import type { ExerciseGuideModule } from './exercise-guides'

const IMAGE_ROOT = '/images/exercise-guides'

export const EXPANDED_RCT_GUIDES: ExerciseGuideModule[] = [
  {
    id: 'acute-ankle-sprain-exercise-rct',
    kind: 'condition',
    selectionLabel: '急性外側踝扭傷',
    theme: 'orange',
    eyebrow: '16 · 2025 隨機對照試驗',
    title: '第一、二級踝扭傷：4 週結構化居家運動',
    summary: '一般照護之外加入每日踝部活動、足趾控制、提踵與平衡進階，4 週功能改善較大。研究用視訊管理，但比較重點是「有沒有加入完整運動方案」，不是遠距與門診是否等效。',
    images: [
      {
        src: `${IMAGE_ROOT}/acute-ankle-sprain-rct.webp`,
        alt: '踝扭傷後的踝泵、毛巾抓地、扶穩提踵與單腳平衡四格圖解',
        step: '4 個代表動作',
        caption: '先活動與足趾控制，再依反應進到提踵和平衡',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '經評估為第一或第二級急性外側踝扭傷、可以依醫療指示逐步承重的成人。骨折、第三級韌帶損傷、明顯不穩或無法承重不適用。',
    dosage: '研究方案為 4 週、每週 5 天、每天約 30 分鐘，從踝泵、足趾活動與毛巾運動開始，再依週次加入提踵、阻力與平衡。實際進度應依腫脹、疼痛及承重能力調整。',
    cue: '先恢復舒服活動與正常承重，不為了趕進度硬做單腳平衡。',
    regression: '保留坐姿踝泵、足趾張合與小幅度活動；提踵改成雙腳且雙手扶穩，平衡先不做。',
    signals: {
      green: '運動後疼痛與腫脹沒有持續上升，走路逐步更順，隔天能回到原本程度。',
      yellow: '跛行加重、腫脹增加或隔天仍明顯更痛：退回前一階並減量。',
      red: '無法走四步、骨性壓痛、快速腫脹變形、麻木冰冷或反覆軟腳：停止並重新評估。',
    },
    evidence: '82 名第一、二級急性踝扭傷患者的 RCT，比較一般照護與一般照護加上 4 週結構化運動；加入運動組在第 4 週的 FAAM 日常與運動功能改善較大。限制是單一場域、介入由遠距方式管理且追蹤只有 4 週，因此不能把結果解讀為所有嚴重度或所有服務模式都適用。',
    audience: '適用於已排除骨折與重度韌帶損傷的急性踝扭傷成人；圖解不能取代急性期診斷與個別承重建議。',
    sources: [
      {
        label: 'Optimizing Ankle Sprain Management in Primary Care: A Randomized Trial of Telerehabilitation Added to Usual Care.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12288864/',
      },
    ],
  },
  {
    id: 'achilles-rupture-early-loading-rct',
    kind: 'condition',
    selectionLabel: '非手術阿基里斯腱斷裂',
    theme: 'teal',
    eyebrow: '17 · 2022 隨機對照試驗',
    title: '非手術治療阿基里斯腱斷裂：早期可控張力負荷',
    summary: '研究在保護固定下，從第 3 週加入可量化的足踝踩踏負荷，改變了癒合肌腱的結構與彈性；這不是自行提前脫靴或做站姿提踵的依據。',
    images: [
      {
        src: `${IMAGE_ROOT}/achilles-rupture-loading-rct.webp`,
        alt: '阿基里斯腱斷裂非手術復健的足踝活動、可控踩踏、坐姿提踵與扶穩站姿提踵圖解',
        step: '階段式負荷',
        caption: '固定保護下由治療團隊設定張力，再逐期進到提踵',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '急性阿基里斯腱完全斷裂、已選擇非手術治療並由骨科與復健團隊依週次追蹤的成人。',
    dosage: '研究從第 3 週開始，每天 3 次做足踝活動 20–30 下；介入組另以專用踩踏器每天 2 次、每次最多 20 下，由約 30 N 逐週增加至 225 N。這些力值不能用一般彈力帶自行複製。',
    cue: '所有負荷都要在護具角度、斷裂間隙與週次獲得團隊確認後進行。',
    regression: '只做醫師允許角度內的足踝活動，維持保護固定；尚未被允許承重時不做任何站姿提踵。',
    signals: {
      green: '保護下活動可控，沒有新的凹陷感、瘀青或隔天腫痛明顯增加。',
      yellow: '小腿緊繃或腫脹增加、動作品質下降：停止加量並聯絡治療團隊。',
      red: '突然彈響、再次失去蹬地能力、傷口或皮膚異常、單側小腿快速腫痛或呼吸困難：立即停止並就醫。',
    },
    evidence: '40 名非手術治療急性阿基里斯腱斷裂患者的 RCT 顯示，早期可控張力組形成較大的肌腱癒合組織且彈性模數較低；研究主要回答組織力學反應，沒有證明患者自評功能一定更好。限制包括樣本小、需專用裝置與嚴格監測。',
    audience: '僅適用於有骨科與復健團隊追蹤的非手術斷裂個案；不是一般阿基里斯腱疼痛或術後患者的通用方案。',
    sources: [
      {
        label: 'Rendek et al. Early Tensile Loading in Nonsurgically Treated Achilles Tendon Ruptures: RCT. Am J Sports Med. 2022.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9527451/',
      },
    ],
  },
  {
    id: 'acute-hamstring-rehab-rct',
    kind: 'condition',
    selectionLabel: '急性腿後肌拉傷',
    theme: 'violet',
    eyebrow: '18 · 2013 隨機對照試驗',
    title: '急性腿後肌拉傷：漸進敏捷穩定 vs 跑步離心進階',
    summary: '兩套三階段主動復健都讓運動員逐步回到跑步與高速動作；研究沒有證明其中一套明顯更快，重點是依症狀與功能標準漸進。',
    images: [
      {
        src: `${IMAGE_ROOT}/hamstring-strain-rehab-rct.webp`,
        alt: '腿後肌拉傷復健的輕鬆慢跑、腳跟壓地、橋式與加速跑四格圖解',
        step: '3 階段代表動作',
        caption: '由低速控制進到橋式與跑步，最後才加入高速動作',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '高速跑步運動中發生、受傷未滿 10 天且影像與臨床已排除完全撕脫的急性腿後肌拉傷運動員。',
    dosage: '研究兩組皆每週居家練習 5 天，依疼痛、動作控制與跑步表現通過三階段；不是按固定日期直接進到衝刺。',
    cue: '動作速度與肌肉長度一次只增加一項，先能控制，再加快或拉長。',
    regression: '回到低強度腳跟壓地或短槓桿橋式，暫停加速跑與長肌長離心。',
    signals: {
      green: '練習與隔天沒有疼痛惡化，走路、慢跑與力量標準逐步恢復。',
      yellow: '局部拉扯感增加、跑姿改變或隔天壓痛上升：退回上一階段。',
      red: '再次突然銳痛、大片瘀青、坐骨附近明顯凹陷或無法正常走路：停止並重新評估。',
    },
    evidence: '25 名完成試驗的急性腿後肌拉傷運動員，比較漸進敏捷／軀幹穩定與漸進跑步／離心強化；回場時間與再傷沒有顯著組間差異。限制是樣本小，且回場時 MRI 常仍未完全恢復，不能只靠「不痛」判定痊癒。',
    audience: '適用於經診斷的急性腿後肌肌肉拉傷運動員；近端肌腱撕脫、完全斷裂或反覆慢性症狀需不同策略。',
    sources: [
      {
        label: 'Silder et al. Clinical and Morphological Changes Following 2 Rehabilitation Programs for Acute Hamstring Strain Injuries: RCT. JOSPT. 2013.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3751188/',
      },
    ],
  },
  {
    id: 'soccer-groin-prevention-rct',
    kind: 'condition',
    selectionLabel: '足球員鼠蹊疼痛預防',
    theme: 'blue',
    eyebrow: '19 · 2022 群集隨機對照試驗',
    title: '高中足球員：哥本哈根內收＋北歐腿後肌預防方案',
    summary: '16 週把內收肌與腿後肌離心訓練放入球隊課表，受傷與缺席天數較一般訓練少；成果來自完整球隊方案，不是單做一個動作。',
    images: [
      {
        src: `${IMAGE_ROOT}/groin-prevention-rct.webp`,
        alt: '足球員進行短槓桿與長槓桿哥本哈根內收、北歐腿後肌和彈力帶內收圖解',
        step: '預防方案',
        caption: '短槓桿起步，逐步加入長槓桿內收與北歐腿後肌',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '無急性鼠蹊疼痛、由教練或物理治療師監督的男性高中足球員季前與賽季訓練。',
    dosage: '研究介入持續 16 週並納入球隊例行訓練；實際組數依短槓桿到長槓桿及個別能力進階，不應一開始就做長槓桿最高難度。',
    cue: '骨盆保持水平、支撐肩不塌；品質下降時先縮短槓桿。',
    regression: '哥本哈根式改成膝部支撐的短槓桿，北歐腿後肌縮小前傾幅度並由同伴協助。',
    signals: {
      green: '內側大腿正常出力，動作後跑動與踢球沒有新增疼痛。',
      yellow: '鼠蹊拉扯、骨盆旋轉或隔天疼痛增加：降階並減少總量。',
      red: '突然銳痛、明顯瘀青、無法加速變向或腹股溝腫塊：停止並評估。',
    },
    evidence: '日本男性高中足球隊的群集 RCT 比較哥本哈根內收、哥本哈根加北歐腿後肌與一般訓練；兩個介入組合併後受傷較少，哥本哈根單獨組的缺席型鼠蹊傷害與平均缺席天數也較低。限制是群集數與事件數不大、可能有選擇偏差，不能直接外推到女性或其他運動。',
    audience: '適用於無症狀或症狀穩定的高中男性足球員預防訓練；已有明顯鼠蹊痛者應先分類診斷。',
    sources: [
      {
        label: 'Effects of a Groin Pain Prevention Program in Male High School Soccer Players: Cluster-RCT. 2022.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9340824/',
      },
    ],
  },
  {
    id: 'acl-criteria-rehab-rct',
    kind: 'condition',
    selectionLabel: '前十字韌帶重建術後',
    theme: 'green',
    eyebrow: '20 · 2025 隨機對照試驗',
    title: 'ACL 重建術後：達標才進階的客觀標準復健',
    summary: '相較以時間為主的一般復健，依腫脹、活動度、力量與功能測試達標後才進到跑跳的方案，在 6 與 12 個月有較好的跳躍表現。',
    images: [
      {
        src: `${IMAGE_ROOT}/acl-secondary-prevention-rct.webp`,
        alt: 'ACL 術後復健的北歐腿後肌、彈力帶深蹲、落地控制與單腳跳圖解',
        step: '達標後進階',
        caption: '肌力與控制先達標，再由雙腳落地進到單腳跳',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '初次 ACL 重建、由手術與復健團隊追蹤的休閒運動員；每個階段都需確認傷口、腫脹、活動度與肌力。',
    dosage: '研究使用完整術後流程：先恢復全活動度、正常步態與力量，再於通過預設功能目標後加入敏捷、跳躍與運動專項。圖中的四項只代表後期內容，不能當成整套術後時間表。',
    cue: '不是「第幾個月到了就跳」，而是膝關節安靜、力量與動作品質達標才進階。',
    regression: '落地改成低高度雙腳，單腳跳先改單腳蹲或踏階；若有積液，回到前一階。',
    signals: {
      green: '訓練後 24 小時內無新增積液或疼痛，動作品質及對稱性逐步改善。',
      yellow: '膝腫、伸直變差、落地內夾或信心下降：暫停跳躍並退階。',
      red: '再次扭轉彈響、快速腫脹、無法伸直或承重、傷口異常：停止並回診。',
    },
    evidence: '40 名 ACL 重建後休閒運動員的隨機試驗比較客觀標準進階與一般復健；客觀標準組在 6、12 個月多項垂直與水平跳躍表現較佳。限制包括小樣本、部分測試完成率差異及介入場域不同，不能據此宣稱一定降低再斷裂率。',
    audience: '適用於由專業團隊管理的 ACL 重建術後運動員；圖中後期跳躍不適合術後早期或膝關節仍腫痛者。',
    sources: [
      {
        label: 'Effects of 2 Different Rehabilitation Programs on Jumping Performance After ACL Reconstruction: RCT.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12237395/',
      },
    ],
  },
  {
    id: 'adolescent-scoliosis-schroth-rct',
    kind: 'condition',
    selectionLabel: '青少年原發性脊柱側彎',
    theme: 'orange',
    eyebrow: '21 · 2016 隨機對照試驗',
    title: '青少年脊柱側彎：Schroth 專項運動加上標準照護',
    summary: '由受訓治療師依曲線型態設定三維自我矯正、呼吸與姿勢耐力，6 個月的 Cobb 角結果優於只接受標準照護。',
    images: [
      {
        src: `${IMAGE_ROOT}/ais-schroth-rct.webp`,
        alt: '青少年進行仰躺、側躺、牆面與坐姿的 Schroth 三維矯正代表姿勢',
        step: '個別化姿勢',
        caption: '軸向延伸、三維自我矯正與呼吸須依曲線型態設定',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '10–18 歲、Cobb 角約 10–45 度、由脊椎團隊診斷為青少年原發性脊柱側彎者。',
    dosage: '研究為每週一次監督課程，加上每天 30–45 分鐘居家練習，持續 6 個月；內容依曲線型態個別化。',
    cue: '先拉長軀幹與建立三維位置，再配合定向呼吸；不是單純向反方向硬彎。',
    regression: '改用仰躺或側躺支撐版本，縮短維持時間；只練治療師親自教過的曲線專屬姿勢。',
    signals: {
      green: '能維持自然呼吸與指定位置，沒有疼痛、暈眩或功能變差。',
      yellow: '憋氣、腰背代償或疼痛增加：增加支撐並請治療師修正。',
      red: '新出現肢體麻木無力、走路改變、呼吸困難或快速惡化夜間痛：停止並評估。',
    },
    evidence: '50 名青少年原發性脊柱側彎患者的 RCT，比較標準照護加 Schroth 與單純標準照護；6 個月最大曲線 Cobb 角的組間差約 3.5 度，方向有利於 Schroth。限制是樣本小、介入高度個別化且需要受訓治療師。',
    audience: '適用於經脊椎專業團隊分類的青少年原發性側彎；不能用通用圖片自行決定矯正方向，也不取代背架或手術評估。',
    sources: [
      {
        label: 'Schreiber et al. Schroth Exercises Added to Standard of Care Lead to Better Cobb Angle Outcomes: RCT. PLoS One. 2016.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5198985/',
      },
    ],
  },
  {
    id: 'plantar-fascia-high-load-rct',
    kind: 'condition',
    selectionLabel: '足底筋膜病變',
    theme: 'teal',
    eyebrow: '22 · 2014 隨機對照試驗',
    title: '足底筋膜病變：墊毛巾的單腳高負荷提踵',
    summary: '鞋墊之外，每隔一天做慢速、漸進加重的單腳提踵，3 個月功能改善快於每日伸展；6–12 個月差異則不再明顯。',
    images: [
      {
        src: `${IMAGE_ROOT}/plantar-fascia-high-load-rct.webp`,
        alt: '前足墊毛巾的雙腳起始、單腳提踵、頂端停留與慢慢下降圖解',
        step: '慢速提踵',
        caption: '毛巾墊起腳趾，3 秒上、停 2 秒、3 秒下',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '超音波與臨床確認、症狀至少 3 個月的足底筋膜病變成人，且能安全扶穩做提踵。',
    dosage: '研究每隔一天訓練，使用前足墊毛巾的單腳提踵，慢速 3 秒上、2 秒停、3 秒下，並隨能力由較多次低負荷進到較少次高負荷。',
    cue: '大拇趾維持在毛巾上，腳踝直上直下；速度慢比抬得高重要。',
    regression: '先雙腳提踵或減少下降深度；無法控制時不加背包重量。',
    signals: {
      green: '訓練中疼痛可控，隔天早晨第一步沒有持續惡化。',
      yellow: '隔天晨痛明顯增加或踝向外翻：減少負荷、組數或下降深度。',
      red: '突然撕裂感、明顯瘀青腫脹、無法踮腳、麻木或夜間靜止痛快速惡化：停止並評估。',
    },
    evidence: '48 名足底筋膜病變患者的 RCT，比較鞋墊加每日伸展與鞋墊加每隔日高負荷提踵；高負荷組 3 個月的足部功能指數較佳，但 1、6、12 個月沒有顯著組間差異。限制是樣本小，且不能推論越重越好。',
    audience: '適用於已確認的慢性足底筋膜病變；急性足底撕裂、骨折、神經病變或無法安全單腳承重者不適用。',
    sources: [
      {
        label: 'Rathleff et al. High-load strength training improves outcome in patients with plantar fasciitis: RCT. 2014.',
        href: 'https://pubmed.ncbi.nlm.nih.gov/25145882/',
      },
    ],
  },
  {
    id: 'distal-radius-early-motion-rct',
    kind: 'condition',
    selectionLabel: '遠端橈骨骨折鋼板固定後',
    theme: 'violet',
    eyebrow: '23 · 2019 隨機對照試驗',
    title: '腕骨折鋼板固定後：早期主動活動與居家運動',
    summary: '術後第 2–3 天拆副木並接受較密集物理治療，長期功能沒有優於固定 2 週後做相同居家運動；研究支持安全時機，也提醒增加門診次數不必然更好。',
    images: [
      {
        src: `${IMAGE_ROOT}/distal-radius-early-motion-rct.webp`,
        alt: '腕骨折固定後的手腕屈伸、前臂旋轉、橈尺偏與手指張合圖解',
        step: '早期主動活動',
        caption: '前臂支撐，以主動活動恢復手腕、旋轉與手指動作',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '掌側鎖定鋼板固定的關節外遠端橈骨骨折成人，已由手術醫師確認固定穩定並允許早期活動。',
    dosage: '研究早期組在術後第 2–3 天開始主動手腕與手指運動，前 2 週每天至少 4 次；2 週後才在疼痛允許下加入被動活動與負荷，6 週後解除限制。實際時程以手術醫囑為準。',
    cue: '前臂有支撐，先做主動、不負重的舒服範圍；不要自行用另一手強壓。',
    regression: '只做手指張合與小幅前臂旋轉，減少手腕幅度；保留醫師指定的副木使用。',
    signals: {
      green: '活動後腫脹可回復，手指循環正常，動作範圍逐步增加。',
      yellow: '傷口拉扯、腫脹或夜間痛增加：減少次數與幅度並聯絡團隊。',
      red: '傷口滲液發熱、手指麻木冰冷、突然變形、劇烈痛或再次跌倒：停止並回診。',
    },
    evidence: '119 名掌側鋼板固定患者的 RCT，比較術後第 2–3 天早期活動加較密集物理治療，與固定 2 週後開始相同居家運動；早期／較密集方案沒有帶來較佳長期功能。這是實際復健時機與劑量的比較，不是服務方式等效研究。',
    audience: '只適用於固定穩定且手術醫師允許活動的遠端橈骨骨折；其他骨折型態或保守固定不可直接套用。',
    sources: [
      {
        label: 'Clementsen et al. Early Mobilization and Physiotherapy vs Late Mobilization and Home Exercises After ORIF of Distal Radius Fractures: RCT. 2019.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6766379/',
      },
    ],
  },
  {
    id: 'carpal-tunnel-gliding-rct',
    kind: 'condition',
    selectionLabel: '輕度腕隧道症候群',
    theme: 'blue',
    eyebrow: '24 · 2021 隨機對照試驗',
    title: '輕度腕隧道：護具之外加入肌腱與神經滑動',
    summary: '兩組都使用中立位護具；額外加入 6 週滑動運動，並沒有顯示更好的組間結果。這篇保留的是「運動加值有限」的負向 RCT，不把常見動作包裝成必然有效。',
    images: [
      {
        src: `${IMAGE_ROOT}/carpal-tunnel-gliding-rct.webp`,
        alt: '腕隧道症候群的直指、鉤拳、桌面手與溫和正中神經滑動圖解',
        step: '滑動序列',
        caption: '手腕接近中立，依序改變手指形狀並做溫和神經滑動',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '電生理與臨床確認為輕度原發性腕隧道症候群、沒有魚際肌萎縮或進行性無力的成人。',
    dosage: '研究運動組每天 3 次，每個姿勢 10 次、維持約 5 秒，持續 6 週；兩組都使用日夜中立位護具。若動作誘發麻電感，不應照表硬做。',
    cue: '手腕保持接近中立，動作是滑動而不是拉到麻。',
    regression: '只做手指肌腱滑動，減少維持時間；暫停任何會讓麻木向手指擴散的神經動作。',
    signals: {
      green: '動作不引發持續麻木，夜間症狀與握力沒有變差。',
      yellow: '麻刺短暫增加或夜間更容易醒：減量並重新檢查姿勢與護具。',
      red: '持續感覺喪失、拇指根肌肉萎縮、物品頻繁掉落或快速進行性無力：停止並儘速評估。',
    },
    evidence: '80 名輕度原發性腕隧道症候群患者的 RCT，比較中立位護具與護具加肌腱／正中神經滑動；6 週後沒有顯著組間效益。限制是追蹤短、只納入輕度個案；結果不能推論運動有害，但不支持宣稱一定能額外改善。',
    audience: '適用於已診斷的輕度腕隧道症候群成人；中重度、肌肉萎縮、糖尿病神經病變或頸神經根問題需個別處理。',
    sources: [
      {
        label: 'Abdolrazaghi et al. Effectiveness of Tendon and Nerve Gliding Exercises in Mild Idiopathic Carpal Tunnel Syndrome: RCT.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10035085/',
      },
    ],
  },
  {
    id: 'lateral-elbow-eccentric-rct',
    kind: 'condition',
    selectionLabel: '慢性外側肘肌腱病變',
    theme: 'green',
    eyebrow: '25 · 2010 隨機對照試驗',
    title: '慢性網球肘：彈性扭力棒手腕伸肌離心訓練',
    summary: '在標準物理治療之外加入手腕伸肌離心扭轉，疼痛、功能與力量改善幅度較大；但試驗只有 21 人，效果大小不宜直接當成一般預測。',
    images: [
      {
        src: `${IMAGE_ROOT}/lateral-elbow-eccentric-rct.webp`,
        alt: '使用無品牌彈性扭力棒進行手腕伸肌離心扭轉的四階段圖解',
        step: '離心扭轉',
        caption: '健側先扭緊，患側手腕慢慢控制扭力棒回正',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '症狀持續至少數週、臨床確認為慢性外側肘肌腱病變，且沒有急性撕裂、骨折或神經症狀的成人。',
    dosage: '原試驗把離心扭轉加入約 7 週標準治療；常用研究流程為每天 3 組、每組 15 次，但阻力與疼痛容許度應由治療師設定。',
    cue: '健側負責扭緊，患側只做慢慢放回的離心控制；肩膀不要跟著聳起。',
    regression: '改用較軟扭力棒、縮小扭轉角度或只做無阻力手腕伸展控制。',
    signals: {
      green: '運動中局部疼痛可控，做完握力與日常使用沒有持續下降。',
      yellow: '隔天疼痛或握力明顯變差：降低阻力、次數或頻率。',
      red: '突然撕裂感、明顯瘀青腫脹、手指持續麻木或手腕伸直無力：停止並評估。',
    },
    evidence: '21 名慢性外側肘肌腱病變患者的隨機試驗，比較標準治療與標準治療加彈性扭力棒離心訓練；加運動組在 DASH、疼痛、壓痛與力量改善較大。限制是樣本非常小、兩組都有共同治療且缺乏長期追蹤。',
    audience: '適用於經確認的慢性外側肘肌腱病變；急性外傷、橈神經壓迫或頸部轉介痛不能直接套用。',
    sources: [
      {
        label: 'Tyler et al. Addition of Isolated Wrist Extensor Eccentric Exercise to Standard Treatment for Chronic Lateral Epicondylosis: RCT. 2010.',
        href: 'https://pubmed.ncbi.nlm.nih.gov/20579907/',
      },
    ],
  },
  {
    id: 'chronic-low-back-stabilization-rct',
    kind: 'condition',
    selectionLabel: '慢性非特異性下背痛',
    theme: 'orange',
    eyebrow: '26 · 2019 隨機對照試驗',
    title: '慢性下背痛：6 週個別化穩定運動與步行',
    summary: '四組主動運動後活動痛都下降；步行與穩定運動也改善部分軀幹耐力。研究沒有證明只有核心運動有效，規律可持續的主動方案同樣重要。',
    images: [
      {
        src: `${IMAGE_ROOT}/low-back-stabilization-rct.webp`,
        alt: '慢性下背痛的腹部控制、死蟲式腳跟點地、橋式與鳥狗式四格圖解',
        step: '穩定運動',
        caption: '從仰躺呼吸控制進到腳跟點地、橋式與鳥狗式',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '症狀超過 3 個月、活動時疼痛且已排除嚴重神經缺損、近期手術、全身性發炎疾病與其他紅旗的非特異性下背痛成人。',
    dosage: '研究介入 6 週；穩定運動依個別能力分級，步行組在平地快走約 30 分鐘。圖解可先每動作 5 次短時間控制，實際總量依隔天反應調整。',
    cue: '保持自然呼吸與骨盆控制；品質穩定後才增加槓桿、時間或次數。',
    regression: '鳥狗式只動一隻手或腳，橋式縮小高度，死蟲式改為單腳跟滑動；也可先從短時間步行開始。',
    signals: {
      green: '正常出力且活動痛沒有持續上升，隔天步行與睡眠維持穩定。',
      yellow: '疼痛向腿部擴散、隔天功能下降或動作需憋氣代償：縮短時間並退階。',
      red: '進行性腿無力、會陰麻木、大小便控制改變、發燒或重大外傷後疼痛：停止並儘速評估。',
    },
    evidence: '48 名完成試驗的慢性下背痛成人被分到柔軟、步行、穩定或穩定加步行，持續 6 週；四組活動痛都下降，步行與合併組的部分軀幹耐力改善。限制是每組人數很少、缺乏不運動對照，不能宣稱某一種運動優於所有其他方案。',
    audience: '適用於已排除特定病理的慢性非特異性下背痛成人；急性外傷、術後或有神經紅旗者不適用。',
    sources: [
      {
        label: 'Suh et al. The Effect of Lumbar Stabilization and Walking Exercises on Chronic Low Back Pain: RCT. Medicine. 2019.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6616307/',
      },
    ],
  },
  {
    id: 'hip-osteoarthritis-exercise-rct',
    kind: 'condition',
    selectionLabel: '髖骨關節炎',
    theme: 'teal',
    eyebrow: '27 · 2014 隨機對照試驗',
    title: '髖骨關節炎：12 週髖部肌力、平衡與活動方案',
    summary: '每週團體課加每週兩次居家練習，相較不治療與安慰性超音波，可減少髖痛並改善功能；一般健康相關生活品質則沒有明顯差異。',
    images: [
      {
        src: `${IMAGE_ROOT}/hip-oa-exercise-rct.webp`,
        alt: '髖骨關節炎的椅子坐站、彈力帶髖外展、低階踏階與扶穩平衡圖解',
        step: '髖部綜合訓練',
        caption: '肌力、踏階與平衡一起進階，不只做單一伸展',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '臨床診斷單側或雙側髖骨關節炎、整體體能可參與運動，且沒有不穩定髖關節置換或嚴重心肺禁忌的成人。',
    dosage: '研究為每週一次 60–90 分鐘團體課，加每週兩次、每次 30–40 分鐘居家練習，共 12 週，內容涵蓋肌力、本體感覺、平衡與柔軟度。',
    cue: '保持軀幹直立與膝蓋朝向腳尖，動作範圍以可控制、隔天可恢復為準。',
    regression: '坐站提高椅面，髖外展減少阻力，踏階降低高度，平衡全程扶穩。',
    signals: {
      green: '運動後疼痛短暫且可回復，走路、坐站或上下階逐步容易。',
      yellow: '跛行加重、夜間痛或隔天僵硬明顯增加：減少阻力與總量。',
      red: '突然無法承重、近期跌倒後劇痛、關節卡住伴變形或發燒紅腫：停止並評估。',
    },
    evidence: '約 209 名納入主要三組分析的髖骨關節炎患者，比較 12 週 THüKo 運動、不治療與安慰性超音波；運動組的 WOMAC 疼痛與功能改善較佳，SF-36 一般生活品質多數面向沒有組間差異。限制是介入包含教育與團體互動，不能把效果歸於單一動作。',
    audience: '適用於症狀性髖骨關節炎且可安全運動的成人；急性骨折、快速惡化或術後限制者需個別處方。',
    sources: [
      {
        label: 'Krauß et al. Exercise Therapy in Hip Osteoarthritis—a Randomized Controlled Trial. Dtsch Arztebl Int. 2014.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4174683/',
      },
    ],
  },
  {
    id: 'older-adult-hyperkyphosis-rct',
    kind: 'condition',
    selectionLabel: '高齡胸椎過度後凸',
    theme: 'violet',
    eyebrow: '28 · 2017 隨機對照試驗',
    title: '高齡過度後凸：6 個月脊柱肌力與姿勢訓練',
    summary: '每週三次、以脊柱伸展肌力與姿勢控制為核心的團體訓練，相較健康教育可小幅改善 Cobb 角與自我形象；整體身體功能沒有明顯組間差異。',
    images: [
      {
        src: `${IMAGE_ROOT}/hyperkyphosis-strength-rct.webp`,
        alt: '高齡過度後凸的鳥狗式、俯臥軀幹抬起、側躺胸椎旋轉與靠牆姿勢圖解',
        step: '脊柱肌力與姿勢',
        caption: '以軸向延伸、背伸肌力與胸椎活動建立可維持的姿勢',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '60 歲以上、胸椎 Cobb 角至少 40 度，能安全參與團體運動且沒有不穩定骨折或嚴重神經症狀的成人。',
    dosage: 'SHEAF 試驗為每週 3 次、每次約 1 小時、持續 6 個月；肌力動作多由 2 組 8 次開始，依中等自覺強度逐步增加。',
    cue: '想像頭頂向上延伸、胸骨輕抬；避免用腰椎過度後彎或抬頭代償。',
    regression: '鳥狗式只伸手或腳，俯臥抬身改成胸前墊毛巾的小幅動作，靠牆時不強壓頭部。',
    signals: {
      green: '背部正常出力、呼吸順暢，練後站立與日常活動沒有變差。',
      yellow: '疼痛達中重度、頭暈、頸部代償或隔天疲勞過久：減量並調整姿勢。',
      red: '新發劇烈背痛、跌倒後疼痛、肢體麻木無力或呼吸困難：停止並評估骨折或其他原因。',
    },
    evidence: '99 名 60 歲以上過度後凸成人的 RCT，比較 6 個月脊柱肌力／姿勢訓練與健康教育；介入組 Cobb 角平均組間改善約 3 度，自我形象改善，但多數身體功能指標無顯著差異。限制是需要高頻監督且受試者整體健康。',
    audience: '適用於已評估的高齡過度後凸成人；疑似壓迫性骨折、嚴重骨質疏鬆疼痛或神經症狀者需先診斷。',
    sources: [
      {
        label: 'Katzman et al. Targeted Spine Strengthening Exercise and Posture Training for Hyperkyphosis: SHEAF RCT.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5873977/',
      },
    ],
  },
  {
    id: 'diabetic-neuropathy-foot-ankle-rct',
    kind: 'condition',
    selectionLabel: '糖尿病周邊神經病變',
    theme: 'blue',
    eyebrow: '29 · 2022 隨機對照試驗',
    title: '糖尿病周邊神經病變：12 週足踝運動方案',
    summary: '一般照護之外加入足趾、踝部肌力與平衡訓練，可改善快速步行速度、踝活動與震動感覺；日常步數、症狀與腳趾力量不一定跟著改善。',
    images: [
      {
        src: `${IMAGE_ROOT}/diabetic-foot-ankle-rct.webp`,
        alt: '糖尿病周邊神經病變的足趾控制、彈力帶踝背屈、扶穩提踵與串聯平衡圖解',
        step: '足踝綜合訓練',
        caption: '先檢查皮膚，再做足趾控制、踝肌力、提踵與扶穩平衡',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '糖尿病周邊神經病變、足部風險分級約 1–2、皮膚完整且已由醫療團隊確認可運動的成人。',
    dosage: '研究持續 12 週，每週 2 次監督課與 2 次居家練習；每次都應先檢查足底、鞋襪與壓力點，再依能力做足趾、踝部與平衡進階。',
    cue: '感覺變差時不能只靠疼痛判斷負荷；每次前後都要用眼睛檢查皮膚。',
    regression: '全部改坐姿，使用輕阻力；平衡只在雙手可扶穩處進行，皮膚有異常時暫停承重運動。',
    signals: {
      green: '皮膚完整、沒有新壓痕水泡，運動後走路與疲勞可回復。',
      yellow: '紅點或壓痕超過短時間不退、腳踝腫或平衡不穩：停止該動作並檢查鞋襪與負荷。',
      red: '傷口、水泡、感染徵象、足部變熱腫脹變形或顏色循環異常：立即停止並接受足部評估。',
    },
    evidence: '78 名糖尿病周邊神經病變患者的 RCT，比較一般照護與一般照護加 12 週足踝運動；介入組快速步行速度、踝活動與震動感覺改善，但自選步速、日常步數、症狀與趾屈力量未顯示組間改善。限制是只納入足部風險 1–2 且有專業監督者。',
    audience: '適用於皮膚完整且已分級的糖尿病周邊神經病變成人；活動性潰瘍、Charcot 足疑慮或嚴重循環問題不適用。',
    sources: [
      {
        label: 'Matias et al. Foot–Ankle Therapeutic Exercise Program Can Improve Gait Speed in People With Diabetic Neuropathy: RCT. Sci Rep. 2022.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9082985/',
      },
    ],
  },
  {
    id: 'breast-cancer-prosper-rct',
    kind: 'condition',
    selectionLabel: '乳癌手術後肩臂功能',
    theme: 'green',
    eyebrow: '30 · 2021 隨機對照試驗',
    title: '乳癌手術後：PROSPER 漸進肩活動與肌力方案',
    summary: '高風險女性在術後 7–10 天開始由物理治療師帶領、逐步從活動度進到阻力訓練，12 個月肩臂功能與疼痛優於一般照護，且未增加淋巴水腫。',
    images: [
      {
        src: `${IMAGE_ROOT}/breast-cancer-prosper-rct.webp`,
        alt: '乳癌手術後的牆面滑手、雙手輔助抬臂、彈力帶划船與對角線阻力動作圖解',
        step: '活動到肌力',
        caption: '先恢復舒服活動，再於傷口與團隊允許後加入阻力',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '非重建乳癌手術後、被判定有肩臂功能問題高風險，傷口與引流狀況已由手術團隊確認可開始活動的成年女性。',
    dosage: 'PROSPER 在術後 7–10 天開始，並於約 1、3 個月追蹤；早期活動度多每天 2 次，約第 4 週後才依恢復加入每週 2–3 次、8–12 次的漸進阻力。',
    cue: '先讓傷口、胸壁與肩胛能舒服移動，再加阻力；不追求一次抬到最高。',
    regression: '牆面滑手縮小高度，改成雙手輔助抬臂；阻力動作先不用彈力帶。',
    signals: {
      green: '傷口狀況穩定，活動後緊繃可回復，手臂腫脹沒有持續增加。',
      yellow: '胸壁拉扯、肩痛或手臂沉重感增加：減少幅度與阻力並聯絡團隊。',
      red: '傷口紅腫滲液發燒、手臂快速腫脹變色、呼吸困難或突發劇痛：停止並就醫。',
    },
    evidence: '392 名乳癌手術後高風險女性的多中心 RCT，比較 PROSPER 漸進運動與一般照護；12 個月 DASH 功能與疼痛改善較佳，沒有觀察到淋巴水腫或手術併發症增加。限制是只納入非重建手術且方案有專業評估與多次追蹤。',
    audience: '適用於手術團隊允許、且有肩臂問題風險的乳癌術後女性；重建手術、傷口問題或淋巴水腫需個別處方。',
    sources: [
      {
        label: 'Bruce et al. Exercise to Prevent Shoulder Problems After Breast Cancer Surgery: PROSPER RCT. BMJ. 2021.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8579424/',
      },
    ],
  },
  {
    id: 'otago-fall-prevention-rct',
    kind: 'condition',
    selectionLabel: '高跌倒風險長者',
    theme: 'orange',
    eyebrow: '31 · 2019 隨機對照試驗',
    title: '曾跌倒高齡者：12 個月 Otago 居家肌力與平衡',
    summary: '物理治療師個別調整的居家肌力、平衡與步行計畫，相較老年醫療一般照護，可降低 12 個月內跌倒發生率。',
    images: [
      {
        src: `${IMAGE_ROOT}/otago-fall-prevention-rct.webp`,
        alt: '高跌倒風險長者扶穩做屈膝、提踵、坐站與串聯站立圖解',
        step: 'Otago 代表動作',
        caption: '在穩固支撐旁練腿力與平衡，再搭配安全步行',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '70 歲以上、過去 12 個月跌倒或被判定為高跌倒風險，且能在物理治療師評估後居家練習的社區長者。',
    dosage: '研究為 12 個月個別化 Otago：肌力與平衡每週 3 次，另每週 2 次約 30 分鐘步行，並由物理治療師定期家訪與進階。',
    cue: '先把支撐放在手邊，能穩定完成才減少扶手；平衡訓練不是故意把自己逼到跌倒。',
    regression: '所有站姿動作雙手扶穩，坐站提高椅面；平衡改成雙腳併攏，不做串聯或單腳。',
    signals: {
      green: '動作穩定、沒有近跌倒，隔天疲勞可回復，步行信心逐步增加。',
      yellow: '需要抓住支撐、頭暈或步態明顯變差：立即坐下並降低難度。',
      red: '跌倒撞頭、無法承重、新發胸痛昏厥、單側無力或說話改變：停止並依急症處理。',
    },
    evidence: '345 名 70 歲以上、曾跌倒或高風險長者的 RCT，比較老年醫療一般照護與一般照護加 12 個月個別化 Otago；介入組 236 次跌倒、對照組 366 次，估計發生率比 0.64。限制是需要家訪與長期支持，不能只靠四張圖複製效果。',
    audience: '適用於經跌倒風險評估且有安全環境與追蹤的社區長者；不穩定心血管症狀、急性疾病或無法安全站立者需先處理。',
    sources: [
      {
        label: 'Liu-Ambrose et al. Effect of a Home-Based Exercise Program on Subsequent Falls Among Community-Dwelling High-Risk Older Adults: RCT. JAMA. 2019.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6549299/',
      },
    ],
  },
  {
    id: 'rheumatoid-hand-sarah-rct',
    kind: 'condition',
    selectionLabel: '類風濕性關節炎手部功能',
    theme: 'teal',
    eyebrow: '32 · 2015 隨機對照試驗',
    title: '類風濕性關節炎：SARAH 漸進手部伸展與肌力',
    summary: '穩定藥物治療之外加入治療師量身調整的手部伸展與漸進肌力，12 個月手部功能較佳；延長追蹤時差異縮小，遵從性是重要限制。',
    images: [
      {
        src: `${IMAGE_ROOT}/ra-hand-sarah-rct.webp`,
        alt: '類風濕性關節炎手部的溫和手腕伸展、彈力帶張指、軟球握力與黏土捏力圖解',
        step: '手部漸進訓練',
        caption: '柔軟度與輕阻力並行，依關節發炎與功能調整',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '類風濕性關節炎藥物至少相對穩定，但仍有手部疼痛、無力或日常功能限制的成人。',
    dosage: 'SARAH 透過 12 週內 6 次治療師會談，教授 7 個柔軟與 4 個肌力動作，並以彈力帶、球或黏土逐步增加阻力；長期效果依持續練習而定。',
    cue: '動作在可控制範圍，不用力擠壓腫痛關節；阻力只在發炎穩定時增加。',
    regression: '急性發炎時先做短時間溫和活動，不加阻力；改用較軟球或徒手張合。',
    signals: {
      green: '關節沒有持續腫熱，運動後手部功能與疲勞可回復。',
      yellow: '關節腫痛或晨僵明顯增加：暫停阻力、減量並與風濕團隊討論。',
      red: '關節快速紅腫發熱、突然失去肌腱功能、手指持續麻木或感染徵象：停止並就醫。',
    },
    evidence: '490 名類風濕性關節炎手部功能受限成人的 RCT，比較一般關節保護照護與加上 SARAH 漸進手部運動；12 個月功能改善較佳且具成本效益。延伸追蹤到平均約 26 個月時組間差異不再明顯，且遵從性下降。',
    audience: '適用於藥物相對穩定且由風濕與手部治療團隊評估的類風濕性關節炎成人；急性嚴重發炎或肌腱斷裂疑慮不適用。',
    sources: [
      {
        label: 'Lamb et al. Strengthening and Stretching for Rheumatoid Arthritis of the Hand: SARAH RCT. Lancet. 2015.',
        href: 'https://pubmed.ncbi.nlm.nih.gov/25308290/',
      },
      {
        label: 'Williamson et al. Extended Follow-up of the SARAH Randomised Controlled Trial.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5775458/',
      },
    ],
  },
  {
    id: 'tmd-jaw-opening-rct',
    kind: 'condition',
    selectionLabel: '疼痛性顳顎關節障礙',
    theme: 'violet',
    eyebrow: '33 · 2022 隨機對照試驗',
    title: '疼痛性顳顎障礙：8 週主動張口運動',
    summary: '兩組每天練習張口；在專業指導下做到疼痛邊緣的輔助組，最大張口幅度改善較大，但也較難執行。本站圖解只呈現安全的主動版本，不建議自行強推下顎。',
    images: [
      {
        src: `${IMAGE_ROOT}/tmd-jaw-opening-rct.webp`,
        alt: '顳顎關節障礙的放鬆下顎、鏡前直線張口、治療師量測與重複主動張口圖解',
        step: '主動張口控制',
        caption: '肩頸放鬆、鏡前直線張口；需要加壓時必須由專業人員指導',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '經牙科或口顎專業診斷為疼痛相關 TMD、最大張口小於約 40 mm，且已排除脫臼、骨折與感染的成人。',
    dosage: '研究兩組每天 4 回合，每回合 5 次、每次維持 10 秒，持續 8 週；疼痛邊緣的輔助方式較具挑戰，只應在專業人員明確教學後使用。',
    cue: '舌頭與肩頸放鬆，鏡中確認下顎直線移動；不要用手把嘴硬撐開。',
    regression: '只做不痛的小幅主動張口，減少維持時間與次數；暫停所有外力輔助。',
    signals: {
      green: '張口路徑平順，運動後疼痛可回復，沒有新的鎖住或咬合改變。',
      yellow: '彈響伴痛、偏斜加重或隔天咀嚼更痛：縮小幅度並回診調整。',
      red: '下顎鎖住無法開合、近期外傷、發燒腫脹、吞嚥呼吸困難或突然咬合改變：停止並就醫。',
    },
    evidence: '61 名疼痛相關 TMD 且張口受限者的隨機試驗，比較做到疼痛邊緣的輔助張口與不痛的主動張口；兩組都改善，輔助組在 4、8 週最大無輔助張口較大，但自覺較難。限制是小型試驗、追蹤短，不能推論越痛越有效。',
    audience: '適用於經口顎專業診斷與教學的疼痛性 TMD；圖解不授權自行做疼痛性被動加壓。',
    sources: [
      {
        label: 'Tobe et al. Jaw-Opening Exercise With and Without Pain for Pain-Related Temporomandibular Disorders: RCT. 2022.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9779752/',
      },
    ],
  },
  {
    id: 'midportion-achilles-eccentric-rct',
    kind: 'condition',
    selectionLabel: '慢性中段阿基里斯腱病變',
    theme: 'blue',
    eyebrow: '34 · 2007 隨機對照試驗',
    title: '慢性中段阿基里斯腱病變：12 週漸進離心提踵',
    summary: '相較等待觀察，12 週漸進離心負荷在 4 個月時有較好的 VISA-A、疼痛與自評恢復；這篇直接測試運動負荷效果，不是服務方式的不劣性研究。',
    images: [
      {
        src: `${IMAGE_ROOT}/achilles-eccentric-rct.webp`,
        alt: '慢性中段阿基里斯腱病變以雙腳上升、單腳轉移、直膝與屈膝慢慢下降的圖解',
        step: '離心提踵',
        caption: '雙腳上升，將重量移到患側後以直膝或屈膝慢慢下降',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: '症狀超過 6 個月、位置在阿基里斯腱中段，且已排除急性斷裂與插入點病變的成人。',
    dosage: '研究採 12 週、每天 2 次的漸進離心小腿訓練；經典方案包含直膝與屈膝慢降，各 3 組 15 次，並在可承受後加重。高總量並非所有人起始劑量。',
    cue: '用雙腳回到頂端，患側負責慢慢下降；負荷要漸進，不追求劇痛。',
    regression: '先雙腳提踵、縮小下降深度或減少組數；需要時在平地而非階梯進行。',
    signals: {
      green: '局部疼痛可控，隔天走路與晨僵沒有持續惡化，提踵能力逐步增加。',
      yellow: '隔天僵痛明顯上升或提踵高度下降：降低總量、負重或下降深度。',
      red: '突然彈響、凹陷、大片瘀青、完全無法單腳踮起或單側小腿快速腫痛：停止並評估。',
    },
    evidence: '75 名慢性中段阿基里斯腱病變患者被分到離心負荷、低能量震波或等待觀察；4 個月時離心組 VISA-A 由 51 增至 76，60% 自評完全恢復或大幅改善，等待組為 24%，且所有主要結果介入組都優於等待。限制是每組 25 人、對象為先前治療失敗的慢性個案。',
    audience: '適用於已確認的慢性中段阿基里斯腱病變；插入點疼痛、急性斷裂、術後或無法安全提踵者不適用。',
    sources: [
      {
        label: 'Rompe et al. Eccentric Loading, Shock-Wave Treatment, or Wait-and-See for Midportion Achilles Tendinopathy: RCT. 2007.',
        href: 'https://pubmed.ncbi.nlm.nih.gov/17244902/',
      },
    ],
  },
  {
    id: 'parkinson-tai-chi-rct',
    kind: 'condition',
    selectionLabel: '巴金森病姿勢穩定',
    theme: 'green',
    eyebrow: '35 · 2012 隨機對照試驗',
    title: '輕中度巴金森病：24 週太極姿勢與重心訓練',
    summary: '每週兩次監督太極，相較阻力與伸展，可改善極限穩定與方向控制；跌倒次數低於伸展組，但沒有證明一定優於阻力訓練。',
    images: [
      {
        src: `${IMAGE_ROOT}/parkinson-tai-chi-rct.webp`,
        alt: '巴金森病患者在治療師監督下做側向重心轉移、踝部搖擺、軀幹旋轉與前後步伐太極圖解',
        step: '太極重心控制',
        caption: '在監督下練重心轉移、軀幹旋轉與前後步伐',
        width: 1254,
        height: 1254,
      },
    ],
    suitableFor: 'Hoehn–Yahr 第 1–4 期、能在監督下站立與練習的輕至中度巴金森病成人。',
    dosage: '研究為每週 2 次、每次 60 分鐘、持續 24 週；內容涵蓋寬窄站姿、重心轉移、踝部搖擺、軀幹旋轉與前後步伐。',
    cue: '步幅與重心移動保持可控，先有治療師或穩固支撐，再增加範圍。',
    regression: '改成扶穩的小幅側向重心轉移或坐姿軀幹旋轉；不做閉眼或快速轉身。',
    signals: {
      green: '步伐穩定、沒有近跌倒，運動後疲勞可回復，方向控制逐步改善。',
      yellow: '凍結步態、頭暈、動作遲緩突然加重或需要抓扶：立即降低範圍並休息。',
      red: '跌倒撞頭、昏厥、胸痛、新發單側無力或藥效明顯異常：停止並依急症或神經科流程處理。',
    },
    evidence: '195 名第 1–4 期巴金森病成人的 RCT，比較太極、阻力與伸展，每週 2 次共 24 週；太極在最大重心移動與方向控制優於兩組，跌倒率低於伸展組，但未明確優於阻力組。限制是課程高度監督，不能直接等同自行看圖練習。',
    audience: '適用於能在專業監督下練習的輕中度巴金森病成人；頻繁凍結、低血壓、近期跌倒或無法安全站立者需先個別評估。',
    sources: [
      {
        label: 'Li et al. Tai Chi and Postural Stability in Patients With Parkinson’s Disease: RCT. N Engl J Med. 2012.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3285459/',
      },
    ],
  },
]
