import type {
  ExerciseGuideImage,
  ExerciseGuideModule,
} from './exercise-guides'

const IMAGE_ROOT = '/images/exercise-guides'

function trialImage(slug: string, alt: string, caption: string): ExerciseGuideImage {
  return {
    src: `${IMAGE_ROOT}/${slug}.webp`,
    alt,
    step: '4 個代表動作',
    caption: `${caption}（依試驗內容重繪示意，非論文原圖）`,
    width: 1254,
    height: 1254,
  }
}

const MUSCULOSKELETAL_SIGNALS = {
  green: '動作可控制，只有可接受的出力或輕微不適，且運動後至隔天能回到原本程度。',
  yellow: '疼痛、腫脹或疲勞明顯增加，隔天仍未回復：減少阻力、次數或活動範圍，必要時請治療師調整。',
  red: '新外傷、突然失去力量或承重能力、明顯變形、持續麻木無力或症狀快速惡化：停止並儘速評估。',
}

const POSTOPERATIVE_SIGNALS = {
  green: '傷口與腫脹穩定，動作品質可維持，運動後至隔天沒有持續惡化。',
  yellow: '關節熱腫、夜間痛或隔天功能明顯變差：退回前一階段並聯絡手術或復健團隊。',
  red: '傷口滲液或發燒、突然彈響伴隨失能、單側肢體快速腫痛、胸痛或呼吸困難：停止並立即就醫。',
}

const NEURO_BALANCE_SIGNALS = {
  green: '能在安全支撐下完成，疲勞可恢復，沒有新增暈眩、步態或神經症狀。',
  yellow: '動作品質下降、接近跌倒、疲勞或症狀延續到隔天：增加支撐、縮短時間並與治療師討論。',
  red: '跌倒撞擊、新出現單側無力或感覺改變、劇烈頭痛、昏厥、胸痛或呼吸困難：停止並立即就醫。',
}

const CARDIOPULMONARY_SIGNALS = {
  green: '呼吸與心跳會上升但仍可控制，停止後能逐步恢復，沒有胸痛或暈眩。',
  yellow: '比平常更喘、心悸、頭暈或疲勞延續到隔天：立刻降速或休息，並依團隊設定調整。',
  red: '胸痛、昏厥、呼吸困難休息後不改善、嘴唇發紫，或監測數值超過醫療團隊設定界線：停止並立即求助。',
}

export const RECENT_RCT_GUIDES: ExerciseGuideModule[] = [
  {
    id: 'rotator-cuff-grasp-rct',
    kind: 'condition',
    selectionLabel: '旋轉肌袖相關肩痛',
    bodyRegion: '上肢與手部',
    searchAliases: ['肩夾擠', '旋轉肌袖', '肩膀痛', '抬手痛', 'GRASP'],
    theme: 'orange',
    eyebrow: '2021 GRASP 隨機對照試驗',
    title: '旋轉肌袖肩痛：一次最佳建議與漸進運動比較',
    summary: '大型務實型試驗顯示，最多 6 次治療師帶領的漸進運動，在 12 個月的肩痛與功能上沒有優於一次完整建議；重點是取得可持續、可調整的運動處方。',
    images: [trialImage('rotator-cuff-grasp-rct', '旋轉肌袖肩痛的肩部輔助活動、牆面滑動、彈力帶外旋與划船四格示意', '由舒服活動開始，再依反應加入外旋與划船阻力')],
    suitableFor: '18 歲以上、肩痛未滿 6 個月且經臨床判斷為旋轉肌袖相關疾病者；近期重大外傷、脫臼、頸椎神經症狀或需手術的完整撕裂不適用。',
    dosage: 'GRASP 比較一次約 60 分鐘的最佳實務建議，與 16 週內最多 6 次、每次約 30 分鐘的個別漸進運動。動作與負荷由治療師依疼痛、活動與力量選擇，並以居家執行為主。',
    cue: '選能穩定重複、症狀可回復的動作；增加阻力前先確認肩胛與上臂控制。',
    regression: '先保留桌面或牆面輔助抬手與低阻力等長收縮，縮小抬手角度。',
    signals: MUSCULOSKELETAL_SIGNALS,
    evidence: '708 人、四組因子設計的多中心 RCT；漸進運動與一次最佳建議在 12 個月 SPADI 沒有具臨床意義的差異。研究規模大且有完整介入手冊；結果不代表「運動無效」，而是較多治療次數未帶來額外長期優勢。',
    audience: '適用於已排除急性結構性損傷的旋轉肌袖相關肩痛成人；圖解是代表動作，不是固定四動作處方。',
    sources: [{ label: 'Hopewell et al. GRASP factorial RCT. Lancet. 2021.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8343092/' }],
  },
  {
    id: 'shoulder-dislocation-sinex-rct',
    kind: 'condition',
    selectionLabel: '外傷性前肩脫臼',
    bodyRegion: '上肢與手部',
    searchAliases: ['肩脫臼', '肩關節不穩', '肩膀滑出來', 'SINEX', '前肩不穩'],
    theme: 'teal',
    eyebrow: '2020 SINEX 隨機對照試驗',
    title: '前肩脫臼後：12 週神經肌肉控制進階',
    summary: '治療師監督的 7 動作 SINEX 方案比標準居家運動改善更多自評功能，但差距略低於預設最小重要差異，不能解讀成所有人都免除手術評估。',
    images: [trialImage('shoulder-dislocation-sinex-rct', '前肩脫臼後的閉鏈承重、彈力帶外旋、牆面控制與進階穩定四格示意', '由低負荷感覺控制逐步進到方向與速度挑戰')],
    suitableFor: '18–39 歲、影像確認的初次或復發性外傷性前肩脫臼，復位後仍覺功能下降，且沒有需手術骨折或超過五次脫臼者。',
    dosage: '12 週、7 個神經肌肉動作；由基礎級每天 2 組×20 下，依疼痛、控制與穩定度進到最高級每週 3 次、2 組×10 下。由物理治療師監督分級。',
    cue: '肱骨頭保持穩定，先精準再加速度、阻力或不穩定面。',
    regression: '從手臂靠身、低阻力等長收縮或桌面閉鏈重心轉移開始。',
    signals: MUSCULOSKELETAL_SIGNALS,
    evidence: '56 人 RCT；SINEX 的 WOSI 改善優於標準居家組，但組間差距略低於最小臨床重要差異。原文補充資料提供分級方案；樣本小且不包含需手術的骨性損傷。',
    audience: '適用於 18–39 歲、完成復位與專業評估後的非手術前肩不穩；試驗結果不能直接外推到其他年齡層，也不可在仍疑似脫臼時自行測試。',
    sources: [{ label: 'Eshøj et al. SINEX for traumatic anterior shoulder dislocation: RCT. 2020.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6993151/' }],
  },
  {
    id: 'reverse-shoulder-early-active-rct',
    kind: 'condition',
    selectionLabel: '反式人工肩關節術後',
    bodyRegion: '上肢與手部',
    searchAliases: ['反式肩關節', '人工肩關節術後', 'RTSA', '肩關節置換', '術後抬手'],
    theme: 'violet',
    eyebrow: '2021 隨機對照試驗',
    title: '反式人工肩關節：早期與延後主動復健比較',
    summary: '早期加入三角肌與外旋肌訓練，與延後主動方案在一年疼痛與功能皆改善，沒有明顯組間優勢；是否提前必須看手術方式與組織修補。',
    images: [trialImage('reverse-shoulder-early-active-rct', '反式人工肩關節術後的手腕活動、桌面滑手、輔助抬手與低阻力外旋四格示意', '依術後週次由遠端活動與輔助動作逐步加入主動控制')],
    suitableFor: '初次反式人工肩關節置換，且手術團隊確認可採該試驗路徑者；骨折、翻修、肩胛棘風險或有肌腱修補者可能需更保守。',
    dosage: '原文 Table 1 列出各期動作。第 2–6 週的活動與輔助活動多為每天 2 次、2–3 組×10–15 下；早期組另做約 20% 最大出力的等長收縮，每天 3 次、10 次×30 秒。',
    cue: '術後限制優先於圖示；不要自行跨過手術團隊設定的角度、重量或週次。',
    regression: '只做手腕手指活動與團隊允許的被動／輔助範圍，暫不加入阻力。',
    signals: POSTOPERATIVE_SIGNALS,
    evidence: '多中心 RCT 比較早期主動與延後主動復健；兩組至 12 個月均改善，未見大型組間效果。原文 Table 1 有完整階段、動作與劑量；研究使用特定手術方式，不能外推到所有置換與修補。',
    audience: '僅供反式肩關節術後與手術／復健團隊核對處方，不是自行提前活動的依據。',
    sources: [{ label: 'Edwards et al. Two rehabilitation approaches after reverse total shoulder arthroplasty: RCT. 2021.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8512973/' }],
  },
  {
    id: 'frozen-shoulder-neuromuscular-rct',
    kind: 'condition',
    selectionLabel: '原發性冰凍肩',
    bodyRegion: '上肢與手部',
    searchAliases: ['五十肩', '冰凍肩', '沾黏性肩關節囊炎', '肩膀卡住', '肩活動受限'],
    theme: 'blue',
    eyebrow: '2023 隨機對照試驗',
    title: '冰凍肩：神經肌肉控制與肌力運動比較',
    summary: '在相同常規治療上加入神經肌肉練習，8 週疼痛與部分主動角度改善較大；試驗只有 40 人，結果需配合病程階段與可耐受程度。',
    images: [trialImage('frozen-shoulder-neuromuscular-rct', '冰凍肩的桌面滑手、牆面滑動、低阻力外旋與閉鏈控制四格示意', '不強拉終點，先以可控制活動與肩胛肱骨協調累積')],
    suitableFor: '40 歲以上、臨床診斷為凍結期或冰凍期的單側原發性冰凍肩；外傷、手術後僵硬與其他肩病因不等同。',
    dosage: '兩組皆每天 1 次、每週 5 天、共 8 週並接受常規治療；神經肌肉組依圖文方案練習閉鏈位置覺、肩胛與旋轉肌控制，實際組次由治療師依階段設定。',
    cue: '以能放鬆呼吸的角度練控制，不用疼痛換活動度。',
    regression: '改成仰躺或桌面支撐的輔助抬手，降低阻力並縮小角度。',
    signals: MUSCULOSKELETAL_SIGNALS,
    evidence: '40 人、單盲 RCT；神經肌肉組在疼痛、主動屈曲與內外旋的組別×時間效果較佳。原文與補充資料描述動作；限制為單中心、小樣本、追蹤僅 8 週。',
    audience: '適用於已確認原發性冰凍肩者；糖尿病、術後或外傷後僵硬應個別調整。',
    sources: [{ label: 'Positive effects of neuromuscular exercises in idiopathic frozen shoulder: RCT. BMC Musculoskelet Disord. 2023.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9854051/' }],
  },
  {
    id: 'whiplash-neck-specific-rct',
    kind: 'condition',
    selectionLabel: '慢性揮鞭症相關頸痛',
    bodyRegion: '頭頸與下顎',
    searchAliases: ['揮鞭症', '車禍頸痛', 'whiplash', '慢性頸痛', '頸部不穩'],
    theme: 'green',
    eyebrow: '2023 隨機對照試驗',
    title: '慢性揮鞭症：網路支持與診所頸部專項運動比較',
    summary: '四次治療師會面加網路支持的 12 週方案，整體結果沒有顯示比每週兩次診所運動差；前提是先完成個別評估並有治療師回饋。',
    images: [trialImage('whiplash-neck-specific-rct', '慢性揮鞭症的仰躺小幅點頭、低負荷等長、肩胛控制與坐姿頸部耐力四格示意', '先做深層頸肌控制，再漸進耐力與肩胛協調')],
    suitableFor: '揮鞭傷後 6 個月至 5 年、持續頸部障礙且無進行性神經病變的成人。',
    dosage: '12 週頸部專項運動；診所組每週 2 次，網路組有 4 次治療師面訪並依線上分級每日練習。由低負荷深層頸肌控制進到頸部與肩胛耐力。',
    cue: '頸部維持小幅精準，不以快速甩動或大幅拉伸追求感覺。',
    regression: '仰躺有支撐的小幅點頭或低強度等長收縮，縮短維持時間。',
    signals: NEURO_BALANCE_SIGNALS,
    evidence: '140 人非劣性 RCT；網路支持組與每週兩次診所組在主要頸部障礙結果未見重要差異。研究有可重現的 12 週分級方案；不能外推到急性外傷、骨折或進行性神經症狀。',
    audience: '適用於已完成車禍後紅旗與神經檢查的慢性揮鞭症成人。',
    sources: [{ label: 'Internet-supported neck-specific exercise versus clinic-based exercise for chronic whiplash: RCT. 2023.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10337460/' }],
  },
  {
    id: 'hand-oa-app-rct',
    kind: 'condition',
    selectionLabel: '症狀性手部骨關節炎',
    bodyRegion: '上肢與手部',
    searchAliases: ['手指退化', '手關節炎', '手指僵硬', '握力痛', 'CareHand'],
    theme: 'orange',
    eyebrow: '2023 隨機對照試驗',
    title: '手部骨關節炎：應用程式影片與紙本居家運動比較',
    summary: '應用程式與紙本都提供 12 週多模式居家照護；應用程式組部分疼痛與上肢功能結果較佳，但主要手功能在 3 個月沒有明顯組間差異。',
    images: [trialImage('hand-oa-app-rct', '手部骨關節炎的手指張合、拇指對指、橡皮筋外展與輕握軟球四格示意', '以無痛或低痛範圍練活動、精細控制與輕阻力')],
    suitableFor: '45 歲以上、單側或雙側症狀性手部骨關節炎成人；急性紅腫熱、近期外傷或發炎性關節炎需先評估。',
    dosage: '兩組都接受 12 週居家運動、教育與自我管理；應用程式以影片示範與紀錄支持，並每月電話追蹤。動作頻率與進階依研究中的應用程式／紙本處方，不應為追求握力而誘發關節腫痛。',
    cue: '手腕保持中立、手指慢慢動；先動作品質，再增加橡皮筋或軟球阻力。',
    regression: '只做溫和關節活動與桌面支撐的對指，暫停擠壓阻力。',
    signals: MUSCULOSKELETAL_SIGNALS,
    evidence: '74 人務實型多中心 RCT；主要手功能在 3 個月未改善，應用程式組在部分疼痛與上肢功能次要結果較佳。原文說明多模式方案與影片交付；樣本小，不能把效果歸因於單一動作。',
    audience: '適用於穩定的手部骨關節炎；應用程式是交付工具，不代表所有商用手部應用程式都有效。',
    sources: [{ label: 'CareHand mobile app for symptomatic hand osteoarthritis: pragmatic RCT. 2023.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10035439/' }],
  },
  {
    id: 'thumb-oa-combo-rct',
    kind: 'condition',
    selectionLabel: '拇指基底關節骨關節炎',
    bodyRegion: '上肢與手部',
    searchAliases: ['拇指根部痛', '虎口痛', 'CMC 關節', '拇指退化', 'COMBO'],
    theme: 'teal',
    eyebrow: '2021 COMBO 隨機臨床試驗',
    title: '拇指基底關節炎：護具、運動與局部用藥的多模式組合',
    summary: '含教育、護具、手部運動與 1% 雙氯芬酸鈉凝膠的多模式組合，對功能有小到中等效果，但主要疼痛結果沒有明顯優勢；不能把整組效果歸因於單一運動或藥物。',
    images: [trialImage('thumb-oa-combo-rct', '拇指基底關節炎的拇指張開、對指、低阻力外展與輕捏軟物四格示意', '前臂支撐、手腕中立，練拇指定位與低負荷控制')],
    suitableFor: '40 歲以上、臨床與影像確認的拇指基底關節骨關節炎成人；近期外傷、神經壓迫或急性發炎不適用。',
    dosage: '試驗介入為 6 週的教育與自我管理、拇指護具、手部運動，加上 1% 雙氯芬酸鈉凝膠；運動依原文 eAppendix 的活動、等長與功能練習執行。這是試驗的組合介入，不是本頁用藥建議；藥物是否適用應由醫師或藥師確認。',
    cue: '拇指根部維持穩定，不用大力捏夾或拉到關節終點。',
    regression: '先做前臂支撐下的小幅位置重現與輕碰對指，減少捏握。',
    signals: MUSCULOSKELETAL_SIGNALS,
    evidence: '204 人隨機臨床試驗；多模式組合在手功能有小至中等效果，但疼痛沒有主要組間差異，運動相關短暫疼痛較常見。Supplement 2 含運動附錄與護具圖。',
    audience: '適用於 40 歲以上、經診斷的拇指基底關節退化；護具、藥物與運動需依個別禁忌決定。',
    sources: [{ label: 'Deveza et al. Efficacy of a Combination of Conservative Therapies vs an Education Comparator on Clinical Outcomes in Thumb Base Osteoarthritis: RCT. JAMA Intern Med. 2021.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7941246/' }],
  },
  {
    id: 'walkback-low-back-rct',
    kind: 'condition',
    selectionLabel: '下背痛復發預防',
    bodyRegion: '脊椎與軀幹',
    searchAliases: ['下背痛復發', '腰痛預防', '走路運動', 'WalkBack', '反覆腰痛'],
    theme: 'violet',
    eyebrow: '2024 WalkBack 隨機對照試驗',
    title: '下背痛緩解後：個別漸進走路＋教育',
    summary: '大型試驗顯示，6 個月個別化走路與教育方案可延後限制活動型下背痛復發；不是症狀正急遽惡化時硬走固定步數。',
    images: [trialImage('walkback-low-back-rct', '下背痛復發預防的平地走路、計時步行、緩坡走路與運動紀錄四格示意', '由可耐受時間開始，逐步增加頻率、時間與步行強度')],
    suitableFor: '最近一次非特異性下背痛已緩解、過去 6 個月有活動受限發作且可安全步行的成人。',
    dosage: '6 個月內最多 6 次物理治療師面訪，個別設定走路頻率、時間與強度，逐步朝每週約 5 次、每次約 30 分鐘前進，並搭配復發自我管理教育。',
    cue: '一次只增加一個變項；先能規律完成，再增加時間、速度或坡度。',
    regression: '改成短時間、平地、多次分段走路，保留可恢復的步行量。',
    signals: MUSCULOSKELETAL_SIGNALS,
    evidence: '701 人、追蹤最長 3 年的 RCT；走路＋教育組的活動受限型下背痛復發較晚。方案由治療師個別進階；結果不適用於特異性脊椎病變或有馬尾症候群警訊者。',
    audience: '適用於非特異性下背痛緩解後的復發預防，不是急性神經壓迫的治療。',
    sources: [{ label: 'Pocovi et al. WalkBack trial. Lancet. 2024.', href: 'https://pubmed.ncbi.nlm.nih.gov/38908392/' }],
  },
  {
    id: 'low-back-yoga-pt-rct',
    kind: 'condition',
    selectionLabel: '慢性非特異性下背痛',
    bodyRegion: '脊椎與軀幹',
    searchAliases: ['慢性腰痛', '瑜珈', '物理治療', '下背痛', '非特異性腰痛'],
    theme: 'blue',
    eyebrow: '2017 隨機非劣性試驗',
    title: '慢性下背痛：瑜珈、物理治療與教育比較',
    summary: '12 週結構化瑜珈在功能上不劣於物理治療，兩者都優於只給教育資料的部分結果；瑜珈須使用為下背痛設計的標準化課程。',
    images: [trialImage('low-back-yoga-pt-rct', '慢性下背痛的呼吸調整、橋式、四足跪姿與溫和站姿四格示意', '以呼吸與控制為核心，姿勢可使用支撐與降階')],
    suitableFor: '持續至少 12 週的非特異性下背痛成人；神經根壓迫、脊椎骨折、感染、癌症或孕期需另行評估。',
    dosage: '瑜珈組每週一次 75 分鐘團體課、共 12 週並居家練習；物理治療組共 15 次個別治療並居家練習。課程手冊提供姿勢、呼吸與降階。',
    cue: '姿勢不是越深越好；保持呼吸、控制與可恢復的症狀反應。',
    regression: '使用椅子、牆面或墊高支撐，縮短維持時間並減少脊椎活動範圍。',
    signals: MUSCULOSKELETAL_SIGNALS,
    evidence: '320 人 RCT；瑜珈對功能與疼痛不劣於物理治療，且兩種主動介入部分結果優於教育。研究位於安全網醫療體系並使用專門手冊，不代表一般瑜珈課都等效。',
    audience: '適用於已排除特異性病因的慢性下背痛成人；需選擇可調整且了解疼痛族群的課程。',
    sources: [{ label: 'Saper et al. Yoga, physical therapy, or education for chronic low back pain. Ann Intern Med. 2017.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6392183/' }],
  },
  {
    id: 'low-back-pilates-rct',
    kind: 'condition',
    selectionLabel: '慢性非特異性下背痛',
    bodyRegion: '脊椎與軀幹',
    searchAliases: ['皮拉提斯', 'Pilates', '慢性腰痛', '核心訓練', '居家運動'],
    theme: 'green',
    eyebrow: '2024 隨機對照試驗',
    title: '慢性下背痛：監督式皮拉提斯與居家運動比較',
    summary: '6 週皮拉提斯在短期疼痛與障礙較佳，但差異未達臨床重要程度；6 個月時疼痛與障礙已無明顯組間差異。',
    images: [trialImage('low-back-pilates-rct', '慢性下背痛皮拉提斯的呼吸核心控制、橋式、側躺抬腿與四足跪姿四格示意', '由基礎穩定進到節段活動與動態控制')],
    suitableFor: '18–50 歲、非特異性下背痛至少 12 週且無神經根症狀或脊椎手術史者。',
    dosage: '每週 2 次、每次 50 分鐘、共 6 週；每堂 7–10 個動作，每動作 2 組×8–12 下，依基礎、中階、高階調整。原文 Table 1 與 Supplementary Table S4 有進階細節。',
    cue: '先維持呼吸與軀幹控制，再增加槓桿、活動範圍或不穩定度。',
    regression: '縮短槓桿、雙腳支撐，從 8 下開始並增加休息。',
    signals: MUSCULOSKELETAL_SIGNALS,
    evidence: '145 人 RCT；皮拉提斯短期統計差異未達疼痛與障礙的臨床重要界線，6 個月僅生活品質仍較佳。原文有動作階段與補充表；介入由認證治療師監督。',
    audience: '適用於已排除特異性病因的慢性下背痛成人；不是所有皮拉提斯課程的通用效果。',
    sources: [{ label: 'Effectiveness of Pilates compared with home-based exercises in chronic low back pain: RCT. 2024.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11528976/' }],
  },
  {
    id: 'osteoporosis-liftmor-rct',
    kind: 'condition',
    selectionLabel: '低骨量／骨質疏鬆',
    bodyRegion: '全身與神經',
    searchAliases: ['骨質疏鬆', '低骨量', '重訓', 'LIFTMOR', '骨密度'],
    theme: 'orange',
    eyebrow: '2018 LIFTMOR 隨機對照試驗',
    title: '低骨量女性：高強度阻力與衝擊訓練',
    summary: '在嚴格一對一監督與技術篩選下，每週兩次高強度訓練改善骨密度與功能；這不是拿到圖後自行做大重量硬舉的依據。',
    images: [trialImage('osteoporosis-liftmor-rct', '低骨量女性在專業監督下做深蹲、硬舉、過頭推舉與低高度落地四格示意', '高強度動作需先學技術並由合格人員逐步加重')],
    suitableFor: '停經後、低骨量且通過醫療與動作篩選，可在專業人員一對一監督下訓練的女性。',
    dosage: '8 個月、每週 2 次、每次約 30 分鐘；主要阻力動作以 5 組×5 下、強度超過 85% 1RM，並含衝擊落地。研究先進行熟悉與逐步加重，全程高度監督。',
    cue: '脊椎與髖部負荷技術先達標，重量由教練依當日表現調整。',
    regression: '先以髖折、箱式深蹲、牆面推與低負荷阻力學習動作，不做衝擊。',
    signals: MUSCULOSKELETAL_SIGNALS,
    evidence: '101 名停經後低骨量女性 RCT；高強度組在腰椎與股骨頸骨密度及功能有較佳變化，嚴重不良事件少。關鍵限制是高度監督與篩選，不能直接外推到有急性椎體骨折或未受訓練者。',
    audience: '僅適合經醫療風險評估並有合格運動專業人員監督者。',
    sources: [{ label: 'Watson et al. LIFTMOR trial. J Bone Miner Res. 2018.', href: 'https://pubmed.ncbi.nlm.nih.gov/28975661/' }],
  },
  {
    id: 'vertebral-fracture-home-rct',
    kind: 'condition',
    selectionLabel: '骨鬆性椎體骨折',
    bodyRegion: '脊椎與軀幹',
    searchAliases: ['椎體骨折', '壓迫性骨折', '骨鬆骨折', '駝背', '居家復健'],
    theme: 'teal',
    eyebrow: '2020 試辦隨機對照試驗',
    title: '椎體骨折後：居家肌力、平衡與姿勢方案',
    summary: '試辦研究證明由物理治療師個別教導的居家方案可執行，但樣本與追蹤不足以確認明確臨床效果，應視為可行性證據。',
    images: [trialImage('vertebral-fracture-home-rct', '椎體骨折後的椅子坐站、彈力帶划船、扶穩提踵與串聯站立四格示意', '以脊椎安全姿勢練下肢力量、背肌耐力與平衡')],
    suitableFor: '影像確認過骨鬆性椎體骨折、病況穩定且經醫師允許運動的高齡成人。',
    dosage: '12 個月個別居家方案，由物理治療師在家訪中教導背伸肌、下肢肌力、平衡與姿勢，依功能逐步增加；不是固定四個動作。',
    cue: '保持軀幹延伸與髖部發力，避免未經評估的負重脊椎彎曲或扭轉。',
    regression: '以高椅坐站、坐姿划船與雙手扶穩平衡開始，縮短維持。',
    signals: NEURO_BALANCE_SIGNALS,
    evidence: '試辦 RCT 評估 12 個月居家物理治療方案的可行性與安全，未能提供確定療效結論。原文描述訓練構成；小樣本、招募與依從性限制必須保留。',
    audience: '適用於病況穩定且有專業人員個別教學的骨鬆性椎體骨折患者。',
    sources: [{ label: 'Home exercise for people with vertebral fractures: pilot RCT. Phys Ther. 2020.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7439228/' }],
  },
  {
    id: 'pfp-hip-quadriceps-rct',
    kind: 'condition',
    selectionLabel: '女性髕股疼痛',
    bodyRegion: '髖膝與大腿',
    searchAliases: ['髕骨痛', '前膝痛', '跑者膝', '上下樓膝痛', '髖肌訓練'],
    theme: 'violet',
    eyebrow: '2018 隨機對照試驗',
    title: '髕股疼痛：髖肌、股四頭肌與伸展比較',
    summary: '8 週三種主動方案都改善疼痛與功能；髖肌訓練沒有全面優於股四頭肌或伸展，應依個別缺損選擇。',
    images: [trialImage('pfp-hip-quadriceps-rct', '髕股疼痛的側躺髖外展、橋式、坐姿膝伸與小幅深蹲四格示意', '髖部與膝部方案都可漸進，依疼痛與控制選擇')],
    suitableFor: '活動相關前膝痛、臨床符合髕股疼痛的女性；急性創傷、明顯腫脹鎖住或髕骨脫臼需另行處理。',
    dosage: '8 週分組訓練；髖肌與股四頭肌組以漸進阻力練習，另有伸展比較組。依原文動作圖與治療師指示逐週增加阻力。',
    cue: '膝與足方向保持可控制，選擇隔天不惡化的活動範圍。',
    regression: '由短槓桿側躺髖外展、橋式或高椅坐站開始，縮小蹲的深度。',
    signals: MUSCULOSKELETAL_SIGNALS,
    evidence: '40 名女性 RCT；三個運動組疼痛與功能均改善，髖肌組並未在所有結果優於其他組。原文有運動圖；樣本小、只有女性且缺少長期追蹤。',
    audience: '適用於經評估的髕股疼痛女性；不應用單一「膝蓋不能內扣」規則取代個別評估。',
    sources: [{ label: 'Hip, quadriceps, or stretching exercises for patellofemoral pain in women: RCT. 2018.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6157473/' }],
  },
  {
    id: 'chronic-ankle-balance-strength-rct',
    kind: 'condition',
    selectionLabel: '慢性踝關節不穩',
    bodyRegion: '足踝',
    searchAliases: ['反覆腳踝扭傷', '腳踝不穩', '軟腳', 'CAI', '平衡訓練'],
    theme: 'blue',
    eyebrow: '2018 隨機對照試驗',
    title: '慢性踝不穩：平衡訓練與阻力訓練比較',
    summary: '6 週平衡與阻力方案都改善部分功能與力量；平衡組在動態平衡有較一致改善，兩者不是互相排斥。',
    images: [trialImage('chronic-ankle-balance-strength-rct', '慢性踝不穩的單腳站、星狀觸地、彈力帶外翻與提踵四格示意', '先有穩固支撐，再進到多方向平衡與踝部阻力')],
    suitableFor: '反覆踝扭傷、主觀軟腳且符合慢性踝關節不穩標準的年輕成人。',
    dosage: '每週 3 次、每次約 20 分鐘、共 6 週；平衡組逐步增加方向、距離與擾動，阻力組以彈力帶做踝四向等漸進訓練。',
    cue: '足弓與膝髖維持控制，碰到支撐或品質下降就結束該組。',
    regression: '雙手扶穩的雙腳提踵、雙腳站或縮短單腳維持時間。',
    signals: MUSCULOSKELETAL_SIGNALS,
    evidence: '39 人 RCT；平衡與阻力組均改善，平衡組動態平衡結果較一致。原文含完整方案；限制為小樣本、年輕族群與 6 週短期結果。',
    audience: '適用於非急性、已排除骨折與明顯機械性不穩的慢性踝不穩成人。',
    sources: [{ label: 'Hall et al. Balance- and strength-training protocols for chronic ankle instability: RCT. J Athl Train. 2018.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6089027/' }],
  },
  {
    id: 'chronic-ankle-hop-stabilization-rct',
    kind: 'condition',
    selectionLabel: '慢性踝不穩回跑跳',
    bodyRegion: '足踝',
    searchAliases: ['腳踝跳躍', '落地不穩', '反覆扭傷', 'hop stabilization', '回運動'],
    theme: 'green',
    eyebrow: '2019 隨機對照試驗',
    title: '慢性踝不穩：6 週跳躍穩定訓練',
    summary: '18 次漸進跳躍與定住落地可改善自評功能與部分落地生物力學；研究只納入 28 名男性，不能直接外推到所有族群。',
    images: [trialImage('chronic-ankle-hop-stabilization-rct', '慢性踝不穩的雙腳小跳定住、前後跳、側向跳與單腳落地四格示意', '由雙腳低幅定住開始，再增加方向與單腳落地')],
    suitableFor: '已可無痛完成基礎單腳平衡、準備回到跑跳的慢性踝不穩成人。',
    dosage: '6 週共 18 次訓練，依原文由雙腳到單腳、單方向到多方向、低幅到較高需求跳躍；每次都以穩定落地品質決定進階。',
    cue: '落地後定住，膝髖共同吸收；不能穩定就降低距離或改雙腳。',
    regression: '先做跨步定住、雙腳踮腳落回或扶穩的小幅跳，不急著單腳。',
    signals: MUSCULOSKELETAL_SIGNALS,
    evidence: '28 名男性 RCT；跳躍穩定組改善自評功能與部分落地指標。原文列出跳躍進階；樣本小、僅男性且屬後期運動，不適用於急性扭傷。',
    audience: '適用於已通過基礎肌力與平衡門檻的慢性踝不穩者。',
    sources: [{ label: 'Hop-stabilization training and chronic ankle instability: RCT. J Athl Train. 2019.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6922560/' }],
  },
  {
    id: 'hamstring-early-lengthening-rct',
    kind: 'condition',
    selectionLabel: '急性腿後肌拉傷',
    bodyRegion: '髖膝與大腿',
    searchAliases: ['腿後肌拉傷', '大腿後側痛', 'hamstring', '跑步拉傷', '長肌長訓練'],
    theme: 'orange',
    eyebrow: '2022 隨機對照試驗',
    title: '腿後肌拉傷：早期與延後長肌長運動比較',
    summary: '受傷後立即或等能無痛走路才開始長肌長運動，回場與再傷沒有明顯差異；研究支持依標準漸進，而不是認定越早越好。',
    images: [trialImage('hamstring-early-lengthening-rct', '腿後肌拉傷的橋式、滑腳跟、髖鉸鏈與漸進跑步四格示意', '先低負荷收縮，再依標準增加肌肉長度與跑步速度')],
    suitableFor: '急性腿後肌拉傷、已排除完全撕裂或近端撕脫，且由運動醫療團隊追蹤的成人。',
    dosage: '兩組使用相同標準化復健，差別在長肌長運動從第 1 天開始或延後到能無痛走路；依疼痛、力量與跑步標準進階，完整動作在原文補充資料。',
    cue: '一次只增加肌肉長度、阻力或速度其中一項。',
    regression: '短槓桿雙腳橋式或低強度等長腳跟壓地，暫停滑動與跑步。',
    signals: MUSCULOSKELETAL_SIGNALS,
    evidence: '90 名運動員 RCT；早期組回場中位數較短，但調整分析的回場時間與再傷未見顯著組間差異。原文有階段與補充方案；不能把結果外推到肌腱撕脫。',
    audience: '適用於經診斷的肌肉型腿後肌拉傷運動員。',
    sources: [{ label: 'Early versus delayed lengthening exercises for acute hamstring injury: RCT. Br J Sports Med. 2022.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9252858/' }],
  },
  {
    id: 'plantar-fasciopathy-exercise-rct',
    kind: 'condition',
    selectionLabel: '足底筋膜病變',
    bodyRegion: '足踝',
    searchAliases: ['足底筋膜炎', '腳跟痛', '晨起第一步痛', '足弓痛', '提踵'],
    theme: 'teal',
    eyebrow: '2024 隨機對照試驗',
    title: '足底筋膜病變：鞋墊與建議之外加運動？',
    summary: '200 人試驗顯示，在建議與客製鞋墊之外加入標準化運動，6 個月沒有額外改善；代表需要個別化，而不是運動一定無效。',
    images: [trialImage('plantar-fasciopathy-exercise-rct', '足底筋膜病變的足趾活動、坐姿提踵、站姿提踵與單腳提踵四格示意', '由低負荷足部控制逐步進到提踵負荷')],
    suitableFor: '臨床確認足底筋膜病變、可安全承重的成人；近期骨折、神經症狀或全身性發炎疾病需先排除。',
    dosage: '研究使用標準化漸進運動並搭配建議與客製鞋墊，依能力從低負荷足部動作進到較高負荷提踵；原文與附錄提供方案。',
    cue: '提踵時保持足趾與足弓控制，負荷增加後隔天第一步痛不應持續升高。',
    regression: '坐姿提踵、雙腳扶穩提踵或減少負重幅度。',
    signals: MUSCULOSKELETAL_SIGNALS,
    evidence: '200 人四組 RCT；在建議＋客製鞋墊基礎上加入運動，6 個月主要結果沒有額外優勢。研究設計完整且呈現陰性結果；不能解讀為所有形式運動都無效。',
    audience: '適用於非急性足底筋膜病變，並需依工作、體重承載與鞋具個別調整。',
    sources: [{ label: 'Exercise, advice and custom orthoses for plantar heel pain: RCT. 2024.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11347971/' }],
  },
  {
    id: 'tka-high-intensity-rct',
    kind: 'condition',
    selectionLabel: '人工膝關節置換術後',
    bodyRegion: '髖膝與大腿',
    searchAliases: ['TKA 術後', '人工膝關節', '膝關節置換', '術後肌力', '高強度復健'],
    theme: 'violet',
    eyebrow: '2017 隨機對照試驗',
    title: '人工膝術後：早期高強度與低強度復健比較',
    summary: '術後第 4 天開始的高強度漸進方案安全，但 3 與 12 個月未優於低強度方案；早期股四頭肌抑制可能限制實際強度。',
    images: [trialImage('tka-high-intensity-rct', '人工膝關節術後的坐站、低台階、腿推與腳踏車四格示意', '由活動與坐站開始，再依腫脹、力量與控制增加負荷')],
    suitableFor: '單側初次人工膝關節置換、手術後病況穩定並由術後團隊允許進階者。',
    dosage: '兩組皆在術後早期開始門診訓練；高強度組更快增加阻力、承重與功能動作。實際組次與重量依疼痛、腫脹、活動度與股四頭肌控制調整。',
    cue: '高強度的前提是膝關節反應穩定與動作品質，不以硬撐重量定義。',
    regression: '高椅坐站、短弧膝伸與低阻力腳踏車，先處理腫脹與伸直控制。',
    signals: POSTOPERATIVE_SIGNALS,
    evidence: '162 人 RCT；高強度與低強度組在 3、12 個月主要結果沒有差異，兩組均改善。高強度未增加重大不良事件，但可能受術後肌肉活化不足限制。',
    audience: '適用於手術與復健團隊監督下的初次人工膝術後患者。',
    sources: [{ label: 'Bade et al. Early high- versus low-intensity rehabilitation after total knee arthroplasty: RCT. 2017.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5415445/' }],
  },
  {
    id: 'tka-trio-targeted-rct',
    kind: 'condition',
    selectionLabel: '人工膝術後恢復較慢',
    bodyRegion: '髖膝與大腿',
    searchAliases: ['人工膝關節恢復慢', 'TKA 術後', 'TRIO', '膝術後復健', '膝無力'],
    theme: 'blue',
    eyebrow: '2020 TRIO 隨機對照試驗',
    title: '人工膝術後恢復較慢：目標式門診復健',
    summary: '針對術後早期功能較差者加上治療師帶領的漸進功能訓練，沒有比單次評估加居家方案帶來重要長期優勢；更多治療不一定等於更好。',
    images: [trialImage('tka-trio-targeted-rct', '人工膝術後的坐站、台階、扶穩單腳承重與漸進走路四格示意', '依功能缺損練坐站、台階、承重與步行')],
    suitableFor: '人工膝關節置換後約 6 週、牛津膝評分顯示恢復較差且傷口與醫療狀況穩定的成人。',
    dosage: '兩組都在 6 週內完成 18 次運動。介入組其中 6 次為每週一對一門診物理治療，由治療師逐週調整目標式肌力、平衡與功能訓練，另做 12 次居家練習；比較組在一次物理治療評估後，完成 18 次沒有治療師逐週進階的居家練習。',
    cue: '以最影響日常功能的缺損設定一至兩個可量化目標，再調整負荷。',
    regression: '高椅坐站、較低台階、雙手扶穩承重與短距離分段走路。',
    signals: POSTOPERATIVE_SIGNALS,
    evidence: '334 人多中心 RCT，專門納入術後早期恢復較差者；同為 6 週 18 次運動，含 6 次治療師逐週進階的門診方案，沒有比一次評估後的居家方案改善 12 個月主要結果。平均結果不能取代個別仍有可修正缺損者的臨床判斷。',
    audience: '適用於術後團隊重新評估恢復較慢原因後的成人；感染、鬆動或血栓疑慮要先排除。',
    sources: [{ label: 'Hamilton et al. Targeting Rehabilitation to Improve Outcomes After Total Knee Arthroplasty in Patients at Risk of Poor Outcomes: RCT. BMJ. 2020.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7551789/' }],
  },
  {
    id: 'hip-oa-hip-booster-rct',
    kind: 'condition',
    selectionLabel: '髖骨關節炎',
    bodyRegion: '髖膝與大腿',
    searchAliases: ['髖關節退化', '髖骨關節炎', '鼠蹊痛', 'Hip Booster', 'NEMEX'],
    theme: 'green',
    eyebrow: '2024 Hip Booster 隨機試驗',
    title: '髖關節炎：高強度阻力與神經肌肉運動比較',
    summary: '12 週高強度阻力與神經肌肉訓練，在坐站、疼痛與生活品質改善相近；沒有證據支持其中一種全面較優。',
    images: [trialImage('hip-oa-hip-booster-rct', '髖骨關節炎的腿推、髖伸、坐站與階梯控制四格示意', '阻力與神經肌肉訓練皆需依能力進階')],
    suitableFor: '臨床診斷髖骨關節炎、可參與團體運動且沒有近期手術或重大運動禁忌的成人。',
    dosage: '兩組皆 12 週、每週 2 次、每次 60 分鐘監督式團體課。阻力組做 5 個髖膝高強度動作；NEMEX 組做 10 個感覺動作控制與功能穩定練習。',
    cue: '阻力組重視可重複的高品質負荷；神經肌肉組重視軀幹、髖膝足排列與控制。',
    regression: '減少阻力與活動深度，使用較高座椅、扶手或雙腳支撐。',
    signals: MUSCULOSKELETAL_SIGNALS,
    evidence: '160 人、多中心群集 RCT；兩組 30 秒坐站都平均增加 1.5 次，疼痛與髖部生活品質無重要組間差異。研究為優越性試驗，結論是阻力訓練未優於 NEMEX。',
    audience: '適用於可安全運動的症狀性髖關節炎成人；可依偏好、設備與缺損選擇方案。',
    sources: [{ label: 'Kjeldsen et al. Progressive resistance training or neuromuscular exercise for hip OA: cluster RCT. Ann Intern Med. 2024.', href: 'https://pubmed.ncbi.nlm.nih.gov/38588540/' }],
  },
  {
    id: 'axspa-high-intensity-rct',
    kind: 'condition',
    selectionLabel: '軸性脊椎關節炎',
    bodyRegion: '脊椎與軀幹',
    searchAliases: ['僵直性脊椎炎', '軸性脊椎炎', 'axSpA', '脊椎僵硬', '高強度運動'],
    theme: 'orange',
    eyebrow: '2020 隨機對照試驗',
    title: '軸性脊椎關節炎：高強度有氧＋肌力',
    summary: '12 週監督式高強度有氧與肌力改善疾病活動、功能與心肺適能；研究是醫療篩選後的漸進課程，不是發炎急遽惡化時硬撐。',
    images: [trialImage('axspa-high-intensity-rct', '軸性脊椎關節炎的腳踏車、深蹲、划船與髖伸展四格示意', '有氧間歇搭配全身肌力與脊椎活動')],
    suitableFor: '病況穩定、經風濕科與運動風險評估的軸性脊椎關節炎成人。',
    dosage: '12 週監督式高強度課程，每週包含心肺間歇與主要肌群阻力訓練；強度以個別最大心率與可重複負荷設定，並逐週進階。',
    cue: '在可維持動作品質與恢復的前提下提高強度，發炎波動時調整總量。',
    regression: '改中等強度腳踏車或走路、較輕阻力與支撐式活動度練習。',
    signals: CARDIOPULMONARY_SIGNALS,
    evidence: '100 人 RCT；高強度運動組在 ASDAS、BASDAI、功能與心肺結果優於一般照護。方案由專業人員監督；樣本數有限，嚴重心血管疾病與無法安全高強度運動者不在適用範圍。',
    audience: '適用於風濕科病況穩定且通過心血管風險評估者。',
    sources: [{ label: 'Sveaas et al. High intensity exercise for axial spondyloarthritis: RCT. Br J Sports Med. 2020.', href: 'https://pubmed.ncbi.nlm.nih.gov/30745314/' }],
  },
  {
    id: 'fibromyalgia-functional-rct',
    kind: 'condition',
    selectionLabel: '纖維肌痛',
    bodyRegion: '全身與神經',
    searchAliases: ['纖維肌痛症', '全身痛', '慢性廣泛疼痛', 'functional exercise', '功能訓練'],
    theme: 'teal',
    eyebrow: '2024 隨機對照試驗',
    title: '纖維肌痛：功能性運動與伸展比較',
    summary: '14 週功能性運動比相同頻率伸展更能降低廣泛疼痛並改善部分生活品質；力量、平衡與功能測驗未見組間差異。',
    images: [trialImage('fibromyalgia-functional-rct', '纖維肌痛的坐站、彈力帶划船、橋式與低台階四格示意', '以全身日常動作循環訓練，依症狀調整')],
    suitableFor: '診斷纖維肌痛、病況穩定且可參與團體功能訓練的成年女性；研究未納入男性。',
    dosage: '每週 2 次、每次 45 分鐘、共 14 週；功能組以 14 個全身動作循環練習，常用 2 組×10 下並依能力調整；比較組做同時長伸展。',
    cue: '以可恢復的努力程度累積一致性，不用單次高量測試極限。',
    regression: '減少循環站數、以坐姿或支撐版本完成，動作間增加休息。',
    signals: CARDIOPULMONARY_SIGNALS,
    evidence: '82 名女性 RCT；功能運動組在廣泛疼痛、纖維肌痛影響與部分生活品質優於伸展，但功能、力量、柔軟度和平衡無組間差異。原文 Figure 1 呈現動作；僅女性且追蹤短。',
    audience: '適用於穩定纖維肌痛成年女性；需依睡眠、疲勞與症狀波動調整。',
    sources: [{ label: 'Fernandes et al. Functional exercise for fibromyalgia: RCT. Adv Rheumatol. 2024.', href: 'https://pubmed.ncbi.nlm.nih.gov/39449056/' }],
  },
  {
    id: 'vivifrail-multicomponent-rct',
    kind: 'condition',
    selectionLabel: '高齡衰弱合併輕度認知障礙',
    bodyRegion: '全身與神經',
    searchAliases: ['衰弱', '肌少症', '認知障礙', 'Vivifrail', '高齡運動'],
    theme: 'violet',
    eyebrow: '2022 Vivifrail 隨機對照試驗',
    title: '高齡認知障礙：個別化多成分運動',
    summary: '依短體能量表分級的 Vivifrail 多成分方案，改善輕度認知障礙或輕度失智高齡者的功能能力；需要照顧者與跌倒風險管理。',
    images: [trialImage('vivifrail-multicomponent-rct', '高齡者的椅子坐站、扶穩串聯走、提踵與陪同走路四格示意', '依體能分級安排肌力、平衡與步行')],
    suitableFor: '75 歲以上、輕度認知障礙或輕度失智，且能在監督或照顧者協助下運動的高齡者。',
    dosage: '依 SPPB 表現選擇 Vivifrail 級別，居家執行肌力、平衡、柔軟與步行的多成分方案，持續約 3 個月；難度與安全支撐隨功能調整。',
    cue: '環境先清空、支撐先就位，再做坐站、平衡或走路。',
    regression: '改坐姿或雙手扶穩，降低負重、距離與雙重任務。',
    signals: NEURO_BALANCE_SIGNALS,
    evidence: '188 名高齡者 RCT；個別化 Vivifrail 方案改善功能能力。原文與 Vivifrail 手冊有分級動作圖；結果依賴監督、認知與照顧環境，不能只交付圖片。',
    audience: '適用於有照顧者或專業人員協助的輕度認知障礙／失智高齡者。',
    sources: [{ label: 'Vivifrail multicomponent exercise in older adults with cognitive impairment: RCT. 2022.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8977963/' }],
  },
  {
    id: 'react-older-adults-rct',
    kind: 'condition',
    selectionLabel: '高齡者行動功能下降',
    bodyRegion: '全身與神經',
    searchAliases: ['高齡體能', '行動力', '平衡訓練', 'REACT', '衰弱預防'],
    theme: 'blue',
    eyebrow: '2022 REACT 隨機對照試驗',
    title: '行動力下降高齡者：一年社區運動方案',
    summary: '結合團體運動與行為維持的一年 REACT 計畫，在 24 個月仍保有較佳下肢功能；持續參與與社區支持是介入的一部分。',
    images: [trialImage('react-older-adults-rct', '社區高齡者的坐站、扶椅髖外展、低台階與小組快走四格示意', '團體練肌力、平衡與有氧，並建立持續活動習慣')],
    suitableFor: '65 歲以上、SPPB 顯示下肢功能已有下降但仍可參加社區團體課程的成人。',
    dosage: '12 個月團體方案，前期較密集、後期降低頻率並強化自我維持；課堂包含有氧、下肢肌力、平衡與活動行為策略。',
    cue: '選能持續一年的難度與環境，規律性比單次高強度更重要。',
    regression: '使用扶手、較高椅面、低台階與較短走路回合。',
    signals: NEURO_BALANCE_SIGNALS,
    evidence: '777 人、多中心 RCT；REACT 組在 24 個月 SPPB 維持較佳，且有健康經濟分析。介入是完整社區與行為維持方案，不能歸因於單一坐站或步行動作。',
    audience: '適用於可參與監督式社區運動的行動功能下降高齡者。',
    sources: [{ label: 'Stathi et al. REACT physical activity and behaviour maintenance programme: multicentre RCT. Lancet Public Health. 2022.', href: 'https://pubmed.ncbi.nlm.nih.gov/35114106/' }],
  },
  {
    id: 'praised-dementia-rct',
    kind: 'condition',
    selectionLabel: '失智症／輕度認知障礙',
    bodyRegion: '全身與神經',
    searchAliases: ['失智復健', '輕度認知障礙', 'PrAISED', '居家運動', '跌倒預防'],
    theme: 'green',
    eyebrow: '2023 PrAISED 隨機對照試驗',
    title: '失智居家復健：運動、日常活動與跌倒預防',
    summary: '高度個別化、最長一年且多次到宅的 PrAISED 方案，沒有改善主要日常活動結果；這個重要陰性試驗提醒介入負擔與可持續性。',
    images: [trialImage('praised-dementia-rct', '失智高齡者在照顧者陪同下做坐站、串聯站、拿取物品與戶外走路四格示意', '把肌力、平衡與日常任務放進熟悉環境')],
    suitableFor: '能在家中接受治療、由照顧者或家人協助的輕度失智或輕度認知障礙成人。',
    dosage: '最長 12 個月、最多約 50 次治療師到宅或聯繫，將肌力、平衡、功能活動與跌倒預防個別化並納入日常。',
    cue: '使用熟悉任務、固定提示與照顧者協助，先確保安全與可理解性。',
    regression: '單一步驟、坐姿或雙手扶穩，取消複雜雙重任務並縮短時間。',
    signals: NEURO_BALANCE_SIGNALS,
    evidence: '365 人、多中心 RCT；即使提供高劑量個別化介入，主要日常活動、體能與生活品質未見重要改善。原文完整描述介入；陰性結果不代表活動無價值，而是該服務模式未證實額外療效。',
    audience: '適用於照顧團隊共同設定安全活動目標；不應宣稱可延緩失智進程。',
    sources: [{ label: 'Goldberg et al. PrAISED intervention for dementia or mild cognitive impairment: RCT. BMJ. 2023.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10463053/' }],
  },
  {
    id: 'parkinson-abc-c-rct',
    kind: 'condition',
    selectionLabel: '巴金森病步態與平衡',
    bodyRegion: '全身與神經',
    searchAliases: ['巴金森', 'Parkinson', '凍結步態', '平衡', 'ABC-C'],
    theme: 'orange',
    eyebrow: '2020 ABC-C 隨機對照試驗',
    title: '巴金森病：敏捷訓練加入認知挑戰',
    summary: '6 週高頻敏捷與雙重任務訓練，改善部分移動與平衡結果；需要防跌環境與熟悉巴金森病的治療師監督。',
    images: [trialImage('parkinson-abc-c-rct', '巴金森病的多方向跨步、跨越低障礙、持球雙重任務走路與轉身四格示意', '把大幅跨步、障礙與認知任務逐步組合')],
    suitableFor: '藥物穩定、可在監督下站走且沒有不穩定心血管疾病的巴金森病成人。',
    dosage: '6 週、每週 3 次、每次約 80–90 分鐘；包含大幅與快速動作、多方向步伐、障礙、感覺動作敏捷與逐步增加的認知雙重任務。',
    cue: '先在單一任務下走穩，再加入轉向、障礙或認知任務。',
    regression: '扶穩原地跨步、較寬通道與單一任務，取消同時說話或持物。',
    signals: NEURO_BALANCE_SIGNALS,
    evidence: '86 人隨機交叉設計試驗；ABC-C 改善部分步態、平衡與認知移動指標。原文含課程架構；介入時間長、監督密集，不能以無監督障礙訓練替代。',
    audience: '適用於專業監督下、可安全站走的巴金森病成人。',
    sources: [{ label: 'Agility Boot Camp with Cognitive Challenge for Parkinson disease: RCT. 2020.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7608677/' }],
  },
  {
    id: 'stroke-virtual-arm-rct',
    kind: 'condition',
    selectionLabel: '腦中風後上肢復健',
    bodyRegion: '全身與神經',
    searchAliases: ['中風手復健', '偏癱上肢', '遠距復健', 'V-ABC', '抓握訓練'],
    theme: 'teal',
    eyebrow: '2025 隨機對照試驗',
    title: '中風後上肢：虛擬手臂密集訓練',
    summary: '穿戴裝置搭配遠距治療師，在家增加大量伸手抓握練習；試驗證明能提高實際動作劑量，臨床功能效果仍需更大研究確認。',
    images: [trialImage('stroke-virtual-arm-rct', '腦中風後的伸手拿杯、抓泡棉塊、桌面毛巾滑動與低架取物四格示意', '以大量可達成的伸手抓握任務累積上肢使用')],
    suitableFor: '中風後仍有可主動伸手抓握能力、能理解遠距指示並有安全居家環境的成人。',
    dosage: '3 週居家密集方案，包含穿戴式裝置提示的伸手抓握活動與 6 次視訊治療；介入組每日平均增加數百次伸手抓握。',
    cue: '軀幹保持可控制，目標物放在能成功完成又稍具挑戰的位置。',
    regression: '縮短距離、使用較大較輕物品、前臂支撐或由照顧者協助擺位。',
    signals: NEURO_BALANCE_SIGNALS,
    evidence: '73 人 RCT；虛擬手臂密集訓練明顯增加每日伸手抓握量。研究主要證明可行性與劑量提升，樣本與追蹤不足以確認長期功能優勢。',
    audience: '適用於中風復健團隊評估後的居家上肢練習；肩痛、半側忽略或認知障礙需額外調整。',
    sources: [{ label: 'Virtual Arm Boot Camp after stroke: randomized trial. 2025.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11921204/' }],
  },
  {
    id: 'ms-pilates-rct',
    kind: 'condition',
    selectionLabel: '多發性硬化症行走功能',
    bodyRegion: '全身與神經',
    searchAliases: ['多發性硬化症', 'MS', '皮拉提斯', '走路耐力', '平衡'],
    theme: 'violet',
    eyebrow: '2018 隨機對照試驗',
    title: '多發性硬化症：12 週個別化皮拉提斯',
    summary: '每週兩次團體皮拉提斯改善 6 分鐘走路與部分起身行走表現；只有 30 人，且沒有與等量主動運動比較。',
    images: [trialImage('ms-pilates-rct', '多發性硬化症的橋式、側躺蚌殼、坐姿軀幹控制與扶穩站姿平衡四格示意', '以呼吸、排列與核心控制支持走路功能')],
    suitableFor: '確診多發性硬化症、未完全依賴輪椅或電動代步且可前往團體課程的成人。',
    dosage: '12 週、每週 2 次、每次 50 分鐘，5–10 人小組；含站姿器械與墊上動作，依個別能力調整，另有每週一次按摩作為共同照護的一部分。',
    cue: '注意熱敏感與疲勞，維持呼吸和排列，不追求力竭。',
    regression: '改墊上或坐姿、減少維持與組數，安排降溫和較長休息。',
    signals: NEURO_BALANCE_SIGNALS,
    evidence: '30 人、評估者盲化 RCT；皮拉提斯組 6 分鐘走路平均增加較多，部分 TUG 改善，其餘多數次要結果無差異。課程只描述代表動作，完整 curriculum 需向作者索取；小樣本且對照不是等量運動。',
    audience: '適用於病況穩定且能在專業監督下調整疲勞與平衡風險的多發性硬化症成人。',
    sources: [{ label: 'Duff et al. Impact of Pilates exercise in multiple sclerosis: RCT. 2018.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5898921/' }],
  },
  {
    id: 'concussion-aerobic-rct',
    kind: 'condition',
    selectionLabel: '青少年運動腦震盪',
    bodyRegion: '全身與神經',
    searchAliases: ['腦震盪', '運動腦震盪', '青少年', '次症狀有氧', '腳踏車'],
    theme: 'blue',
    eyebrow: '2019 隨機臨床試驗',
    title: '腦震盪後：個別化次症狀有氧運動',
    summary: '受傷第一週內開始、低於症狀惡化門檻的個別有氧，比安慰性伸展更快恢復；前提是先由運動醫療人員完成測試與排除紅旗。',
    images: [trialImage('concussion-aerobic-rct', '青少年腦震盪後做心率監測腳踏車、跑步機走路、戶外步行與坐姿症狀紀錄四格示意', '依個別症狀門檻控制心率與時間，不做碰撞運動')],
    suitableFor: '13–18 歲、運動相關腦震盪後 10 天內，已完成醫療評估且可接受運動測試者。',
    dosage: '每天最多 20 分鐘有氧，目標心率設在運動測試誘發症狀心率約 80%；症狀增加 2 分或達 20 分鐘即停止。每日重新記錄並由研究團隊調整。',
    cue: '維持在症狀門檻以下；這是有控制的有氧，不是回到球場對抗。',
    regression: '降低心率目標、改平地走路或分段完成，症狀上升即停止。',
    signals: NEURO_BALANCE_SIGNALS,
    evidence: '103 名青少年隨機臨床試驗；次症狀有氧組恢復中位數 13 天，伸展組 17 天。原文清楚定義心率與停止規則；不適用於未排除顱內傷害或頸椎傷害者。',
    audience: '僅適用於醫療評估後的青少年運動腦震盪；回場仍需分階段通過。',
    sources: [{ label: 'Leddy et al. Early subthreshold aerobic exercise for sport-related concussion: RCT. JAMA Pediatr. 2019.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6450274/' }],
  },
  {
    id: 'pad-lite-walking-rct',
    kind: 'condition',
    selectionLabel: '周邊動脈疾病走路受限',
    bodyRegion: '全身與神經',
    searchAliases: ['周邊動脈疾病', '間歇性跛行', '走路小腿痛', 'PAD', 'LITE'],
    theme: 'green',
    eyebrow: '2021 LITE 隨機臨床試驗',
    title: '周邊動脈疾病：高強度與低強度走路比較',
    summary: '居家高強度走路改善 6 分鐘步行，低強度走路沒有優於無運動控制；這裡的高強度有穿戴監測與教練電話支持。',
    images: [trialImage('pad-lite-walking-rct', '周邊動脈疾病的跑步機快走、扶欄休息、重新開始與穿戴裝置紀錄居家走路四格示意', '以走路—休息間歇累積較高強度步行')],
    suitableFor: '確診下肢周邊動脈疾病、可在醫療團隊設定下居家走路的成人。',
    dosage: '12 個月居家走路，目標每週約 5 天、每次累積最多約 50 分鐘；高強度組走到中重度腿部缺血症狀後休息再走，並使用穿戴裝置與教練追蹤。',
    cue: '分辨典型腿部症狀與胸痛、呼吸困難或不尋常疼痛；按團隊規則走停。',
    regression: '降低速度、縮短走路回合並增加休息，但不要自行把醫療監測方案改成完全無症狀散步。',
    signals: CARDIOPULMONARY_SIGNALS,
    evidence: '305 人多中心 RCT；高強度居家走路改善 6 分鐘步行，低強度組未優於無運動控制。介入包含穿戴監測與行為支持，不能只用「走到痛」四字複製。',
    audience: '適用於血管專業評估後的穩定 PAD 成人；急性肢體缺血警訊需立即就醫。',
    sources: [{ label: 'McDermott et al. LITE randomized clinical trial. JAMA. 2021.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8025122/' }],
  },
  {
    id: 'copd-rehab-duration-rct',
    kind: 'condition',
    selectionLabel: '慢性阻塞性肺病',
    bodyRegion: '全身與神經',
    searchAliases: ['COPD', '肺復健', '慢性阻塞性肺病', '呼吸復健', '運動喘'],
    theme: 'orange',
    eyebrow: '2024 PuRe Duration 隨機試驗',
    title: '慢性阻塞性肺病肺復健：8 週與 12 週比較',
    summary: '每週兩次監督式耐力、肌力與自我管理，8 週與 12 週的耐力改善符合等效判定，但資料也無法完全排除 12 週更好。',
    images: [trialImage('copd-rehab-duration-rct', 'COPD 肺復健的腳踏車、坐站、彈力帶划船與低台階四格示意', '耐力與全身肌力搭配呼吸與自我管理')],
    suitableFor: '病況穩定、經肺科或肺復健團隊評估可運動的 COPD 成人。',
    dosage: '8 週或 12 週、每週 2 次監督式肺復健，包含個別化耐力與肌力訓練及自我管理教育；運動強度依基線測試與呼吸反應調整。',
    cue: '使用團隊設定的呼吸困難程度、血氧與恢復規則，不與別人的速度比較。',
    regression: '降低腳踏車阻力或步行速度、分段完成並延長恢復時間。',
    signals: CARDIOPULMONARY_SIGNALS,
    evidence: '66 人等效性 RCT；8 與 12 週在耐力步行改善達到預設等效標準，但信賴區間仍不能排除 12 週較佳。原文清楚描述每週兩次耐力、肌力與教育；樣本小。',
    audience: '適用於專業肺復健場域；近期急性惡化或氧氣需求改變需先評估。',
    sources: [{ label: 'Bishop et al. PuRe Duration Trial. Respirology. 2024.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11688624/' }],
  },
  {
    id: 'lung-cancer-exercise-rct',
    kind: 'condition',
    selectionLabel: '肺癌治療後運動',
    bodyRegion: '全身與神經',
    searchAliases: ['肺癌復健', '癌症運動', '心肺適能', '腳踏車', '阻力訓練'],
    theme: 'teal',
    eyebrow: '2021 隨機對照試驗',
    title: '肺癌存活者：有氧、阻力與組合訓練',
    summary: '16 週有氧與組合訓練改善心肺適能，其中有氧方案完成度較佳；癌症分期、治療副作用與骨轉移風險必須個別篩選。',
    images: [trialImage('lung-cancer-exercise-rct', '肺癌存活者的腳踏車、腿推、坐姿推胸與有氧阻力循環四格示意', '依治療狀況選擇有氧、阻力或組合訓練')],
    suitableFor: '原試驗對象為 21–80 歲、完成所有根治性治療後 1 年至未滿 10 年、ECOG 體能狀態 0–1，且經測試確認心肺適能偏低的肺癌存活者；不能直接外推至治療中患者。',
    dosage: '16 週、每週 3 次監督式運動；分別比較有氧、阻力、組合與伸展注意力控制，強度依個別測試進階。',
    cue: '依呼吸、疲勞、疼痛與個別運動測試結果調整；若病況改變、復發或開始新療程，先由腫瘤團隊重新評估。',
    regression: '短時間低阻力腳踏車、坐姿肌力與較長休息，暫停會誘發骨痛的負荷。',
    signals: CARDIOPULMONARY_SIGNALS,
    evidence: '90 人四組 RCT；有氧與組合訓練改善峰值攝氧量，有氧組可行性與效果較一致。參與者均已完成根治性治療至少 1 年，且需通過心肺運動與最大肌力測試；樣本小且族群經嚴格篩選。',
    audience: '適用於已完成根治性治療、心肺適能偏低且經腫瘤科與運動醫療團隊核可的肺癌存活者；疑似復發、骨轉移、感染或有新療程急性副作用時不自行訓練。',
    sources: [{ label: 'Scott et al. Effects and Tolerability of Exercise Therapy Modality on Cardiorespiratory Fitness in Lung Cancer: RCT. J Cachexia Sarcopenia Muscle. 2021.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8718021/' }],
  },
  {
    id: 'cardio-oncology-core-rct',
    kind: 'condition',
    selectionLabel: '腫瘤心臟復健',
    bodyRegion: '全身與神經',
    searchAliases: ['癌症心臟復健', 'cardio-oncology', '癌症運動', 'CORE', '心肺適能'],
    theme: 'violet',
    eyebrow: '2023 CORE 隨機臨床試驗',
    title: '癌症治療後：心臟復健式有氧＋阻力',
    summary: '8 週結合有氧、阻力與風險因子管理的 CORE 方案改善峰值攝氧量；需要腫瘤心臟與復健團隊監測，不是一般健身課。',
    images: [trialImage('cardio-oncology-core-rct', '癌症存活者做跑步機走路、坐站、彈力帶划船與輕啞鈴推舉四格示意', '以心臟復健架構整合有氧、阻力與監測')],
    suitableFor: '曾接受具心臟毒性的癌症治療和／或已有心血管疾病、屬高心血管風險，且病況穩定並經腫瘤心臟團隊評估的成人癌症存活者。',
    dosage: '8 週、每週 2 次監督式課程，結合個別化有氧與阻力訓練、教育與心血管風險管理；強度依心肺測試與治療狀況設定。',
    cue: '以監測數值、症狀與當日治療狀況調整，不追求固定速度或重量。',
    regression: '低至中等強度分段有氧、坐姿或較輕阻力，增加休息與監測。',
    signals: CARDIOPULMONARY_SIGNALS,
    evidence: '75 人隨機臨床試驗；CORE 組 8 週峰值攝氧量改善較佳。方案同時包含運動、教育與風險管理，樣本與追蹤有限，不能把效果歸於單一動作。',
    audience: '適用於高心血管風險、由腫瘤心臟與復健團隊共同監督的癌症存活者。',
    sources: [{ label: 'Viamonte et al. Cardio-Oncology Rehabilitation for Cancer Survivors With High Cardiovascular Risk: RCT. JAMA Cardiol. 2023.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10568446/' }],
  },
  {
    id: 'postpartum-dra-rct',
    kind: 'condition',
    selectionLabel: '產後腹直肌分離',
    bodyRegion: '脊椎與軀幹',
    searchAliases: ['腹直肌分離', '產後核心', 'DRA', '腹直肌訓練', '腹橫肌'],
    theme: 'blue',
    eyebrow: '2023 試辦隨機對照試驗',
    title: '產後腹直肌分離：捲腹與腹橫肌啟動比較',
    summary: '小型試辦研究中，短捲腹組的腹直肌間距縮小較多；高失訪與量測侷限使結果不足以宣布「捲腹最好」，功能與症狀仍更重要。',
    images: [trialImage('postpartum-dra-rct', '產後腹直肌分離的仰躺腹部控制、小幅捲腹、腳跟滑動與橋式四格示意', '從可控制的腹部收縮開始，依症狀逐步增加')],
    suitableFor: '原試驗納入陰道生產後 72 小時內、腹直肌間距至少 30 mm 者；這不等於建議所有產婦在產後 72 小時自行開始，實際時點須由產科／骨盆健康專業人員依出血、傷口、疼痛與骨盆底狀況確認。',
    dosage: '原試驗在產後 72 小時內完成基線評估後個別處方：腹橫肌組做仰躺屈膝 5 秒啟動，腹直肌組做 1 秒小幅捲腹；基線處方 1–10 下，6 週評估後可到 1–20 下，每天 2 次、每週至少 5 天。這是小型試辦研究的時點與劑量，不是普遍產後醫囑。',
    cue: '動作過程可呼吸且沒有骨盆底壓迫、疼痛或明顯代償；不只看腹部外觀。',
    regression: '減少捲起幅度或只做短時間腹部啟動，暫停會誘發症狀的動作。',
    signals: {
      green: '能自然呼吸，腹部與骨盆底沒有疼痛、沉重或漏尿增加，日常功能維持穩定。',
      yellow: '腹部明顯不適、骨盆底沉重、漏尿或出血增加：減量並聯絡產後／骨盆健康專業人員。',
      red: '大量出血、發燒、傷口異常、劇烈腹痛、單側小腿腫痛、胸痛或呼吸困難：停止並立即就醫。',
    },
    evidence: '44 人試辦 RCT；腹直肌組在 6、12 週部分量測點的間距縮小較多，無通報不良事件，但 COVID-19 造成高失訪且缺乏依從性日誌。屬可行性訊號，不是確定療效。',
    audience: '適用於產後醫療評估後的腹直肌分離；剖腹產、骨盆底症狀或疼痛需個別調整。',
    sources: [{ label: 'Simpson and Hahne. Early postpartum rectus versus transversus training: pilot RCT. 2023.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10686295/' }],
  },
  {
    id: 'knee-internet-exercise-rct',
    kind: 'condition',
    selectionLabel: '慢性膝痛遠距復健',
    bodyRegion: '髖膝與大腿',
    searchAliases: ['慢性膝痛', '膝骨關節炎', 'Skype 物理治療', '遠距運動', '疼痛因應'],
    theme: 'green',
    eyebrow: '2017 隨機對照試驗',
    title: '慢性膝痛：視訊運動＋疼痛因應技巧',
    summary: '七次視訊物理治療、居家肌力與網路疼痛因應訓練，在 3 個月改善疼痛與功能，部分效果維持至 9 個月。',
    images: [trialImage('knee-internet-exercise-rct', '慢性膝痛的視訊指導坐站、低台階、彈力帶膝伸與髖外展四格示意', '治療師透過視訊校正下肢肌力與功能動作')],
    suitableFor: '40 歲以上、慢性膝痛符合膝骨關節炎臨床標準，且能安全使用視訊與居家運動的成人。',
    dosage: '3 個月內 7 次視訊物理治療（原研究使用 Skype），處方 5–6 個下肢肌力動作、每週 3 次，並完成 8 個網路疼痛因應模組；依視訊觀察調整阻力與動作品質。',
    cue: '鏡頭需看得到全身與支撐物，先確保環境安全再進行遠距動作。',
    regression: '高椅坐站、較低台階、較輕彈力帶並減少組次。',
    signals: MUSCULOSKELETAL_SIGNALS,
    evidence: '148 人 RCT；遠距運動＋疼痛因應組在 3 個月疼痛與功能優於網路教育控制，部分結果維持 9 個月。介入是運動與心理技巧組合，不能只歸因於單一肌力動作。',
    audience: '適用於穩定慢性膝痛且能安全遠距訓練者。',
    sources: [{ label: 'Bennell et al. Internet-delivered exercise and pain-coping skills for chronic knee pain: RCT. Ann Intern Med. 2017.', href: 'https://pubmed.ncbi.nlm.nih.gov/28241215/' }],
  },
  {
    id: 'escape-meniscal-pt-rct',
    kind: 'condition',
    selectionLabel: '退化性半月板撕裂',
    bodyRegion: '髖膝與大腿',
    searchAliases: ['半月板撕裂', '退化性半月板', '膝關節鏡', 'ESCAPE', '物理治療'],
    theme: 'orange',
    eyebrow: '2018 ESCAPE 隨機臨床試驗',
    title: '退化性半月板：運動物理治療與關節鏡手術比較',
    summary: '8 週運動物理治療在 24 個月膝功能不劣於早期關節鏡部分切除；部分人後續仍選擇手術，需共同決策而非一概排斥。',
    images: [trialImage('escape-meniscal-pt-rct', '退化性半月板撕裂的腳踏車、淺蹲、低台階弓步與扶穩單腳平衡四格示意', '以心肺暖身、閉鏈肌力、協調與平衡組成方案')],
    suitableFor: '45–70 歲、MRI 確認退化性半月板撕裂且沒有真正鎖膝、嚴重骨關節炎或急性外傷性撕裂者。',
    dosage: '8 週共 16 次、每次 30 分鐘物理治療；包含心肺暖身、協調與平衡、閉鏈下肢肌力與功能動作，原文補充資料有逐級動作。',
    cue: '以膝伸直能力、腫脹與功能控制決定深度；不是用疼痛反覆測試撕裂。',
    regression: '低阻力腳踏車、高椅坐站、較低台階與雙手扶穩平衡。',
    signals: MUSCULOSKELETAL_SIGNALS,
    evidence: '321 人、多中心隨機臨床試驗；24 個月物理治療在自評膝功能不劣於關節鏡部分半月板切除，五年追蹤仍支持非劣性。原文有運動流程與附錄；有真正鎖膝者未納入。',
    audience: '適用於非阻塞型退化性半月板撕裂成人，用於與骨科共同決策。',
    sources: [{ label: 'van de Graaf et al. ESCAPE trial: physical therapy versus arthroscopic surgery for degenerative meniscal tears. JAMA. 2018.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6583004/' }],
  },
]
