import type { ExerciseGuideModule } from './exercise-guides'

const RESEARCH_DATE = '2026-09-28'
const researchImage = (id: string, alt: string) => [{
  src: `/images/exercise-guides/${id}.svg`,
  width: 1200,
  height: 900,
  step: '研究方案圖解',
  alt,
  caption: '本站原創研究流程示意，呈現代表性安排；不是論文原圖，也不是每位患者都適用的固定處方。',
}]

export const CURATED_CARDIO_GUIDES: ExerciseGuideModule[] = [
  {
    id: 'hf-action-aerobic-training-rct',
    kind: 'condition', evidenceKind: 'rct', reviewStatus: 'approved', approvalDate: RESEARCH_DATE,
    publishedDate: RESEARCH_DATE, modifiedDate: RESEARCH_DATE,
    selectionLabel: '穩定心衰竭有氧訓練', bodyRegion: '全身與神經',
    searchAliases: ['心臟復健', '心衰竭運動', 'HF-ACTION', '射出分率降低', '心肺耐力'],
    supervision: 'medical-team', theme: 'blue', eyebrow: '2009 大型多中心隨機試驗',
    title: '穩定心衰竭：HF-ACTION 的監督有氧與居家銜接',
    summary: '心衰竭患者能否運動，先取決於病況與運動評估。HF-ACTION 支持在穩定、經篩選的患者中安排結構化有氧訓練；主要死亡或住院比較未達統計顯著，不能承諾運動一定延長壽命。',
    images: researchImage('hf-action-aerobic-training-rct', '心衰竭復健的醫療評估、監督步行或腳踏車、逐步調整與居家追蹤四格流程'),
    steps: [
      { title: '先做心肺評估', instruction: '由心臟與復健團隊確認病況穩定，檢視運動測試、症狀及用藥，再決定合適的模式與強度。', dosage: '研究先做心肺運動測試；不能用年齡公式自行設定心率。' },
      { title: '監督下有氧', instruction: '研究使用步行、跑步機或固定式腳踏車；由工作人員觀察反應，開始與結束都保留緩慢轉換。', dosage: '研究目標為 3 個月內完成 36 次監督課程。' },
      { title: '逐次確認耐受', instruction: '記下活動時間、呼吸感受與異常症狀，由團隊決定是否延長；不要同時自行加速度及時間。', dosage: '研究起始每次 15–30 分鐘；這是試驗安排，不是新患者起始量。' },
      { title: '銜接居家追蹤', instruction: '確認可安全執行後才轉入居家模式，保留紀錄及回診；中斷或身體狀況改變時重新評估。', dosage: '研究第 18 次監督後開始銜接，第 36 次後轉居家。' },
    ],
    suitableFor: '已診斷射出分率降低型心衰竭、接受穩定藥物治療，並經團隊判斷可以訓練的成人。研究收納左心室射出分率不超過 35% 的穩定門診患者；剛急性惡化、尚在調整治療或未經運動評估者，不能照這個流程自行開始。',
    dosage: '研究先安排每週 3 次監督訓練，後續居家目標為每週 5 次、每次 40 分鐘，強度依實測心率儲備設定。許多人實際完成量低於目標，因此不能把研究目標當成必須達成的最低量；個別處方仍由團隊依症狀、功能、藥物及裝置調整。',
    cue: '訓練重點是可持續的活動與回報症狀。使用影響心率的藥物或植入裝置時，不要只追著手錶數字走，也不要因某天不喘就跨級增加負荷。',
    regression: '若原定活動變得明顯困難，先停止增加，由團隊改短時間、增加休息或回到監督環境；突然耐力下降需要找原因，不能單純當成體力差而硬練。',
    followUpLabel: '追蹤功能與病況',
    followUp: '回診時帶活動紀錄，討論走路與日常任務是否改善、是否有中斷原因。新出現的水腫、夜間喘或活動能力下滑應提早聯絡原團隊，不等訓練週期結束。',
    signals: { green: '在團隊允許的範圍完成活動，症狀與日常功能維持穩定。', yellow: '比平常更喘、恢復變慢、新增水腫或心悸：停止加量並聯絡團隊。', red: '胸痛、昏厥、休息仍明顯呼吸困難或持續不適：立即停止並緊急就醫。' },
    evidence: 'HF-ACTION 將 2,331 人隨機分組，中位追蹤 30 個月。主要死亡或全因住院結果的風險比為 0.93（95% 信賴區間 0.84–1.02），未達顯著；預先規劃的額外校正分析才顯示小幅效益。多中心規模與盲性事件判定提升可信度，但依從性下降、組間活動交叉及當時治療背景限制解讀。',
    audience: '提供穩定心衰竭患者與家屬理解心臟復健服務；不是急性心衰竭、自行停藥或居家運動測試指南。',
    sources: [{ label: 'O’Connor CM, Whellan DJ, Lee KL, et al. Efficacy and Safety of Exercise Training in Patients With Chronic Heart Failure: HF-ACTION Randomized Controlled Trial. JAMA. 2009;301(14):1439–1450. doi:10.1001/jama.2009.454.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC2916661/' }],
  },
  {
    id: 'rehab-hf-multidomain-rehabilitation-rct',
    kind: 'condition', evidenceKind: 'rct', reviewStatus: 'approved', approvalDate: RESEARCH_DATE,
    publishedDate: RESEARCH_DATE, modifiedDate: RESEARCH_DATE,
    selectionLabel: '心衰竭住院後體能', bodyRegion: '全身與神經',
    searchAliases: ['REHAB-HF', '衰弱', '心衰竭出院', '老人心臟復健', '住院後無力'],
    supervision: 'medical-team', theme: 'teal', eyebrow: '2021 多中心隨機試驗',
    title: '心衰竭住院後：REHAB-HF 的四面向功能復健',
    summary: '年長心衰竭患者出院後，可能同時面臨站不穩、起身無力與走不遠。REHAB-HF 將平衡、力量、移動與耐力一起處理，改善 3 個月身體功能；沒有證明能減少 6 個月再住院。',
    images: researchImage('rehab-hf-multidomain-rehabilitation-rct', '年長心衰竭患者接受支撐平衡、起身力量、轉位步行與耐力分段訓練的四面向示意'),
    steps: [
      { title: '平衡與安全支撐', instruction: '治療師先確認坐站穩定度，選擇需要的扶手與協助；圖解的站姿不代表每個人已經可以站立。', dosage: '依功能層級選動作，不以住院天數強制進階。' },
      { title: '起身與下肢力量', instruction: '把從椅子起身等生活任務列為力量目標，座高、扶手及協助量均由治療師設定。', dosage: '次數依當天能力決定；尚不能起身者採更低層級活動。' },
      { title: '移動與步行', instruction: '在適當協助下練習轉位、走路及方向改變，先確保動作安全，再延長活動範圍。', dosage: '研究同時處理移動能力，不只要求連續走得更久。' },
      { title: '分段累積耐力', instruction: '把可耐受的活動與休息交替，逐步銜接出院後課程；心肺反應與疲倦均納入調整。', dosage: '研究安排出院後 36 次門診訓練，於 3 個月評估功能。' },
    ],
    suitableFor: '因急性失代償心衰竭住院的年長成人，經醫療團隊判斷可開始個別復健；本篇說明從住院銜接門診的照護概念。仍有不穩定症狀、不能安全配合或需要高度生命支持時，活動範圍由病房團隊決定。',
    dosage: '研究介入於住院期間或早期住院後啟動，出院後延續 36 次門診課程，並非所有患者做同一套次數。每次按平衡、力量、移動與耐力分別分級，能力較弱的面向先獲得適當支持；圖解四格是研究領域摘要，不是要求同一天全部完成的清單。',
    cue: '先問「是否更容易起身、移動與完成生活任務」，再問走了幾分鐘。恢復的速度會受到原本衰弱程度、共病與病況影響，不應拿別人的進度當標準。',
    regression: '從站立退回有支撐的坐姿活動，或增加轉位協助，必須由治療師選擇。若突然退步，先排除醫療問題，再決定是不是降低運動量即可。',
    followUpLabel: '出院後如何接續',
    followUp: '出院前確認門診復健、輔具與家中動線安排；回診同時檢視跌倒或近跌倒、活動紀錄及心衰竭症狀。課程中斷後先重評，不直接回到中斷前的最高負荷。',
    signals: { green: '協助量適當，起身與移動逐步穩定，活動後能恢復。', yellow: '頻繁近跌倒、起身暈眩、疲憊增加或走路突然變慢：先停止進階並通報。', red: '胸痛、昏倒、休息時喘或急速惡化：停止活動並立即由醫療團隊處理。' },
    evidence: '349 人的隨機試驗中，97% 屬衰弱或衰弱前期。3 個月短式身體功能量表（SPPB）校正後組間差為 1.5 分（95% 信賴區間 0.9–2.0），有利復健；6 個月全因再住院沒有顯著減少。研究由多中心執行，但課程依從性約 67%，且不是以證明死亡率降低為主要設計，不宜把功能改善等同疾病治癒。',
    audience: '供患者、照顧者與醫療人員討論出院後多面向復健；需要心臟與復健團隊共同規劃。',
    sources: [{ label: 'Kitzman DW, Whellan DJ, Duncan P, et al. Physical Rehabilitation for Older Patients Hospitalized for Heart Failure. N Engl J Med. 2021;385(3):203–216. doi:10.1056/NEJMoa2026141.', href: 'https://pubmed.ncbi.nlm.nih.gov/33999544/' }],
  },
  {
    id: 'copd-home-pulmonary-rehabilitation-rct',
    kind: 'condition', evidenceKind: 'rct', reviewStatus: 'approved', approvalDate: RESEARCH_DATE,
    publishedDate: RESEARCH_DATE, modifiedDate: RESEARCH_DATE,
    selectionLabel: 'COPD 居家肺復健', bodyRegion: '全身與神經',
    searchAliases: ['慢性阻塞性肺病', '肺阻塞', 'COPD', '肺復健', '在家運動會喘'],
    supervision: 'medical-team', theme: 'green', eyebrow: '2017 隨機等效性試驗',
    title: '穩定肺阻塞：有專業追蹤的居家肺復健',
    summary: '交通或體力讓你難以到院復健時，可以和肺復健團隊討論居家模式。這項研究的居家方案包含一次家訪與每週電話，不是只發一張運動單；短期效果可接近中心課程，長期維持仍是問題。',
    images: researchImage('copd-home-pulmonary-rehabilitation-rct', '居家肺復健的首次評估、步行、椅子起身與簡易阻力、電話追蹤四格流程'),
    steps: [
      { title: '首次家訪評估', instruction: '物理治療師檢視居家環境、吸入器使用與活動目標，陪同完成第一次課程。', dosage: '研究包含 1 次家訪；不以自行看圖取代首次評估。' },
      { title: '選擇可行有氧', instruction: '研究常使用步行，以可取得的場地與個人能力安排；同時記下時間及距離供團隊調整。', dosage: '研究建議每次至少 30 分鐘有氧；個人起始量須另評估。' },
      { title: '生活動作練力', instruction: '研究納入椅子起身、踏階及水瓶阻力等方法，治療師依穩定度與呼吸反應選擇，不必全做。', dosage: '器材可以簡單，阻力與總量仍須個別設定。' },
      { title: '每週追蹤調整', instruction: '透過電話檢視完成情形、設定下一步目標，討論急性惡化處理與持續活動的方法。', dosage: '研究家訪後有 7 次每週電話，整體介入 8 週。' },
    ],
    suitableFor: '病況穩定、能配合居家紀錄，並經胸腔與肺復健團隊評估的 COPD 成人。研究排除近 4 週急性惡化及無法運動的共病；剛住院、氧氣需求改變或明顯不穩定者，不能直接套用這個服務模式。',
    dosage: '研究比較 8 週居家方案與門診中心肺復健，兩者都保留運動及自我管理元素。實際步行時長、休息方式和阻力量由團隊調整；需要氧氣者依原處方使用，不能為了完成研究時間自行增加、減少或拔除氧氣。',
    cue: '居家課程的核心是持續溝通與目標設定。把「做了多少、為什麼沒做、呼吸與腿部疲勞如何」記清楚，比硬湊時間更有助於下一次安排。',
    regression: '不適增加時先停下休息並回報，團隊可縮短單段時間或調整動作；無扶手的踏階不適合平衡不足者，不能只因器材在家中就認為安全。',
    followUpLabel: '八週後還需要維持計畫',
    followUp: '課程結束時就討論後續活動及再評估，因研究兩組在 12 個月均未保有原先進步。若咳嗽、痰或呼吸狀況改變，先依既有急性惡化計畫聯絡團隊。',
    signals: { green: '在個人計畫內活動，休息後呼吸恢復，日常功能穩定。', yellow: '比平常更喘、恢復較慢、痰量或症狀改變：暫停加量並聯絡照護團隊。', red: '休息時嚴重喘、胸痛、意識改變或嘴唇發紫：立即停止並緊急就醫。' },
    evidence: '166 人、兩中心、評估者盲性的隨機等效性試驗，介入結束時六分鐘步行距離支持居家模式不劣於中心模式；12 個月則無法排除居家模式較差，且兩組進步都未維持。中心組完成率偏低會影響比較，結果不表示所有居家服務、所有肺病或無追蹤自練都同樣有效。',
    audience: '供穩定 COPD 患者討論替代的肺復健服務；不是急性喘的處理流程，也不是停用吸入藥物的依據。',
    sources: [{ label: 'Holland AE, Mahal A, Hill CJ, et al. Home-based rehabilitation for COPD using minimal resources: a randomised, controlled equivalence trial. Thorax. 2017;72(1):57–65. doi:10.1136/thoraxjnl-2016-208514.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5329049/' }],
  },
  {
    id: 'icu-team-early-mobilization-rct',
    kind: 'condition', evidenceKind: 'rct', reviewStatus: 'approved', approvalDate: RESEARCH_DATE,
    publishedDate: RESEARCH_DATE, modifiedDate: RESEARCH_DATE,
    selectionLabel: '加護病房活動安全', bodyRegion: '全身與神經',
    searchAliases: ['TEAM 試驗', '加護病房復健', 'ICU', '呼吸器', '重症早期活動'],
    supervision: 'medical-team', theme: 'violet', eyebrow: '2022 多國隨機試驗｜負面結果',
    title: '呼吸器治療中的早期活動：TEAM 提醒不是越多越好',
    summary: 'TEAM 比較加強早期主動活動與各院常規照護，沒有改善 180 天存活且離院的天數，活動相關不良事件反而增加。這篇協助家屬理解團隊如何拿捏活動，不提供自行幫患者站起的操作處方。',
    images: researchImage('icu-team-early-mobilization-rct', '加護病房復健的資格評估、團隊個別設定、監測下活動與重新評估四格安全流程'),
    steps: [
      { title: '先判斷能否活動', instruction: '由加護團隊確認當天清醒程度、呼吸循環狀況與管路安全，不能只看患者是否能抬手。', dosage: '每次活動前重評；家屬不自行判讀資格。' },
      { title: '團隊設定目標', instruction: '醫師、護理師與治療師依病況討論當天適合的活動層級及協助方式，必要時暫緩。', dosage: '不把較早站起或較多分鐘當成每人目標。' },
      { title: '監測下進行', instruction: '只在工作人員指導及保護下進行選定活動，持續觀察循環、呼吸與不適反應。', dosage: '研究平均活動時間是觀察結果，不能照數字複製。' },
      { title: '停止並重新評估', instruction: '反應不佳時立即由團隊處理；下次是否恢復或退階，依重新評估決定。', dosage: '當天完成一項，不代表隔天必須更進一步。' },
    ],
    suitableFor: '正在接受侵入性呼吸器治療的成人患者之家屬，以及需要理解重症復健決策的人。此情境完全屬醫療團隊監督範圍，任何床邊坐起、站立、轉位或步行都不能由非專業人士依圖自行嘗試。',
    dosage: '750 人試驗中的加強活動組每日主動活動平均 20.8 分鐘，常規組為 8.8 分鐘；這是兩組實際暴露量，不是安全上限、最低需要量或建議處方。常規照護本來就包含活動，研究不能解讀為「完全不動比所有復健都好」。',
    cue: '要討論的是此刻患者是否能承受這項活動、是否有合適人力與監測。早一天站起的短期表現，不能代替存活、離院與生活功能等較重要結果。',
    regression: '若團隊認為尚不適合主動活動，依病況採其決定的照護或較低層級安排。不要自行改呼吸器、氧氣、鎮靜藥物或管路來讓活動「順利完成」。',
    followUpLabel: '適合和加護團隊討論的事項',
    followUp: '家屬可提供生病前走路能力、輔具與跌倒紀錄，協助設定現實目標。離開加護病房後仍需重新評估恢復需求，不能把本試驗直接套用到所有出院後復健。',
    signals: { green: '當班團隊確認可進行且全程監測；這不是家屬自行判定的綠燈。', yellow: '疲倦、不適或監測數值偏離個人設定：立即告知在場醫護，是否續做由團隊決定。', red: '心律、血壓或血氧異常，意識改變或管路安全問題：由在場醫療團隊立即處理。' },
    evidence: 'TEAM 是 49 家醫院、6 國參與的 RCT。180 天存活且離院天數中位數為 143 與 145 天，無顯著差異；可能與活動相關的不良事件為 9.2% 與 4.1%。試驗規模大、追蹤完整，顯示加強早期活動不能一概視為更好；但各院常規活動不同，也不能外推成所有重症患者都應避免復健。',
    audience: '供家屬理解醫療決策的證據圖解；沒有任何一步可作為家屬自行執行的 ICU 運動教程。',
    sources: [{ label: 'TEAM Study Investigators and the ANZICS Clinical Trials Group; Hodgson CL, Bailey M, Bellomo R, et al. Early Active Mobilization during Mechanical Ventilation in the ICU. N Engl J Med. 2022;387(19):1747–1758. doi:10.1056/NEJMoa2209083.', href: 'https://pubmed.ncbi.nlm.nih.gov/36286256/' }],
  },
  {
    id: 'colon-cancer-challenge-exercise-rct',
    kind: 'condition', evidenceKind: 'rct', reviewStatus: 'approved', approvalDate: RESEARCH_DATE,
    publishedDate: RESEARCH_DATE, modifiedDate: RESEARCH_DATE,
    selectionLabel: '結腸癌治療後運動', bodyRegion: '全身與神經',
    searchAliases: ['CHALLENGE', '大腸癌運動', '結腸癌', '化療後運動', '癌症復健', '癌症運動'],
    supervision: 'medical-team', theme: 'orange', eyebrow: '2025 多中心第三期隨機試驗',
    title: '結腸癌輔助化療後：CHALLENGE 的長期運動支持',
    summary: '完成結腸癌手術與輔助化療後，有持續支持的運動方案可成為照護的一部分。CHALLENGE 的 3 年方案改善無病存活，並有支持整體存活較佳的結果；適用的是特定治療後族群，不能推論運動能代替抗癌治療。',
    images: researchImage('colon-cancer-challenge-exercise-rct', '結腸癌治療後的團隊評估、選擇可行活動、持續支持與追蹤傷害四格研究方案圖'),
    steps: [
      { title: '治療後先評估', instruction: '和腫瘤及復健團隊確認治療階段、體力與影響活動的症狀，再決定是否適合進入運動方案。', dosage: '本研究在完成輔助化療後啟動，不是化療中通用課表。' },
      { title: '選擇可行活動', instruction: '以能長期融入生活的身體活動作為討論起點，考量場地、喜好與需要的協助。', dosage: '圖解是規劃概念；不把固定步數當成試驗驗證處方。' },
      { title: '持續支持習慣', instruction: '讓有資格的運動與醫療人員追蹤執行情形，將難以持續的原因納入調整，不以意志力硬撐。', dosage: '研究介入持續 3 年，不能等同一次衛教或短期挑戰。' },
      { title: '追蹤功能與傷害', instruction: '保留癌症追蹤，同時記錄肌肉骨骼不適、活動能力及中斷原因，讓團隊調整進度。', dosage: '體力改善不代表可以延後檢查或省略原有治療。' },
    ],
    suitableFor: '完成結腸癌切除與輔助化療後、經腫瘤團隊確認適合運動規劃的成人。研究不能直接代表直腸癌、轉移性疾病、正在接受不同療程或所有其他癌症；若病況、造口、神經症狀或共病影響活動，需另訂安排。',
    dosage: '研究比較 3 年結構化運動支持與健康教育資料，結果來自整體服務，不是單一動作、固定每日步數或某個「抗癌強度」。試驗中的支持與追蹤需由合格團隊持續提供；實際頻率與強度由照護團隊依治療狀態和個人能力共同設定。',
    cue: '先找到能持續且可調整的活動，再逐步增加。活動較少或暫時中斷並不等於個人造成復發，研究的群體結果不能拿來責備患者。',
    regression: '疲倦或肌肉骨骼不適增加時，回報團隊後調整活動模式與份量；平衡受影響時需重新選擇環境及支撐，不能僅靠降低速度就假設安全。',
    followUpLabel: '運動與癌症追蹤並行',
    followUp: '把運動安排放進原有追蹤計畫，討論可行的支持資源、症狀與功能。長期目標可以調整，不必為追逐研究結果而忍痛、補做或突然加倍活動。',
    signals: { green: '團隊確認適合，活動後恢復可接受，沒有持續增加的不適。', yellow: '新發或持續的疼痛、異常疲倦、步態改變：暫停進階並回報。', red: '胸痛、昏厥、明顯呼吸困難或急性嚴重症狀：停止並緊急就醫。' },
    evidence: '55 個中心的 889 人 RCT，中位追蹤 7.9 年。5 年無病存活率為 80.3% 與 73.9%；其終點合併復發、新原發癌或死亡，不能簡寫成復發率降低相同比例。肌肉骨骼不良事件為 18.5% 與 11.5%，運動組較多。隨機分派及長期臨床結果是優點，但外推族群與服務執行條件有限。',
    audience: '供完成結腸癌治療的患者與家屬討論長期支持；不保證個人療效，也不取代腫瘤科追蹤。',
    sources: [{ label: 'Courneya KS, Vardy JL, O’Callaghan CJ, et al.; CHALLENGE Investigators. Structured Exercise after Adjuvant Chemotherapy for Colon Cancer. N Engl J Med. 2025;393(1):13–25. doi:10.1056/NEJMoa2502760.', href: 'https://pubmed.ncbi.nlm.nih.gov/40450658/' }],
  },
  {
    id: 'breast-cancer-lymphedema-resistance-rct',
    kind: 'condition', evidenceKind: 'rct', reviewStatus: 'approved', approvalDate: RESEARCH_DATE,
    publishedDate: RESEARCH_DATE, modifiedDate: RESEARCH_DATE,
    selectionLabel: '乳癌淋巴水腫與阻力', bodyRegion: '上肢與手部',
    searchAliases: ['乳癌術後', '淋巴水腫', '手臂腫脹', '重量訓練', '阻力訓練'],
    supervision: 'medical-team', theme: 'teal', eyebrow: '2009 隨機對照試驗',
    title: '穩定乳癌相關淋巴水腫：慢慢增加的阻力訓練',
    summary: '有穩定淋巴水腫不代表永遠不能做重量訓練。這項試驗在配戴合身壓力衣與逐步加量的條件下，未增加手臂腫脹，且力量和部分症狀改善；結果不能套用到突然腫起、感染或自行重訓。',
    images: researchImage('breast-cancer-lymphedema-resistance-rct', '淋巴水腫患者先評估壓力衣與症狀、輕阻力練習、逐步加量並追蹤腫脹的四格示意'),
    steps: [
      { title: '先確認水腫穩定', instruction: '請淋巴水腫團隊檢查皮膚、既有症狀與壓力衣，建立可比較的基準，再安排訓練。', dosage: '試驗對象為穩定手臂淋巴水腫，不是急性腫脹。' },
      { title: '學會阻力動作', instruction: '先由專業人員確認握持、關節活動與呼吸方式，選擇能控制的阻力，不從日常可搬重量推算起始量。', dosage: '研究採漸進重量訓練，不要求第一堂就做到力竭。' },
      { title: '慢慢增加負荷', instruction: '依症狀、動作品質和團隊檢視來決定是否加量；圖示代表逐步負荷，不是固定啞鈴重量。', dosage: '研究每週訓練 2 次，主要腫脹結果於 1 年評估。' },
      { title: '追蹤手臂反應', instruction: '觀察衣袖或壓力衣感受、沉重感及活動能力，出現變化時回報，不只看當下有沒有痛。', dosage: '研究要求訓練時穿合身壓力衣；個別使用仍依團隊。' },
    ],
    suitableFor: '乳癌治療後已有穩定手臂淋巴水腫，願意接受淋巴水腫評估及漸進訓練的成人女性。手術後尚未獲准活動、皮膚感染、突然腫脹或病況未釐清者不適用；沒有水腫但屬高風險的族群，與本篇研究問題也不同。',
    dosage: '研究以每週 2 次、緩慢漸進的重量訓練追蹤 1 年，並要求合身壓力衣。這些條件屬整體方案的一部分，不能只拿「重訓沒有變腫」當成不限重量的許可。本篇不指定通用組數，因起始重量、恢復及症狀差異需要個別評估。',
    cue: '目標是逐步恢復力量與生活能力，不是用重量把腫脹「壓回去」。訓練不能代替既有水腫管理，也不要因一次無不適就跳級增加負荷。',
    regression: '不適或沉重感上升時先停止加重，交由團隊確認是否回到更輕阻力或暫停該項。新發腫脹需找原因，不直接認定只是正常運動反應。',
    followUpLabel: '把力量與腫脹一起追蹤',
    followUp: '回診提供症狀與訓練紀錄，讓團隊比較腫脹、活動與日常功能。壓力衣不合身或皮膚不適應及時處理，不要為完成課表而勉強穿戴。',
    signals: { green: '既有水腫維持穩定，動作可控制，訓練後沒有持續增加的沉重感。', yellow: '腫脹、緊繃或活動受限增加：暫停進階並聯絡淋巴水腫團隊。', red: '手臂迅速紅腫熱痛、發燒或突然明顯腫脹：停止並儘速就醫。' },
    evidence: '141 名穩定淋巴水腫女性的 RCT，雙側手臂體積差增加至少 5 個百分點的比例為訓練組 11%、對照組 12%，未有顯著差異；專業判定的水腫惡化發作較少，力量較佳。研究支持特定漸進方案的安全性，但樣本及族群有限，不能承諾重訓治好水腫，也不能外推到所有癌症或急性症狀。',
    audience: '供穩定乳癌相關淋巴水腫患者討論阻力訓練；需由淋巴水腫及癌症照護團隊協調。',
    sources: [{ label: 'Schmitz KH, Ahmed RL, Troxel A, et al. Weight lifting in women with breast-cancer-related lymphedema. N Engl J Med. 2009;361(7):664–673. doi:10.1056/NEJMoa0810118.', href: 'https://pubmed.ncbi.nlm.nih.gov/19675330/' }],
  },
  {
    id: 'diabetes-dare-combined-exercise-rct',
    kind: 'condition', evidenceKind: 'rct', reviewStatus: 'approved', approvalDate: RESEARCH_DATE,
    publishedDate: RESEARCH_DATE, modifiedDate: RESEARCH_DATE,
    selectionLabel: '第二型糖尿病運動', bodyRegion: '全身與神經',
    searchAliases: ['糖尿病', '血糖', 'HbA1c', '有氧加阻力', 'DARE'],
    supervision: 'medical-team', theme: 'blue', eyebrow: '2007 四組隨機試驗',
    title: '第二型糖尿病：DARE 的有氧與阻力組合',
    summary: '有氧和阻力訓練都能是血糖照護的一部分。DARE 試驗中，合併組的糖化血色素改善較大，但合併組也花了更多時間運動，不能因此宣稱相同時間下混合訓練一定最好。',
    images: researchImage('diabetes-dare-combined-exercise-rct', '糖尿病運動的用藥及風險評估、有氧、阻力與血糖功能追蹤四格示意'),
    steps: [
      { title: '先談用藥與安全', instruction: '與照護團隊確認運動評估、低血糖處理及足部等限制，先知道出現不適要如何回應。', dosage: '研究受試者須完成運動篩檢及 4 週導入期。' },
      { title: '安排有氧活動', instruction: '依能力選擇可重複執行的活動模式，記下時間與感受，逐步建立可維持的節奏。', dosage: '強度與時間個別設定，不能用流汗量判斷血糖效益。' },
      { title: '加入阻力練習', instruction: '由專業人員教導大肌群出力及呼吸，確保動作品質後，再和有氧安排在整體課程裡。', dosage: '研究合併兩種訓練，總時間多於單一模式。' },
      { title: '追蹤整體反應', instruction: '回診檢視血糖、症狀、活動能力及完成情形，藥物是否調整由醫療人員決定。', dosage: '研究訓練每週 3 次、22 週，於約 6 個月比較 HbA1c。' },
    ],
    suitableFor: '已診斷第二型糖尿病，接受適當風險評估且能配合運動及回診的成人。試驗收納 39–70 歲、通過運動壓力測試或心臟科許可並完成導入期的人；不能直接套用到所有共病、胰島素療程或功能受限者。',
    dosage: '研究把患者分為有氧、阻力、兩者合併或久坐對照，正式訓練每週 3 次、共 22 週。個人需要多少時間及阻力取決於能力與治療情境，不能直接照合併組做雙倍運動，更不能用運動量換算應少吃多少藥。',
    cue: '把規律完成與安全反應當作進步指標。血糖單次下降不等於長期控制改善；HbA1c 的變化也不等於每個人都能獲得相同效果。',
    regression: '先和團隊調整為較短活動或較容易控制的阻力動作；如果不適可能與血糖有關，應先按既有處理計畫確認原因，不靠繼續運動來「壓下血糖」。',
    followUpLabel: '運動紀錄帶回糖尿病門診',
    followUp: '記錄運動前後的不適、低血糖事件與執行困難，協助團隊調整。足部傷口、視力或活動耐受改變時，先重新評估再進階；這些安全限制不是單一試驗替每個人排除過的風險。',
    signals: { green: '依個人計畫活動，沒有血糖相關不適或持續疼痛，恢復正常。', yellow: '異常顫抖、冒汗、心悸、頭暈或新足部不適：停止並依既有計畫處理、聯絡團隊。', red: '意識混亂、昏厥、無法安全進食、胸痛或嚴重呼吸困難：立即尋求緊急醫療協助。' },
    evidence: '251 人四組 RCT 顯示合併訓練的 HbA1c 改善分別比單做有氧、阻力多 0.46 與 0.59 個百分點；血壓及血脂組間未顯著不同。試驗直接比較多種模式是優點，但合併組總運動時間較長、導入期篩選出較能遵從者，且運動組不良事件較多，不能宣稱模式協同效應已被獨立證明。',
    audience: '供第二型糖尿病成人與照護團隊討論訓練組合；不是用藥調整表，也不是急性高低血糖的自行處理教程。',
    sources: [{ label: 'Sigal RJ, Kenny GP, Boulé NG, et al. Effects of aerobic training, resistance training, or both on glycemic control in type 2 diabetes: a randomized trial. Ann Intern Med. 2007;147(6):357–369. doi:10.7326/0003-4819-147-6-200709180-00005.', href: 'https://pubmed.ncbi.nlm.nih.gov/17876019/' }],
  },
  {
    id: 'urinary-incontinence-group-pelvic-floor-rct',
    kind: 'condition', evidenceKind: 'rct', reviewStatus: 'approved', approvalDate: RESEARCH_DATE,
    publishedDate: RESEARCH_DATE, modifiedDate: RESEARCH_DATE,
    selectionLabel: '年長女性骨盆底訓練', bodyRegion: '脊椎與軀幹',
    searchAliases: ['尿失禁', '骨盆底肌', '凱格爾', '咳嗽漏尿', 'GROUP 試驗'],
    supervision: 'professional-guidance', theme: 'violet', eyebrow: '2020 非劣性隨機試驗',
    title: '年長女性漏尿：先學正確收縮，再選團體或個別課程',
    summary: '團體骨盆底課程可以是接受治療的一種方式，但前提是先確認你會正確收縮。GROUP 試驗顯示，專業帶領的團體課程在一年漏尿改善上不劣於個別治療；它沒有證明單靠網路圖解也同樣有效。',
    images: researchImage('urinary-incontinence-group-pelvic-floor-rct', '骨盆底訓練的個別確認、收縮放鬆、生活情境練習與居家紀錄四格概念圖'),
    steps: [
      { title: '個別確認收縮', instruction: '先由骨盆底物理治療師確認收縮方式與能否放鬆，再進入團體或個別課程。', dosage: '研究兩組都有首次個別教學，不跳過這個步驟。' },
      { title: '收縮也要放鬆', instruction: '依學到的方式練習力量、耐力及協調；不要用憋氣、夾腿或向下用力取代骨盆底控制。', dosage: '維持時間與次數按能力調整，不提供人人相同的秒數。' },
      { title: '練進生活任務', instruction: '在治療師教導下把控制整合到咳嗽等情境，逐步改變姿勢與難度；不在排尿中反覆練習。', dosage: '研究分為三個 4 週階段，依課程進度增加難度。' },
      { title: '居家練習與紀錄', instruction: '依個別作業練習，記下漏尿情境及困難；仍無法掌握時回到個別確認。', dosage: '研究為 12 週課程，並有後續居家維持及 1 年評估。' },
    ],
    suitableFor: '60 歲以上、以壓力性或混合型尿失禁為主且能參與課程的社區女性。尿急、漏尿或骨盆不適有不同原因，未分類前不宜全部當成肌肉無力；明顯骨盆器官脫垂、疼痛、近期手術或活動受限需個別評估。',
    dosage: '研究每週 1 次、每次 1 小時，包含衛教與運動，共 12 週；團體為 8 人，兩組皆有居家作業。居家安排在介入期每週 5 天，之後每週 3 天持續 9 個月。這些是研究服務頻率，收縮秒數與次數仍依正確執行能力設定。',
    cue: '目標是能收縮、能放鬆、能在需要時控制。愈用力不一定愈好，練習引起疼痛或排尿困難時要回頭確認，不把不適當成有效訓練的證明。',
    regression: '退回較容易掌握的姿勢與較短的收縮，並安排個別檢查動作。團體課中不懂或跟不上時可以要求重新示範，不必勉強追上他人的進度。',
    followUpLabel: '用漏尿情境評估變化',
    followUp: '和治療師約定以排尿日誌及生活受影響程度追蹤，避免只數完成幾下。完成一段治療仍沒有改善，應檢視診斷、動作及依從性，再討論其他照護選擇。',
    signals: { green: '可正確收縮與放鬆，沒有疼痛，生活情境的控制逐步改善。', yellow: '會陰疼痛、越練越緊、用力方向不確定或排尿不順：先暫停並安排評估。', red: '血尿、發燒合併尿路症狀、突然尿滯留，或新發會陰麻木與腿無力：儘速就醫。' },
    evidence: '362 人、兩中心的非劣性 RCT，1 年時個別與團體組漏尿次數減少的中位百分比為 70% 與 74%，達預設非劣性標準。這不是治癒率，也不能解讀為每位患者少漏七成。評估者盲性及一年追蹤是優點，但排除多種共病、活動限制與明顯脫垂，適用範圍有限。',
    audience: '供年長女性選擇有專業帶領的骨盆底治療；男性術後、單純急迫型尿失禁或骨盆疼痛不能直接套用。',
    sources: [{ label: 'Dumoulin C, Morin M, Danieli C, et al.; Urinary Incontinence and Aging Study Group. Group-Based vs Individual Pelvic Floor Muscle Training to Treat Urinary Incontinence in Older Women: A Randomized Clinical Trial. JAMA Intern Med. 2020;180(10):1284–1293. doi:10.1001/jamainternmed.2020.2993.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7400216/' }],
  },
  {
    id: 'fibromyalgia-tai-chi-comparison-rct',
    kind: 'condition', evidenceKind: 'rct', reviewStatus: 'approved', approvalDate: RESEARCH_DATE,
    publishedDate: RESEARCH_DATE, modifiedDate: RESEARCH_DATE,
    selectionLabel: '纖維肌痛太極選擇', bodyRegion: '全身與神經',
    searchAliases: ['纖維肌痛症', '全身疼痛', '太極', '慢性疼痛運動', 'fibromyalgia'],
    supervision: 'professional-guidance', theme: 'green', eyebrow: '2018 比較效果隨機試驗',
    title: '纖維肌痛：太極與有氧如何選擇？',
    summary: '已確診纖維肌痛、又難以持續一般有氧的人，可以和治療團隊討論有指導的太極。研究中的太極整體症狀改善至少相近，部分比較較佳；結果來自完整課程，不能把一個動作或放鬆呼吸說成治療全部疼痛。',
    images: researchImage('fibromyalgia-tai-chi-comparison-rct', '太極課程的暖身、緩慢移重心、呼吸與放鬆、課後反應紀錄四格概念示意'),
    steps: [
      { title: '先暖身與定步', instruction: '由熟悉纖維肌痛的指導者帶領低負荷暖身，找到可穩定站立、能自在呼吸的姿勢。', dosage: '站不穩或膝部不適先調整，沒有必須蹲低的要求。' },
      { title: '緩慢移動重心', instruction: '在可控制的幅度內學習連續緩慢動作，避免為模仿姿勢而硬拉到極限。', dosage: '動作幅度及連續時間個別調整；圖示不是完整楊氏套路。' },
      { title: '呼吸與放鬆', instruction: '課程搭配呼吸、注意力與放鬆練習，不憋氣，也不把特定呼吸節奏當成必要療效條件。', dosage: '研究測試整套身心課程，無法分辨單一元素的效果。' },
      { title: '追蹤並持續練', instruction: '記下疼痛、疲勞、睡眠與生活功能反應，把症狀波動帶回團隊討論後續進度。', dosage: '太極每週 1 或 2 次、12 或 24 週；每堂 60 分鐘。' },
    ],
    suitableFor: '經臨床診斷的成人纖維肌痛患者，願意參與有指導且漸進的運動。全身疼痛不等於纖維肌痛；若症狀尚未分類、出現新的局部腫脹、神經症狀或全身性疾病徵象，應先評估原因。',
    dosage: '研究比較四種太極安排與每週 2 次、24 週的有氧課程，兩者每堂均為 60 分鐘且有居家練習鼓勵。研究課程長度不是所有人的起始耐受量；可與團隊先建立較短、可恢復的安排，不能只因研究做一小時就忍痛跟滿。',
    cue: '找到願意持續、做完能恢復的模式比爭論哪一種一定最好更實際。太極在本研究出席率較高，喜好與可近性也會影響真實生活中的持續練習。',
    regression: '症狀波動時縮小幅度、降低連續時間或增加支撐，並和指導者調整。若每次都出現明顯且持續的功能惡化，先重新評估，不照固定週數硬性加量。',
    followUpLabel: '把功能而非單日疼痛當追蹤重點',
    followUp: '記下能否完成散步、家務、工作與睡眠的變化，和團隊一起比較。研究允許延續原有醫療照護，不能因為參加太極就自行停用藥物或中斷其他治療。',
    signals: { green: '動作穩定，訓練反應可恢復，日常活動逐步維持或改善。', yellow: '症狀增加且影響後續生活、疲倦明顯延長或失去平衡：調整並和團隊討論。', red: '新發局部無力、明顯關節紅腫、發燒、胸痛或昏厥：停止並就醫確認。' },
    evidence: '226 人 RCT 於 24 週比較纖維肌痛影響量表（FIQR），四個太極組合併較有氧組多改善 5.5 分（95% 信賴區間 0.6–10.4）。24 週較 12 週安排有利，每週 2 次未明顯優於 1 次。單一中心、無法遮盲受試者及出席率不同限制解讀；部分缺失值分析削弱顯著性，不能宣稱太極必然勝過有氧。',
    audience: '提供確診纖維肌痛成人討論運動選擇；圖解不取代個別診斷，也不把疼痛簡化為缺乏運動或心理因素。',
    sources: [{ label: 'Wang C, Schmid CH, Fielding RA, et al. Effect of tai chi versus aerobic exercise for fibromyalgia: comparative effectiveness randomized controlled trial. BMJ. 2018;360:k851. doi:10.1136/bmj.k851.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5861462/' }],
  },
]
