import type { ExerciseGuideImage, ExerciseGuideModule } from './exercise-guides'

// Original summaries; study verification and limitations are recorded in
// research-notes/exercise-guides-2026-09-28-msk.md. Publication confirmed by the website content owner on 2026-09-28.
const COMMON = {
  kind: 'condition' as const,
  evidenceKind: 'rct' as const,
  reviewStatus: 'approved' as const,
  approvalDate: '2026-09-28',
  publishedDate: '2026-09-28',
  modifiedDate: '2026-09-28',
}

function schematic(id: string, description: string): ExerciseGuideImage[] {
  return [{
    src: `/images/exercise-guides/${id}.svg`,
    alt: `${description}的原創代表性研究流程示意圖，並非完整或個人化運動處方`,
    step: '研究方案圖解',
    caption: '原創代表性示意：用四個環節理解研究方案，不是論文原圖，也不代表每位患者都適用的動作與劑量。',
    width: 1200,
    height: 900,
  }]
}

export const CURATED_MSK_GUIDES: ExerciseGuideModule[] = [
  {
    ...COMMON,
    id: 'lumbar-stenosis-individualized-rct',
    supervision: 'medical-team',
    bodyRegion: '脊椎與軀幹',
    searchAliases: ['腰椎狹窄', '椎管狹窄', '神經性跛行', 'Schneider', 'lumbar spinal stenosis'],
    selectionLabel: '腰椎狹窄與走路',
    theme: 'blue',
    eyebrow: 'JAMA Network Open・259 人隨機試驗',
    title: '腰椎狹窄走不遠：個別化復健如何安排',
    summary: '走一段路就腿痠麻、坐下較舒服，必須先確認原因。這項試驗支持手法合併個別化運動的短期改善，但半年後各組差異消失；不能把踩腳踏車或單一伸展說成能解除神經壓迫。',
    images: schematic('lumbar-stenosis-individualized-rct', '腰椎狹窄的評估、腳踏車、坐站與步行追蹤'),
    steps: [
      { title: '確認步行症狀來源', instruction: '研究先用影像與臨床表現確認腰椎狹窄及神經性跛行。門診同時檢查腿力、感覺與步行能力，再選個別化運動，不能只憑年齡或腰痠自行套用。', dosage: '研究對象超過 60 歲；開始前完成醫療評估。' },
      { title: '坐姿腳踏車暖身', instruction: '研究方案使用固定式腳踏車。調整座高與阻力，讓雙腳能連續踩動；上車、下車與姿勢由治療師確認，若腿麻加重就停止並回報。', dosage: '原研究居家手冊由每天 5 分鐘起，目標於 6 週內逐步到 20 分鐘；不是人人必須達到。' },
      { title: '選擇肌力與活動練習', instruction: '治療師依檢查安排脊椎穩定、伸展與手法；圖以椅子坐站代表居家動作選項。先保持平順起身與坐下，椅面高度、扶手與次數都依能力調整。', dosage: '研究為每週 2 次、共 6 週的個別治療；單一動作次數須個別指定。' },
      { title: '追蹤走路而非硬撐距離', instruction: '記錄何時出現腿部症狀、休息後是否緩解，以及日常可完成的步行任務。圖示短段步行是功能追蹤的代表，並非要求持續走到麻木或無力。', dosage: '研究在第 2 與第 6 個月評估；門診依症狀提早調整。' },
    ],
    suitableFor: '經診斷有腰椎狹窄與神經性跛行、病況穩定且可參與復健的成人。與研究最相近的是 60 歲以上、彎腰或坐下時症狀較少的人；周邊血管疾病、髖膝問題或其他神經病變也可能使走路受限。',
    dosage: '研究比較 6 週醫療照護、社區團體運動、手法加個別化運動。後兩組各安排 12 次；個別治療約每次 45 分鐘，並搭配居家練習。本頁只呈現方案結構，未提供自行操作的脊椎或神經鬆動術。',
    cue: '把「能完成多少日常活動」和症狀一起看；改善不等於影像上的狹窄已消失，也不以忍受麻木換取運動量。',
    regression: '由治療師改用較短的踩車段落、較高椅面與扶手；站立引發症狀時先改有支撐的活動，再重新檢查。',
    followUpLabel: '何時調整治療策略',
    followUp: '若復健期間可走距離持續縮短、腿力下降或生活功能沒有進展，回診檢查診斷與處方，討論其他治療。不要因研究顯示部分人改善，就延後處理進行性神經症狀。',
    signals: {
      green: '能穩定踩車或坐站，活動後腿部症狀回到原本程度，日常走路未變差。',
      yellow: '腿麻出現得更早、休息後恢復更慢或步態變差：先減量，聯絡治療團隊。',
      red: '新發大小便控制異常、會陰麻木或快速加重的雙腿無力，立即就醫；突發無法行走也需儘速評估。',
    },
    evidence: 'Schneider 等人納入 259 人，採三組隨機分派。手法加個別化運動在 2 個月的症狀與功能比另兩組改善較多；6 個月時平均分數與反應者比例已無組間差異。研究無法對參與者與治療者盲化，且介入包含手法與多種運動，無法分離單一動作效果，也沒有直接比較手術。',
    audience: '穩定腰椎狹窄患者及家屬；應由復健或脊椎醫療團隊規劃。',
    sources: [
      { label: 'Schneider MJ, Ammendolia C, Murphy DR, et al. Comparative Clinical Effectiveness of Nonsurgical Treatment Methods in Patients With Lumbar Spinal Stenosis: A Randomized Clinical Trial. JAMA Network Open. 2019;2(1):e186828. doi:10.1001/jamanetworkopen.2018.6828.', href: 'https://pubmed.ncbi.nlm.nih.gov/30646197/' },
      { label: 'Schneider MJ, Ammendolia C, Murphy D, et al. Comparing the Effectiveness of Nonsurgical Treatments for Lumbar Spinal Stenosis in Reducing Pain and Increasing Walking Ability. PCORI; 2019. Appendix A: Manual Therapy and Exercise Protocol.', href: 'https://www.ncbi.nlm.nih.gov/books/NBK594346/bin/22019cer587_Appendix_A.pdf' },
    ],
  },
  {
    ...COMMON,
    id: 'low-back-restore-cft-rct',
    supervision: 'professional-guidance',
    bodyRegion: '脊椎與軀幹',
    searchAliases: ['慢性下背痛', '認知功能治療', 'RESTORE', 'CFT', 'Kent'],
    selectionLabel: '慢性下背痛與動作信心',
    theme: 'teal',
    eyebrow: 'Lancet・RESTORE 492 人隨機試驗',
    title: '慢性下背痛不敢動：RESTORE 的認知功能治療',
    summary: '反覆腰痛且越來越不敢彎腰、久坐或提物時，認知功能治療把理解疼痛、分級練習與生活調整放在一起。研究評估的是受訓治療師提供的完整療程，不能縮成四個居家動作或一句「放輕鬆就好」。',
    images: schematic('low-back-restore-cft-rct', '慢性下背痛的理解疼痛、動作練習與生活活動'),
    steps: [
      { title: '理解自己的疼痛經驗', instruction: '治療師聆聽症狀、檢查動作，討論對受傷的擔心與想恢復的生活目標。這不表示疼痛是想像出來的，而是尋找可以改變的動作、活動與生活因素。', dosage: '研究首次諮詢約 60 分鐘，依個人狀況形成計畫。' },
      { title: '在指導下練習擔心的動作', instruction: '從自己會害怕或迴避的任務中選一項，例如坐站或彎腰取物；在治療師協助下調整呼吸、緊繃與動作方式，逐步增加信心。圖示為代表性任務，不要求忍痛硬做。', dosage: '研究安排個人化的每日練習，沒有所有人相同的組數、重量或彎腰角度。' },
      { title: '把活動放回生活', instruction: '依喜好與可負荷程度安排走路或其他身體活動，同時處理睡眠、壓力與生活參與的障礙。先設定可持續的任務，再與治療師討論增加活動的方式。', dosage: '研究於 12 週內最多 7 次治療；後續每次約 30–40 分鐘。' },
      { title: '建立復發時的應對計畫', instruction: '回顧哪種活動有幫助、症狀波動時如何調整，以及哪些新症狀要重新就醫。目標是改善生活功能與自主應對，不是要求永遠沒有任何痠痛。', dosage: '原方案於第 26 週再安排一次加強追蹤。' },
    ],
    suitableFor: '已排除骨折、感染、癌症等嚴重脊椎病因，腰痛超過 3 個月且至少中度影響活動的成人。新發神經缺損、急性外傷或尚未釐清的全身症狀，應先診斷再談動作練習。',
    dosage: 'RESTORE 比較一般照護、認知功能治療，以及認知功能治療加動作感測回饋。兩種治療都採個別化訪談、檢查和練習；劑量不是固定「核心訓練菜單」。本頁的坐站、取物與步行只是說明任務練習的例子。',
    cue: '把需要恢復的生活任務說清楚；不以某一種「完美姿勢」當成所有人的唯一答案，也不要把症狀全歸因於心理。',
    regression: '由治療師把任務拆小，例如減少搬物重量、縮短活動時間或增加支撐；仍保留可以成功完成的部分。',
    followUp: '若照計畫執行仍持續惡化、日常活動越來越少，或對動作的恐懼無法在治療中處理，回診重新評估診斷、負荷與需要的跨專業協助。',
    signals: {
      green: '練習時可正常呼吸，活動信心逐步提升，日常任務較容易完成。',
      yellow: '反覆出現無法恢復的症狀增加，或為完成練習明顯憋氣與僵住：與治療師調整任務。',
      red: '新發尿滯留或失禁、會陰麻木、進行性腿無力，應立即就醫；發燒合併嚴重背痛亦需儘速評估。',
    },
    evidence: 'Kent 等人在澳洲 20 間診所納入 492 人。13 週時，兩個認知功能治療組的 Roland–Morris 活動受限量表，相較一般照護平均均改善約 4.6 分；52 週的效果相近。患者與治療師未盲化，主要結果是自我回報；介入者接受專門訓練，不能推論一般網路衛教或單一放鬆動作能複製效果。',
    audience: '慢性下背痛且活動受限的成人；由熟悉認知功能治療的專業人員帶領。',
    sources: [
      { label: 'Kent P, Haines T, O’Sullivan P, et al.; RESTORE trial team. Cognitive functional therapy with or without movement sensor biofeedback versus usual care for chronic, disabling low back pain (RESTORE): a randomised, controlled, three-arm, parallel group, phase 3, clinical trial. Lancet. 2023;401(10391):1866–1877. doi:10.1016/S0140-6736(23)00441-5.', href: 'https://pubmed.ncbi.nlm.nih.gov/37146623/' },
    ],
  },
  {
    ...COMMON,
    id: 'frozen-shoulder-uk-frost-rct',
    supervision: 'medical-team',
    bodyRegion: '上肢與手部',
    searchAliases: ['五十肩', '沾黏性肩關節囊炎', '冰凍肩', 'UK FROST', 'Rangan'],
    selectionLabel: '五十肩治療選擇',
    theme: 'violet',
    eyebrow: 'Lancet・UK FROST 503 人多中心試驗',
    title: '五十肩：結構化復健與手術如何選擇',
    summary: '五十肩的伸展強度要配合疼痛與僵硬程度。UK FROST 比較的是結構化復健加類固醇注射與兩種手術策略；12 個月沒有一組達到研究預設的臨床優勢，不代表在家拉筋等於全部治療。',
    images: schematic('frozen-shoulder-uk-frost-rct', '五十肩的診斷、輔助活動、漸進伸展與功能追蹤'),
    steps: [
      { title: '先確認五十肩與治療選項', instruction: '由醫師確認肩關節主動及被動活動受限，排除外傷、關節炎與其他原因，再共同討論復健、注射或手術。注射與手術都是醫療處置，不是圖解可自行執行的步驟。', dosage: '研究納入成人單側原發性五十肩，外旋被動活動明顯受限。' },
      { title: '疼痛期採輔助活動', instruction: '由治療師選擇可容忍的主動或自行輔助活動。圖以桌面支撐前滑代表輔助抬手；身體平順移動，不借旁人猛推到極限。', dosage: '居家頻率與次數個別指定；本圖未重現完整研究手冊。' },
      { title: '依僵硬程度調整伸展', instruction: '當疼痛可控制，再由治療師安排適當方向的伸展與肌力活動。圖以輕柔外旋作代表；伸展終點取決於當下反應，不以「撕開沾黏」作居家目標。', dosage: '原試驗結構化復健最多 12 次、在 12 週內完成；不是固定每日硬拉次數。' },
      { title: '檢查生活功能是否進步', instruction: '用穿衣、梳頭或伸手拿物等任務記錄改變，再調整居家練習。若復健無法改善需求，與醫師重談治療，不必因平均研究結果而排除適合自己的選項。', dosage: '原試驗主要結果在 12 個月評估；日常治療依反應安排複診。' },
    ],
    suitableFor: '已由醫師診斷原發性五十肩、需要了解保守治療與手術取捨的成人。外傷後立即抬不起手、術後肩關節或已知大範圍肌腱撕裂，不能直接套用此研究。',
    dosage: '非手術組包含結構化物理治療與關節內類固醇注射；手術組分別為麻醉下鬆動或關節鏡關節囊鬆解，亦有後續復健。家庭動作、持續時間與次數依疼痛主導或僵硬主導的狀態調整；本頁未提供注射處方。',
    cue: '疼痛很強時先減少刺激，僵硬為主時才逐步增加可容忍的活動範圍；每次治療要連結到實際穿衣、睡眠與抬手需求。',
    regression: '改用前臂支撐與較小角度，降低伸展力道；若睡眠與日常疼痛加重，先回到治療師確認過的舒服動作。',
    followUp: '若依計畫復健後仍難以完成重要生活任務，回診共同評估下一步。合併糖尿病者，任何注射與負荷調整應由醫療團隊考慮整體病況。',
    signals: {
      green: '可控制的牽拉感，結束後沒有持續加重的夜間痛，日常活動漸進改善。',
      yellow: '拉完更痛、夜間睡眠變差或隔日抬手更困難：減少伸展，回報治療師。',
      red: '發燒合併肩部紅熱腫、外傷後變形或突然無法抬手，應儘速就醫；肩痛合併胸悶呼吸困難需緊急評估。',
    },
    evidence: 'Rangan 等人在英國 35 間醫院隨機分派 503 人。12 個月的 Oxford Shoulder Score 組間平均差異，均未達預設臨床重要門檻；關節鏡組與麻醉鬆動組分別通報 8 與 2 件嚴重不良事件。試驗未盲化、聚焦轉介至醫院的患者，且比較複合策略，不能分離運動或注射的獨立效果，也不是證明三種治療完全等效。',
    audience: '五十肩患者及家屬；動作由治療師指導，醫療選擇由醫師與患者共同決定。',
    sources: [
      { label: 'Rangan A, Brealey SD, Keding A, et al.; UK FROST Study Group. Management of adults with primary frozen shoulder in secondary care (UK FROST): a multicentre, pragmatic, three-arm, superiority randomised clinical trial. Lancet. 2020;396(10256):977–989. doi:10.1016/S0140-6736(20)31965-6.', href: 'https://pubmed.ncbi.nlm.nih.gov/33010843/' },
      { label: 'South Tees Hospitals NHS Foundation Trust. Physiotherapist booklet: frozen shoulder. UK FROST implementation resource; accessed 2026-09-28.', href: 'https://www.southtees.nhs.uk/staff-area/resources/physiotherapist-booklet-frozen-shoulder/' },
    ],
  },
  {
    ...COMMON,
    id: 'subacromial-specific-exercise-rct',
    supervision: 'professional-guidance',
    bodyRegion: '上肢與手部',
    searchAliases: ['肩峰下疼痛', '夾擠症候群', '旋轉肌袖', 'Holmgren', 'subacromial'],
    selectionLabel: '持續肩峰下疼痛',
    theme: 'green',
    eyebrow: 'BMJ・102 人隨機試驗',
    title: '肩峰下疼痛：旋轉肌袖與肩胛肌的漸進負荷',
    summary: '抬手痛很久，不代表只能休息或手術。這項研究在已等候手術的患者中，比較有進階負荷的肩部訓練與不加重的活動操；重點是治療師調整阻力與症狀，而不是所有人立刻做相同重量。',
    images: schematic('subacromial-specific-exercise-rct', '旋轉肌袖離心負荷、肩胛肌力與肩後側伸展'),
    steps: [
      { title: '先建立可承受的起點', instruction: '確認是持續肩峰下疼痛，並檢查抬手、肩袖力量與其他肩部疾病。研究兩組都先接受注射與衛教；不能把其結果解讀為任何新發肩痛都適合直接加重。', dosage: '研究介入 12 週；參與者症狀超過 6 個月且先前保守治療未奏效。' },
      { title: '控制肩袖的放回動作', instruction: '研究包含肩袖離心訓練。圖以肩外旋呈現負荷控制概念；由治療師選姿勢、阻力與活動角度，不甩動、不用身體旋轉代償。', dosage: '原方案肌力動作每次 3 組、每組 15 次；前 8 週每天 2 次，後 4 週每天 1 次。這是研究量，不是初次嘗試量。' },
      { title: '加入肩胛肌力', instruction: '研究同時訓練肩胛穩定肌，包含向心與離心出力。圖用拉帶划船作代表性示意，緩慢拉回與放回，保持頸部舒適；不能只用一項動作代表整套方案。', dosage: '使用與整體肌力方案相同的研究頻率，負荷於回診時逐步調整。' },
      { title: '配合需要的活動度練習', instruction: '研究含肩後側伸展，並視需要加入專業手法。圖示橫跨胸前的輕柔伸展是概念示意；治療師須先確定方向適合，不以壓迫痛或麻感追求幅度。', dosage: '原方案肩後側伸展每次 30–60 秒、3 次；頻率隨研究階段調整，實際執行可減量。' },
    ],
    suitableFor: '已排除五十肩、肩關節不穩定與頸椎轉移痛，經評估屬持續肩峰下疼痛的成人。研究主要為 30–65 歲、先前保守治療失敗且等候肩峰下減壓手術者，不能直接推論到所有肩袖撕裂或急性傷害。',
    dosage: '這是密集且受監督的 12 週方案，包含 5 項肌力、1 項伸展、回診調整與必要手法。本頁四步是研究邏輯摘要；在未評估前不建議直接照完整研究總量執行。',
    cue: '原研究容許運動中有限疼痛，但不是越痛越有效；每次負荷應能保持控制，並在下次訓練前回到原本症狀。',
    regression: '由治療師減少阻力、幅度或總量，增加手肘支撐；若即使輕負荷仍刺痛或突然失力，先重新檢查。',
    followUp: '若規律執行與調整後仍無功能進步，回診確認診斷與後續選項。研究中的手術選擇差異不等於所有肩痛都不需手術。',
    signals: {
      green: '可維持動作控制，訓練後症狀於下次練習前恢復。',
      yellow: '原研究疼痛上限為 5/10，且須於下次練習前回復；超過或未恢復就減量並聯絡治療師，不把此門檻套用到所有疾病。',
      red: '突發明顯失力、外傷後抬不起手、持續手臂麻木或紅熱腫與發燒：停止並就醫。',
    },
    evidence: 'Holmgren 等人隨機納入 102 人，97 人完成 12 週並納入分析。特定訓練組的 Constant–Murley 改善比對照多 15 分，選擇手術者為 20% 對 63%。但對照組沒有進階負荷，兩組都接受注射，特定組另含手法；單中心且追蹤短，不能證明離心本身優於所有其他復健，也不能據此估算長期避免手術的機率。',
    audience: '經評估的持續肩峰下疼痛患者；阻力與劑量需專業指導。',
    sources: [
      { label: 'Holmgren T, Björnsson Hallgren H, Öberg B, Adolfsson L, Johansson K. Effect of specific exercise strategy on need for surgery in patients with subacromial impingement syndrome: randomised controlled study. BMJ. 2012;344:e787. doi:10.1136/bmj.e787.', href: 'https://pubmed.ncbi.nlm.nih.gov/22349588/' },
    ],
  },
  {
    ...COMMON,
    id: 'acl-kanon-rehabilitation-rct',
    supervision: 'medical-team',
    bodyRegion: '髖膝與大腿',
    searchAliases: ['前十字韌帶', 'ACL', 'KANON', 'Frobell', '延後重建'],
    selectionLabel: 'ACL 受傷後治療選擇',
    theme: 'orange',
    eyebrow: 'NEJM・KANON 121 人隨機試驗',
    title: '前十字韌帶斷裂：復健優先與重建的共同決策',
    summary: '前十字韌帶受傷後，復健是兩種治療策略共同的一部分。KANON 比較早期重建加復健，以及先復健、必要時再重建；研究支持討論選擇，不是用幾個動作宣告韌帶已癒合或能直接回場。',
    images: schematic('acl-kanon-rehabilitation-rct', '前十字韌帶受傷後的共同決策與分階段復健'),
    steps: [
      { title: '確認合併損傷與運動需求', instruction: '醫療團隊評估韌帶、半月板與軟骨狀況，了解工作及轉向運動需求。先討論早期重建或復健優先的理由，並預先約定不穩定時如何再評估。', dosage: '研究追蹤的 121 人為年輕、活躍成人；個別手術時機由醫師共同決策。' },
      { title: '恢復可控制的膝活動', instruction: '在醫囑允許的範圍內練習膝伸屈與大腿出力。圖以坐姿輕柔伸膝表示早期功能重建方向，並非 KANON 全部動作；合併修補手術者依特定限制執行。', dosage: '次數、角度與負重個別指定；不以固定受傷天數自行進階。' },
      { title: '漸進肌力與站立控制', instruction: '治療師依腫脹、力量與動作品質調整訓練。圖以有支撐的坐站代表下肢出力，之後是否加入單腳、跳躍或方向改變，需另行評估。', dosage: '研究採結構化復健；組數與回場時程依功能、合併損傷及治療策略決定。' },
      { title: '依不穩定與目標重新決策', instruction: '追蹤是否反覆軟腳、能否完成日常及運動任務；若仍不穩或無法達到需求，重新討論重建。平地走路不痛不等於已能切入、急停或對抗。', dosage: '主要研究結果為 2 年追蹤；回場時間需醫療與功能評估。' },
    ],
    suitableFor: '已確診 ACL 受傷、想了解初始治療選項的成人。研究不能涵蓋所有職業選手、多韌帶傷害、需特別保護的半月板修補或其他複雜膝傷；這些情況需不同計畫。',
    dosage: '兩組都接受結構化復健；「復健優先」也包含需要時接受延後重建。四步是協助與團隊討論的代表性流程，並非以文章取代完整 ACL 處方或手術後限制。',
    cue: '先恢復可用的膝功能，持續記錄腫脹與軟腳；用完整的生活及運動需求判斷進展，不只看疼痛分數。',
    regression: '若負重動作造成腫脹或失控，由治療師退回有支撐、較小幅度的活動；不要自行挑戰單腳跳測試。',
    followUp: '反覆膝軟腳、活動後腫脹或功能停滯，應提早回診，重新討論穩定性與治療策略。先復健不表示之後不能手術，也不應把延後重建視為失敗。',
    signals: {
      green: '經允許的活動能保持穩定，沒有新增腫脹或軟腳。',
      yellow: '反覆不穩、訓練後腫脹增加或伸直變差：停止進階，回報團隊。',
      red: '膝蓋突然卡住無法伸直、急劇腫脹或新外傷無法承重，儘速就醫；小腿腫痛合併呼吸困難需緊急處理。',
    },
    evidence: 'Frobell 等人的 KANON 試驗中，121 人接受兩種策略；2 年 KOOS4 改善未見顯著組間差異。先復健組 59 人中有 23 人仍接受延後重建，因此結果不是「不開刀和開刀一樣」的直接比較。樣本有限、治療無法盲化，且主要為患者回報功能；不能推論韌帶結構癒合、長期關節炎預防或所有回場需求。',
    audience: 'ACL 患者及家屬；必須由骨科與復健團隊共同管理。',
    sources: [
      { label: 'Frobell RB, Roos EM, Roos HP, Ranstam J, Lohmander LS. A randomized trial of treatment for acute anterior cruciate ligament tears. New England Journal of Medicine. 2010;363(4):331–342. doi:10.1056/NEJMoa0907797.', href: 'https://pubmed.ncbi.nlm.nih.gov/20660401/' },
    ],
  },
  {
    ...COMMON,
    id: 'young-meniscus-dream-rct',
    supervision: 'medical-team',
    bodyRegion: '髖膝與大腿',
    searchAliases: ['半月板撕裂', 'DREAM', '年輕成人膝傷', 'Skou', 'meniscal tear'],
    selectionLabel: '年輕成人半月板',
    theme: 'blue',
    eyebrow: 'NEJM Evidence・DREAM 121 人試驗',
    title: '年輕成人半月板撕裂：先復健的研究與限制',
    summary: 'MRI 顯示半月板撕裂，仍需要結合症狀、卡住與活動需求決定治療。DREAM 研究支持把監督式運動與衛教納入選項，但並非所有撕裂都適合等待，也不能把運動後較不痛當成撕裂已接回。',
    images: schematic('young-meniscus-dream-rct', '半月板撕裂的醫療評估、暖身、肌力和平衡追蹤'),
    steps: [
      { title: '先確認能否嘗試復健', instruction: '由骨科確認影像、膝蓋是否真正卡住及合併損傷，討論手術與復健的利弊。若已接受半月板縫合，應遵守術後負重和彎曲限制，不能照非手術方案做。', dosage: '原研究納入 18–40 歲、MRI 證實且被評估可接受手術的患者。' },
      { title: '用可控制的活動暖身', instruction: '方案包含漸進神經肌肉與肌力訓練。圖示固定式腳踏車代表低衝擊暖身選項；若轉動引發卡住或腫脹，先停止並由治療師調整。', dosage: '研究監督課程每週 2 次、共 12 週，每次整體訓練約 60–90 分鐘。' },
      { title: '練習膝髖協調出力', instruction: '治療師依能力選擇肌力與功能動作。圖以控制式坐站作示意，先在可容忍深度起身和坐回，避免為完成次數而突然扭轉膝蓋。', dosage: '個別動作阻力、組數與深度由治療師指定；不能把整堂課時間當成單一動作時長。' },
      { title: '追蹤平衡與症狀反應', instruction: '在確認安全後練習站立控制，並持續記錄腫脹、卡住及生活功能。若運動與衛教無法滿足需求，研究方案仍保留後續手術選項。', dosage: '研究有初期及末期衛教，主要結果追蹤至 12 個月；提早惡化者應先回診。' },
    ],
    suitableFor: '18–40 歲且經醫師評估可選擇初始復健的半月板撕裂患者。不能套用到真正鎖膝、需儘速處理的移位撕裂、合併重大韌帶傷害或已有縫合保護限制的人。',
    dosage: 'DREAM 比較早期半月板手術與 12 週監督運動加衛教、必要時延後手術。訓練包含神經肌肉控制及肌力，並非只有休息、抬腿或單項運動。圖中的暖身與坐站為代表性整理，實際動作須依完整評估選擇。',
    cue: '把卡住、腫脹與功能需求說清楚；能走路不等於可以立即深蹲、跳躍或快速轉向。',
    regression: '由治療師縮小負重深度、減少阻力並增加支撐；若仍出現機械性卡住，暫停該動作並回診。',
    followUp: '若復健後持續卡住、反覆腫脹或生活功能不進步，重新討論診斷與手術選項。研究的平均結果不能決定個別撕裂是否適合修補。',
    signals: {
      green: '動作順暢、膝部沒有卡住，訓練後沒有新增腫脹。',
      yellow: '隔天腫脹或疼痛增加、反覆卡頓：減量並聯絡治療團隊。',
      red: '膝蓋真正卡住無法伸直、突然無法承重或紅熱腫伴發燒，應儘速就醫。',
    },
    evidence: 'Skou 等人於 7 間丹麥醫院納入 121 人，107 人完成 12 個月追蹤。KOOS4 改善的調整後組間差為 5.4 分，95% 信賴區間 −0.7 至 11.4，未證實早期手術優越；運動組 26% 轉接受手術。樣本較小、非盲化且區間仍容許一定差異，因此不能宣稱完全等效，也不能據此判定特定撕裂型態的最佳治療。',
    audience: '經骨科評估的年輕成人半月板撕裂患者；由醫療與復健團隊規劃。',
    sources: [
      { label: 'Skou ST, Hölmich P, Lind M, et al. Early Surgery or Exercise and Education for Meniscal Tears in Young Adults. NEJM Evidence. 2022;1(2):EVIDoa2100038. doi:10.1056/EVIDoa2100038.', href: 'https://pubmed.ncbi.nlm.nih.gov/38319181/' },
      { label: 'Skou ST, Lind M, Hölmich P, et al. Study protocol for a randomised controlled trial of meniscal surgery compared with exercise and patient education for treatment of meniscal tears in young adults. BMJ Open. 2017;7(8):e017436. doi:10.1136/bmjopen-2017-017436.', href: 'https://doi.org/10.1136/bmjopen-2017-017436' },
    ],
  },
  {
    ...COMMON,
    id: 'adolescent-pfp-school-rct',
    supervision: 'professional-guidance',
    bodyRegion: '髖膝與大腿',
    searchAliases: ['青少年膝前痛', '髕股疼痛', '學生', 'Rathleff', 'patellofemoral'],
    selectionLabel: '青少年膝前痛',
    theme: 'violet',
    eyebrow: 'BJSM・121 名青少年群集隨機試驗',
    title: '學生膝前痛：把肌力練習與疼痛教育放進日常',
    summary: '上下樓梯、跑跳或久坐時膝前疼痛，應先確認原因。這項校園研究發現，教育再加監督運動比單純教育更有機會自覺恢復；實際可持續的練習安排，比一次做很多更值得和治療師討論。',
    images: schematic('adolescent-pfp-school-rct', '青少年髕股疼痛的衛教、膝肌力、髖外展與坐站'),
    steps: [
      { title: '安排能持續的學校與居家計畫', instruction: '學生、家長與治療師一起了解疼痛、調整運動負荷並設定目標。把體育課、球隊與復健總量一起考量，避免把復健額外堆在已過量的活動上。', dosage: '原研究監督運動每週 3 次、共 3 個月，另有居家練習指導。' },
      { title: '個別化膝伸肌訓練', instruction: '由治療師依疼痛與能力選擇坐姿伸膝或負重練習。圖示坐姿伸膝代表一個選項，平順抬起及放回，不能為了完成組數而猛踢。', dosage: '研究方案的次數、阻力與角度由治療師決定，沒有全體相同的固定組數。' },
      { title: '加上髖部肌力', instruction: '研究手冊包含側躺抬腿等髖外展動作。圖示側躺抬腿時讓骨盆穩定，在可控制範圍抬起與放回；是否使用彈力帶要依訓練表現調整。', dosage: '依監督課程與居家處方安排；先保持動作品質，再提高難度。' },
      { title: '把力量用在坐站與階梯', instruction: '依能力選擇坐站、單階上踏或樓梯活動；先有穩定支撐與較低難度。圖以坐站呈現功能訓練，不要求一開始就做單腳蹲。', dosage: '原方案功能訓練每週 3 次；具體階級與次數由治療師調整。' },
    ],
    suitableFor: '經評估為髕股疼痛的 15–19 歲青少年，願意在學校或居家持續練習。膝部外傷、反覆髕骨脫位、明顯積水或卡住，應先做不同診斷評估，不能只當作一般成長痛。',
    dosage: 'Rathleff 研究是教育加 3 個月多模式治療，包含髖膝肌力、功能訓練與視需要的其他措施；居家內容另行教學。本頁選四個核心環節說明，並非把完整方案縮成四個固定動作。',
    cue: '選能做得穩、隔天不影響上學與走路的難度；練習出席與生活安排是治療的一部分，不用以忍痛證明有努力。',
    regression: '由治療師調低階梯、提高椅面或減少阻力；必要時先減少引發症狀的跑跳，保留能承受的活動。',
    followUp: '若膝痛持續妨礙上課、上下樓或運動，請家長協助安排複診，檢查診斷、實際負荷與計畫可行性；不要只要求學生增加練習次數。',
    signals: {
      green: '動作品質穩定，練習後日常走路與上樓沒有變差。',
      yellow: '隔天膝前痛增加、跛行或因痛缺課：先減量，與家長及治療師討論。',
      red: '明顯膝腫、真正卡住、發燒合併紅熱，或外傷後無法承重：停止練習並就醫。',
    },
    evidence: '121 名 15–19 歲青少年依群集分派為教育，或教育加運動。12 個月自覺恢復的勝算比為 1.73，95% 信賴區間 1.02–2.93，24 個月仍有差異。主要結果屬自我回報、無法完全盲化；較高出席與恢復的關聯不代表單純加量即可改善，也不能直接推論到年紀更小的兒童或單一髖肌動作。',
    audience: '青少年、家長與學校運動指導者；確診及負荷調整需專業協助。',
    sources: [
      { label: 'Rathleff MS, Roos EM, Olesen JL, Rasmussen S. Exercise during school hours when added to patient education improves outcome for 2 years in adolescent patellofemoral pain: a cluster randomised trial. British Journal of Sports Medicine. 2015;49(6):406–412. doi:10.1136/bjsports-2014-093929.', href: 'https://pubmed.ncbi.nlm.nih.gov/25388552/' },
      { label: 'Rathleff MS, Roos EM, Olesen JL, Rasmussen S. Early intervention for adolescents with Patellofemoral Pain Syndrome—a pragmatic cluster randomised controlled trial. BMC Musculoskeletal Disorders. 2012;13:9. doi:10.1186/1471-2474-13-9. Study protocol.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3328242/' },
    ],
  },
  {
    ...COMMON,
    id: 'ankle-recurrence-balance-rct',
    supervision: 'professional-guidance',
    bodyRegion: '足踝',
    searchAliases: ['腳踝反覆扭傷', '本體感覺', '平衡板', 'Hupperets', '2BFit'],
    selectionLabel: '踝扭傷再發預防',
    theme: 'teal',
    eyebrow: 'BMJ・522 人隨機試驗',
    title: '腳踝扭傷恢復後：8 週平衡訓練降低再扭傷',
    summary: '回到球場後仍可能再次扭傷。這項研究在原有照護之外加入 8 週漸進本體感覺訓練，一年內自述再扭傷較少；它是恢復後的預防策略，並非剛受傷腫痛時就站上搖晃平衡板。',
    images: schematic('ankle-recurrence-balance-rct', '踝扭傷恢復後的站立控制與漸進平衡訓練'),
    steps: [
      { title: '先完成急性傷害評估與照護', instruction: '確認已完成原有治療並可重新參與運動。若仍痛到不能踩地、骨頭壓痛或明顯腫脹，先回診；預防計畫不能取代骨折或其他踝傷的判斷。', dosage: '研究納入近 2 個月有外側踝扭傷的運動者，訓練安排在原照護與回到運動之後。' },
      { title: '在穩固地面練習控制', instruction: '圖以扶穩單腳站呈現入門平衡概念。先確定支撐物不會移動，再由治療師選擇適合的站姿；扶手是安全調整，不是研究獨立驗證的新處方。', dosage: '本頁不指定單腳站秒數；由目前平衡與症狀決定。' },
      { title: '適應後再增加平衡挑戰', instruction: '原研究提供平衡板與教學，逐步增加難度。確認平地控制良好後，才在安全環境使用合適器材；圖示器材不代表需要閉眼、拋球或同時加多種挑戰。', dosage: '原研究每週 3 次、最多每次 30 分鐘，持續 8 週；不是一開始就做滿 30 分鐘。' },
      { title: '接回運動與記錄再扭傷', instruction: '在完成平衡練習之外，與教練討論跑跳及變向負荷。若又扭到，記錄時間與情境並重新評估；不要用「多練就會穩」忽略反覆失控。', dosage: '研究追蹤 1 年；回場能力須另行評估，不以完成 8 週作唯一標準。' },
    ],
    suitableFor: '踝扭傷已接受適當照護、可回到運動且需要降低再發風險的人。研究包含 12–70 歲運動者，但年齡跨度不表示每種腳踝問題都適用；高跌倒風險、持續不穩或感覺異常者需額外評估。',
    dosage: '原方案是在通常照護之上額外加入居家本體感覺訓練，附器材與教學資訊；不能用網頁圖取代學習完整動作。此頁的支撐站立是代表性安全調整，不能宣稱與原方案有相同防傷幅度。',
    cue: '先站得穩，再提高難度；把平衡練習與球場總負荷一起規劃，不把搖晃越大當成效果越好。',
    regression: '回到平地、雙腳或扶手支撐；若仍不穩或疼痛，停止器材練習並請治療師調整。',
    followUp: '持續有腳踝要翻掉的感覺、反覆扭傷或運動後腫脹，應評估韌帶、肌腱、軟骨及控制能力，討論是否需要其他保護策略。',
    signals: {
      green: '可隨時扶穩，練習時無翻腳或尖銳痛，之後走路未變差。',
      yellow: '為保持平衡頻繁跳腳、踝部腫脹或疼痛增加：降低難度，先回到支撐練習。',
      red: '新扭傷後無法承重、明顯變形或骨部壓痛、足部麻木或冰冷，停止並儘速就醫。',
    },
    evidence: 'Hupperets 等人將 522 人隨機分為通常照護，或另加 8 週居家訓練。一年內自述再扭傷為 22% 對 33%，估計相對風險 0.63，95% 信賴區間 0.45–0.88。主要結果依自我回報，居家依從性不一，兩組原有照護也不同；結果支持附加預防方案，不能推論單一平衡動作、急性傷害治癒或所有人都能避免再發。',
    audience: '已恢復運動的踝扭傷者；開始與進階前宜由治療師確認。',
    sources: [
      { label: 'Hupperets MDW, Verhagen EALM, van Mechelen W. Effect of unsupervised home based proprioceptive training on recurrences of ankle sprain: randomised controlled trial. BMJ. 2009;339:b2684. doi:10.1136/bmj.b2684.', href: 'https://pubmed.ncbi.nlm.nih.gov/19589822/' },
    ],
  },
  {
    ...COMMON,
    id: 'nordic-hamstring-prevention-rct',
    supervision: 'professional-guidance',
    bodyRegion: '髖膝與大腿',
    searchAliases: ['Nordic', '北歐腿後肌', '腿後肌拉傷預防', 'Petersen', 'hamstring prevention'],
    selectionLabel: '足球腿後肌防傷',
    theme: 'green',
    eyebrow: 'AJSM・942 名球員群集隨機試驗',
    title: 'Nordic 腿後肌訓練：漸進導入足球防傷',
    summary: 'Nordic 腿後肌離心訓練在男子足球研究中降低了拉傷發生率。它的負荷不輕，需要教練或治療師確認固定方式並漸進安排；不能在剛拉傷時自行用大角度下放，也不是做一次就有防傷效果。',
    images: schematic('nordic-hamstring-prevention-rct', 'Nordic 腿後肌訓練的安全固定、前傾下放與漸進安排'),
    steps: [
      { title: '確認適合加入防傷訓練', instruction: '由教練或治療師檢查近期拉傷、膝部跪姿耐受與既有訓練量。這篇談可正常訓練者的預防；有急性腿後側痛的人需先走傷害評估與復健流程。', dosage: '原研究在例行足球訓練之外加入 10 週漸進訓練。' },
      { title: '建立穩定跪姿與固定', instruction: '雙膝放在合適軟墊上，踝部由可靠夥伴或經確認的設備固定，軀幹與大腿保持可控制的位置。先檢查前方接手空間，避免器材滑脫。', dosage: '首次由專業人員示範及確認；圖示為代表性設置，非完整器材操作說明。' },
      { title: '控制前傾並安全接手', instruction: '在能控制的範圍內緩慢前傾，用腿後肌抵抗下放；接近失去控制前以雙手承接。初學者不追求下降到底，協助或縮小幅度需由指導者安排。', dosage: '下放幅度、每週組數與次數由指導者依完整訓練計畫及個人恢復調整。' },
      { title: '把進階與賽季維持排進行事曆', instruction: '配合球隊賽程與恢復情況逐步增加負荷，注意隔日痠痛是否影響跑步。不能為補課一次集中做大量離心訓練，也不能只在比賽前臨時加入。', dosage: '原研究完成 10 週進階後，在球季每週維持 1 次。' },
    ],
    suitableFor: '可正常參與足球訓練、需要腿後肌拉傷預防的球員。直接證據來自男子職業與業餘足球；女性、青少年及其他運動項目的劑量與效果不能由此單篇直接推定。',
    dosage: 'Petersen 試驗採 10 週漸進離心訓練，再接每週球季維持，與例行訓練比較。本頁呈現 Nordic 的動作概念與負荷安排；實際每週組數須配合完整方案、賽程及個人恢復，由專業指導者安排。',
    cue: '固定可靠、下放可控、前方能安全接手；品質下降就結束該組，不要把突然跌下去視為有效的一次。',
    regression: '在指導下縮小前傾幅度或改用輔助；若跪姿痛、無法安全承接或有急性拉傷疑慮，暫不做 Nordic。',
    followUp: '若反覆出現腿後側局部疼痛或跑步功能下降，請治療師檢查是否已受傷；防傷計畫不應掩蓋持續疼痛，也不取代回場評估。',
    signals: {
      green: '兩側肌肉出力感可控制，訓練後活動正常，痠感未妨礙下次跑步。',
      yellow: '痠痛影響步態、跑速或下次練習，或動作後半段失控：降低量並調整排程。',
      red: '突然撕裂感、局部劇痛或瘀青、明顯失力與跛行：立刻停止，安排傷害評估。',
    },
    evidence: 'Petersen 等人以球隊分派 50 隊、942 名男子球員。完整球季觀察到介入組 15 件、對照組 52 件急性腿後肌傷害；整體調整後傷害率比 0.293，95% 信賴區間 0.150–0.572。群集試驗具有實務價值，但無法盲化且限男子足球；它評估的是整季安排，不能解讀為每個人都有固定比例保護或用來治療尚未癒合的拉傷。',
    audience: '男子足球球員、教練與治療師；初始學習與負荷進階需要指導。',
    sources: [
      { label: 'Petersen J, Thorborg K, Nielsen MB, Budtz-Jørgensen E, Hölmich P. Preventive effect of eccentric training on acute hamstring injuries in men’s soccer: a cluster-randomized controlled trial. American Journal of Sports Medicine. 2011;39(11):2296–2303. doi:10.1177/0363546511419277.', href: 'https://pubmed.ncbi.nlm.nih.gov/21825112/' },
    ],
  },
  {
    ...COMMON,
    id: 'football-11plus-youth-rct',
    supervision: 'professional-guidance',
    bodyRegion: '全身與神經',
    searchAliases: ['足球暖身', 'FIFA 11+', '女子足球', 'Soligard', '神經肌肉暖身'],
    selectionLabel: '青少年足球暖身',
    theme: 'orange',
    eyebrow: 'BMJ・1,892 名球員群集隨機試驗',
    title: '青少年女子足球：把肌力與落地控制放進暖身',
    summary: '完整暖身不只有慢跑。這項挪威研究把跑步、肌力、平衡與跳躍整合進約 20 分鐘流程，整體和嚴重傷害較少；但主要的下肢傷害結果未達統計顯著，不能宣稱每一種傷害都能預防。',
    images: schematic('football-11plus-youth-rct', '青少年足球的低速跑、肌力平衡、落地與變向暖身'),
    steps: [
      { title: '先用低速跑與動態動作暖身', instruction: '在教練設置的路線中，以低速跑搭配髖部活動及可控制的動態動作，和隊友保持安全距離。研究第一部分有多項跑步動作，本圖只代表開場階段。', dosage: '原方案第一部分約 8 分鐘；由教練帶領完整流程。' },
      { title: '加入肌力與單腳平衡', instruction: '研究中段包含軀幹支撐、腿後肌、單腳平衡及蹲等訓練，各有進階層級。圖以單腳持球代表其中一項，並非只做這一項即可取代整個中段。', dosage: '中段肌力、平衡與跳躍合計約 10 分鐘；每項依選定層級完成。' },
      { title: '練習可控制的起跳與落地', instruction: '依程度選擇跳躍練習，注意落地能穩定承接、膝與足的方向可控制。教練先看動作品質，再增加難度；不必為了同步隊友而勉強跳高。', dosage: '屬前述 10 分鐘中段的一部分，不是另外加 10 分鐘；先用合適層級。' },
      { title: '最後才提高速度與變向', instruction: '以較快跑步接回足球需要的動作，逐步練習加速與方向變化。若已有傷痛或不穩，教練應調整內容，而非要求所有人完成相同強度。', dosage: '原方案末段約 2 分鐘；訓練前做全套，比賽前使用跑步部分。' },
    ],
    suitableFor: '有教練帶領、可正常參與訓練的青少年女子足球隊。直接研究對象為 13–17 歲；目前急性受傷、術後或有未釐清運動症狀者，需要個別處理。',
    dosage: '研究完整暖身約 20 分鐘，分為 8 分鐘跑步、10 分鐘肌力平衡跳躍，以及 2 分鐘快速跑。教練先接受教學，再於球季訓練前規律實施。本頁為四個環節摘要，未列出全套動作與所有層級，不能取代完整教練教材。',
    cue: '以能穩定控制的層級反覆練習，讓暖身成為例行訓練的一部分；不要只在比賽或受傷後才臨時採用。',
    regression: '教練降低跳躍高度、跑速或動作層級；疼痛或不穩時改成可承受的暖身並安排評估。',
    followUp: '若球員持續出現膝踝疼痛、落地失控或反覆扭傷，應評估個別傷害與整體訓練負荷；團體暖身不能替代一對一復健或回場判斷。',
    signals: {
      green: '完成暖身後動作流暢，無新發疼痛，能平穩承接落地。',
      yellow: '落地反覆失控、痠痛影響跑步或疲勞累積：降低層級，回報教練。',
      red: '急性扭轉後腫脹、突然撕裂感、無法承重，或運動時胸痛、暈厥：停止並依症狀儘速就醫。',
    },
    evidence: 'Soligard 等人分析 125 個俱樂部、1,892 名球員的一個球季。主要下肢傷害率比為 0.71，95% 信賴區間 0.49–1.03，未達統計顯著；次要的整體、過度使用與嚴重傷害風險較低。群集試驗不易盲化、執行程度各異，且多個次要結果需審慎解讀；不能推論每一類傷害、男性球員或單一暖身動作都有相同效果。',
    audience: '青少年女子足球球員、教練與家長；由熟悉完整方案的專業人員帶領。',
    sources: [
      { label: 'Soligard T, Myklebust G, Steffen K, et al. Comprehensive warm-up programme to prevent injuries in young female footballers: cluster randomised controlled trial. BMJ. 2008;337:a2469. doi:10.1136/bmj.a2469.', href: 'https://pubmed.ncbi.nlm.nih.gov/19066253/' },
    ],
  },
]
