import type { ExerciseGuideImage, ExerciseGuideModule } from './exercise-guides'

function trialImage(id: string, alt: string): ExerciseGuideImage {
  return {
    src: `/images/exercise-guides/${id}.svg`,
    width: 1200,
    height: 900,
    step: '研究方案圖解',
    alt,
    caption: '本站原創研究方案示意，呈現代表性訓練與評估流程；不是論文原圖，也不是可直接照做的個人處方。',
  }
}

const REVIEW = {
  kind: 'condition',
  evidenceKind: 'rct',
  reviewStatus: 'approved',
  approvalDate: '2026-09-28',
  publishedDate: '2026-09-28',
  modifiedDate: '2026-09-28',
  bodyRegion: '全身與神經',
} as const

export const CURATED_NEURO_GUIDES: ExerciseGuideModule[] = [
  {
    ...REVIEW,
    id: 'life-mobility-disability-rct',
    selectionLabel: '高齡行走能力維持',
    searchAliases: ['LIFE', '老人運動', '行動失能', '高齡肌力', '走路耐力'],
    supervision: 'professional-guidance',
    theme: 'green',
    eyebrow: '2014 LIFE 多中心隨機試驗',
    title: '高齡行走能力：LIFE 的步行、肌力與平衡組合',
    summary: '對還能走完 400 公尺、但已有下肢功能限制的高齡者，長期且有支持的運動計畫，比健康教育更能減少日後喪失這項能力的機會。研究支持整套方案，不是單靠散步或某一個動作。',
    images: [trialImage('life-mobility-disability-rct', 'LIFE 研究的步行評估、漸進步行、下肢肌力及平衡活動四格示意')],
    steps: [
      { title: '先評估行走能力', instruction: '研究先確認受試者能完成 400 公尺步行，並檢查下肢功能與運動安全性。這是團隊的評估項目，不是要求體弱者獨自測極限。', dosage: '開始前個別評估；依功能安排起點。' },
      { title: '漸進累積步行', instruction: '在安全場地以可持續的速度行走，從較輕強度逐步增加。研究的目標強度約為稍微吃力，並非快走競賽。', dosage: '研究步行目標每週 150 分鐘，單日逐步朝 30 分鐘進展。' },
      { title: '加入下肢肌力', instruction: '方案使用腳踝負重訓練下肢；圖示只是負重活動的代表。重量、動作與支撐方式須由指導者依力量與平衡選擇。', dosage: '研究目標約 10 分鐘；各肌力動作 2 組、每組 10 次。' },
      { title: '保留平衡與柔軟度', instruction: '課程另有平衡及大肌群柔軟度活動，並用居家記錄維持規律。不能因步行量達標，就省略原本需要的防跌支持。', dosage: '平衡目標約 10 分鐘；中心每週 2 次，另有居家活動 3–4 次。' },
    ],
    suitableFor: '研究納入 1,635 名 70–89 歲、活動量少、SPPB 下肢功能分數不高於 9 分，但仍可步行 400 公尺的成人。已無法完成步行、急性疾病或安全性尚未確認者，需要另訂復健計畫。',
    dosage: '這是持續多年的中等強度組合方案，平均追蹤 2.6 年；起始負荷較輕，再逐步提高。分鐘數與組次是研究目標，不能要求每位長者第一天就完成，也不能把研究的 400 公尺結局當每天必做的測驗。',
    cue: '把「能否穩定持續」放在速度之前；需要輔具或陪同時，先讓團隊安排，再增加走路時間。',
    regression: '短段行走、增加休息或保留支撐均應由指導者調整。生病或中斷後重新評估起點，不補做累積欠下的運動量。',
    followUpLabel: '追蹤生活中的行動能力',
    followUp: '記錄外出距離、坐站難度及是否差點跌倒，再與團隊檢討。若原本能完成的日常路程逐漸縮短，即使沒有疼痛，也應重新找出原因。',
    signals: {
      green: '在安排的支撐與休息下能維持步態，沒有新增不適，日常活動未因訓練而受影響。',
      yellow: '步態變亂、差點跌倒或疲勞使日常活動下降：先縮短課程，向指導者回報後再進階。',
      red: '胸痛、昏厥或突然單側無力：停止並立即求助；跌倒受傷或新出現無法負重須就醫評估。',
    },
    evidence: '八中心、評估者盲化 RCT；運動組主要行動失能為 30.1%，健康教育組為 35.5%，危險比 HR 0.82（95% CI 0.69–0.98）。優點是樣本大、結局明確且追蹤較長；限制是受試者仍具基本行走能力、無法盲化運動參與者。不能解讀為避免所有失能，也不能把效果歸因於單一動作。',
    audience: '供長者、照顧者與復健團隊理解如何安排長期活動。不是急性住院、臥床或重度認知障礙者的通用處方。',
    sources: [{ label: 'Pahor M, Guralnik JM, Ambrosius WT, et al. Effect of Structured Physical Activity on Prevention of Major Mobility Disability in Older Adults: The LIFE Study Randomized Clinical Trial. JAMA. 2014;311(23):2387–2396. DOI: 10.1001/jama.2014.5616.', href: 'https://jamanetwork.com/journals/jama/fullarticle/1875328' }],
  },
  {
    ...REVIEW,
    id: 'sprintt-frailty-mobility-rct',
    selectionLabel: '衰弱與肌少症',
    searchAliases: ['SPRINTT', '肌少症', '衰弱', '肌肉量下降', '高齡行動功能'],
    supervision: 'professional-guidance',
    theme: 'teal',
    eyebrow: '2022 SPRINTT 多中心隨機試驗',
    title: '衰弱合併肌少症：運動與營養支持如何保留行動能力',
    summary: 'SPRINTT 把規律運動、活動追蹤與個別營養諮詢一起安排。對下肢功能較差的研究族群，這套方案減少行動失能；功能較好的族群未見相同效果，不能宣稱所有肌少症患者都同樣受益。',
    images: [trialImage('sprintt-frailty-mobility-rct', 'SPRINTT 的功能評估、有氧與肌力活動、居家練習及營養活動回饋四格示意')],
    steps: [
      { title: '確認衰弱與肌肉狀態', instruction: '團隊同時檢查下肢功能、肌肉量及步行能力，而非僅憑年齡或體重判斷肌少症。先確認哪些活動需要保護與協助。', dosage: '研究納入 70 歲以上、SPPB 3–9 分且尚能完成 400 公尺步行者。' },
      { title: '中心建立動作與負荷', instruction: '課程包含有氧、肌力、平衡與柔軟度；在指導下建立可持續的走路與下肢出力方式，再練習較有挑戰的內容。', dosage: '中心課程每週 2 次，負荷依自覺用力程度調整。' },
      { title: '循序加入居家活動', instruction: '先把學會的項目帶回家，記錄實際完成情況，再逐漸增加練習日。居家活動仍屬有團隊支持的同一套方案。', dosage: '居家由每週 1 次逐步增加，研究後期最多每週 4 次。' },
      { title: '回顧活動與飲食', instruction: '研究結合活動監測回饋與個別營養諮詢，檢視難以遵從的原因。飲食內容由專業人員依疾病與進食狀況安排。', dosage: '介入最長 36 個月；運動與營養追蹤並行。' },
    ],
    suitableFor: '適合已經專業確認身體衰弱及低肌肉量、仍保有基本步行能力者與團隊討論。試驗排除明顯認知障礙、已有行動失能及無法安全運動者，不能直接套用於所有衰弱長者。',
    dosage: '方案由建立習慣期進到維持期，持續安排中心及居家活動。研究走路目標為 Borg 6–20 分量表約 13 分，下肢肌力約 15–16 分；這些數字須先教會量表並確認耐受，不是「越吃力越好」的指令。',
    cue: '肌力、步行、平衡與飲食支持各有角色；只照圖做幾次運動，不能視為已完成試驗介入。',
    regression: '若無法兼顧全套內容，先與團隊選定可安全持續的項目，減少負荷或分段完成；飲食限制、體重下降或進食困難須一併回報。',
    followUpLabel: '用功能變化調整計畫',
    followUp: '追蹤行走、坐站與外出參與，不以體重增加或單次肌肉量數字作唯一成效。活動或飲食難以維持時，優先檢討障礙與可取得的協助。',
    signals: {
      green: '活動與飲食安排能持續執行，站走控制穩定，沒有新增不適。',
      yellow: '持續疲勞、步行能力下降、進食不足或差點跌倒：先調整並安排專業檢討。',
      red: '昏厥、胸痛、突然呼吸困難或新出現單側無力：立即停止並求助。',
    },
    evidence: '1,519 人、評估者盲化 RCT；預設主要族群 SPPB 3–7 分共 1,205 人，行動失能（主要分析也將死亡計入）為介入組 46.8%、教育組 52.7%，HR 0.78（95% CI 0.67–0.92）。SPPB 8–9 分組未見風險降低。多中心及預設分層提高可信度，但整套介入同時含營養與回饋，不能分離運動的單獨效果；RCT 亦不等於所有族群都有高確定性證據。',
    audience: '供高齡者及家屬理解衰弱管理的組合方案；須由復健與營養專業依個人疾病、功能及照顧資源調整。',
    sources: [{ label: 'Bernabei R, Landi F, Calvani R, et al. Multicomponent intervention to prevent mobility disability in frail older adults: randomised controlled trial (SPRINTT project). BMJ. 2022;377:e068788. DOI: 10.1136/bmj-2021-068788.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9092831/' }],
  },
  {
    ...REVIEW,
    id: 'taijiquan-falls-prevention-rct',
    selectionLabel: '高齡防跌太極',
    searchAliases: ['太極拳', '太極防跌', '跌倒預防', 'Tai Ji Quan', 'TJQMBB'],
    supervision: 'professional-guidance',
    theme: 'orange',
    eyebrow: '2018 三組隨機對照試驗',
    title: '高跌倒風險長者：治療性太極的重心與轉向練習',
    summary: '這篇研究測試經過改編的防跌太極課程，六個月內的跌倒次數少於伸展課程，也少於多模式運動。效果來自完整、持續且有教學的課程，不能等同任意太極影片或四個示範動作。',
    images: [trialImage('taijiquan-falls-prevention-rct', '治療性太極的安全起始姿勢、重心轉移、軀幹轉向及整合平衡四格示意')],
    steps: [
      { title: '先建立安全起點', instruction: '由指導者確認站姿、步行與必要支撐。研究使用八個改編動作及治療性活動，不以熟記招式或站得低為目標。', dosage: '先接受跌倒風險與活動能力評估。' },
      { title: '練習重心轉移', instruction: '在可控制範圍內感受重心在雙腳間移動，配合自然呼吸。指導者依能力調整承重與穩定度要求。', dosage: '屬完整課程的一部分；研究未提供通用的單動作每日次數。' },
      { title: '整合軀幹與視線轉向', instruction: '課程將軀幹、骨盆、眼頭手協調加入活動。轉向幅度與速度依平衡反應調整，不自行追求快速或極限轉動。', dosage: '以課堂分級練習為準，不額外指定秒數或角度。' },
      { title: '在課程中逐步挑戰', instruction: '將重心、轉向與站立控制連成活動；困難度由指導者決定。下課後記錄跌倒與差點跌倒，作為調整依據。', dosage: '每週 2 堂、每堂 60 分鐘，共 24 週。' },
    ],
    suitableFor: '研究納入 670 名 70 歲以上社區長者，有過跌倒或行動受限。是否適合站立課程須先評估；反覆昏厥、急性受傷或站立需大量協助者，不應直接照影片練習。',
    dosage: '三組接受相同頻率與時間的團體課：治療性太極、多模式運動或伸展。太極方案強調八式及其變化、重心位移與感覺動作整合；圖解只說明訓練構成，沒有取代完整的專業課程。',
    cue: '練習的重點是察覺並控制失衡趨勢；不要為了姿勢好看而加深蹲姿、急轉或自行取消輔具。',
    regression: '請指導者降低重心移動幅度、增加穩固支撐或改為較容易的活動。經調整的版本不能直接宣稱有和原試驗相同的防跌效果。',
    followUpLabel: '同時記錄跌倒與近跌倒',
    followUp: '帶著跌倒時間、環境與活動情境回診或回課堂檢討；若反覆出現新暈眩或腳步不穩，先找原因，不只增加練習量。',
    signals: {
      green: '可在安排的保護下移動重心，沒有新增暈眩，活動後仍能安全走動。',
      yellow: '必須突然抓住物品、連續踏步才能站穩或出現關節痛：停止該動作並請指導者降階。',
      red: '跌倒撞頭、昏厥、突然無力或胸痛：停止並立即就醫或求助。',
    },
    evidence: '評估者盲化、三組 RCT；24 週跌倒共為太極組 152 次、多模式組 218 次、伸展組 363 次。太極的跌倒發生率比相對伸展為 0.42，相對多模式為 0.69；這是事件率，不是每個人風險必降同樣比例。限制包含單一美國地區、跌倒自我回報、族群以白人為主，以及主要作者揭露課程授權利益關係。',
    audience: '供長者與照顧者選擇有系統的防跌課程；不是所有太極流派的療效證明，也不是獨自挑戰平衡的指引。',
    sources: [{ label: 'Li F, Harmer P, Fitzgerald K, et al. Effectiveness of a Therapeutic Tai Ji Quan Intervention vs a Multimodal Exercise Intervention to Prevent Falls Among Older Adults at High Risk of Falling: A Randomized Clinical Trial. JAMA Intern Med. 2018;178(10):1301–1310. DOI: 10.1001/jamainternmed.2018.3915.', href: 'https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/2701631' }],
  },
  {
    ...REVIEW,
    id: 'dapa-dementia-exercise-rct',
    selectionLabel: '失智症運動與認知',
    searchAliases: ['DAPA', '失智症運動', '認知退化', '阿茲海默症', '失智肌力'],
    supervision: 'medical-team',
    theme: 'violet',
    eyebrow: '2018 DAPA 隨機試驗・陰性結果',
    title: '失智症：體能訓練不能保證減緩認知退化',
    summary: 'DAPA 發現，四個月的中高強度有氧與肌力訓練，沒有減緩輕至中度失智症的認知退化。安排活動時，應先說清楚個人的體能與生活目標，不能將「更努力運動」宣稱為認知治療。',
    images: [trialImage('dapa-dementia-exercise-rct', 'DAPA 的個別評估、監督式固定腳踏車、肌力訓練及認知生活功能追蹤四格示意')],
    steps: [
      { title: '先訂生活與體能目標', instruction: '團隊評估疾病、用藥、理解指令及活動能力，並與本人及照顧者討論目標。不能把改善記憶力當作這套方案已證實的效果。', dosage: '每位參與者先接受個別評估。' },
      { title: '監督式固定車訓練', instruction: '研究在治療師與助理帶領下，以固定腳踏車進行有氧活動，依耐受調整負荷；本圖只介紹曾被研究的流程。', dosage: '研究為 5 分鐘暖身，再最多 25 分鐘中等至吃力踩踏。' },
      { title: '加入個別化肌力活動', instruction: '研究使用啞鈴手臂活動及坐站訓練，負重依能力調整。不要因研究曾使用負重背心，就自行替失智長者穿上負重。', dosage: '肌力內容納入每次 60–90 分鐘的團體課，由團隊處方。' },
      { title: '把認知與體能分開追蹤', instruction: '記錄活動參與、日常功能、情緒及照顧負擔。走得較遠或完成較重負荷，不等於認知退化受到控制。', dosage: '監督課每週 2 次、共 4 個月；主要認知結果追蹤至 12 個月。' },
    ],
    suitableFor: '試驗對象為社區中的輕至中度失智症患者，能自行坐椅及走約 3 公尺，並排除不適合運動的急性或不穩定疾病。重度失智、無法配合安全指令或需大量移位協助者不屬相同族群。',
    dosage: '原方案還鼓勵每週額外一小時居家活動，監督期後轉為居家維持。這些是研究安排，並非推薦用高強度治療失智症；是否運動、如何監督及做多久，應依本人意願、體能目標與醫療評估決定。',
    cue: '使用簡短且一致的提示，觀察本人意願與不舒服的表現。無法順利完成時，先調整環境與溝通，不以強迫或增加負重達到時數。',
    regression: '與團隊改選熟悉、較短且可接受的活動，增加陪同及休息。這是個別化調整方向，不是原試驗證明可以改善認知的替代方案。',
    followUpLabel: '以生活目標重新檢討成效',
    followUp: '若活動後持續混亂、害怕、跌倒或照顧負擔上升，應回報並重新設計計畫；不能只看運動出席率就判定介入適合。',
    signals: {
      green: '本人願意參與，在既有支持下能跟隨提示，日常狀態沒有因活動變差。',
      yellow: '異常疲累、持續抗拒、較平常混亂或活動後功能下降：暫停並聯絡照顧與醫療團隊。',
      red: '急性意識改變、昏厥、胸痛、突然單側無力或跌倒後明顯受傷：立即就醫。',
    },
    evidence: '494 人多中心 RCT（運動 329 人、通常照護 165 人），12 個月認知結果未受益，運動組 ADAS-cog 表現稍差，臨床意義仍不確定。日常活動、生活品質等亦未見組間改善。六週走路距離只在運動組追蹤，不能把組內改善當成隨機比較的體能療效。優點是樣本較大與盲化評估；仍不能推論所有形式、強度的活動都無價值。',
    audience: '供失智症患者家屬與醫療團隊討論合理運動目標；本篇重點是辨識證據限制，不建議自行複製高強度方案。',
    sources: [{ label: 'Lamb SE, Sheehan B, Atherton N, et al. Dementia And Physical Activity (DAPA) trial of moderate to high intensity exercise training for people with dementia: randomised controlled trial. BMJ. 2018;361:k1675. DOI: 10.1136/bmj.k1675.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5953238/' }],
  },
  {
    ...REVIEW,
    id: 'leaps-stroke-walking-rct',
    selectionLabel: '中風步行復健選擇',
    searchAliases: ['LEAPS', '中風走路', '減重跑步機', '中風居家復健', '步態訓練'],
    supervision: 'medical-team',
    theme: 'blue',
    eyebrow: '2011 LEAPS 隨機對照試驗',
    title: '中風後走路：減重跑步機未優於治療師帶領的居家運動',
    summary: 'LEAPS 比較專業減重跑步機訓練與治療師帶領的居家肌力、平衡活動，一年後前者未顯示較好的功能性行走結果。器材是否昂貴，不應取代對安全、可行性與個人需要的評估。',
    images: [trialImage('leaps-stroke-walking-rct', 'LEAPS 的步行評估、吊帶支撐跑步機、地面步行及治療師居家肌力平衡方案四格示意')],
    steps: [
      { title: '評估步行與風險', instruction: '團隊檢查步行速度、平衡、心肺耐受與協助需要，決定適合的路徑。不要自行用研究分級數字決定何時放開輔具。', dosage: '研究於中風約 2 個月時分組。' },
      { title: '專業減重步行方案', instruction: '其中兩組使用吊帶減重跑步機，在治療師及必要協助下練步行；支撐量與速度由團隊調整，非家用跑步機可直接替代。', dosage: '研究分別在中風後約 2 或 6 個月啟動此方案。' },
      { title: '銜接地面行走', instruction: '減重步行方案也包含地面步行，觀察器材外的實際行走能力。這是原方案的一部分，不是單做跑步機的療效驗證。', dosage: '各方案預定 36 次、每次 90 分鐘，於 12–16 週完成。' },
      { title: '另一條路徑：居家肌力平衡', instruction: '對照組由物理治療師在家提供漸進肌力與平衡活動。它是替代研究組別，不是前三步之後每人都必須追加的課程。', dosage: '居家組於中風約 2 個月啟動，同樣預定 36 次。' },
    ],
    suitableFor: '研究納入 408 名中風後仍有中重度行走限制者，分組時步速低於每秒 0.8 公尺。是否能參與須先經團隊評估；急性不穩定中風、尚不能安全接受訓練或重度共病者，不可直接套用。',
    dosage: '36 次與 90 分鐘是完整研究課程的預定劑量，包含不同內容與休息，並非連續在跑步機上走 90 分鐘。各組也可能接受研究外的通常復健，因此研究不能回答完全停止復健會如何。',
    cue: '在足夠保護下練習，並追蹤生活中的安全行走；不要為追求步數，忽略暈眩、姿勢控制或跌倒。',
    regression: '出現不穩時由團隊增加協助、降低訓練難度，或調整為更合適的平衡與肌力內容。家屬不可自行操作吊帶減重或提高跑步機速度。',
    followUpLabel: '比較功能，也比較安全與負擔',
    followUp: '與團隊定期檢視家中移位、外出路程、跌倒及訓練可持續性；若每次課後反而更難行走，應先調整方案再追求總量。',
    signals: {
      green: '在既定協助下步態可控制，休息後能恢復，沒有新增暈眩或神經症狀。',
      yellow: '差點跌倒、拖腳明顯增加、暈眩或疲勞妨礙日常行動：停止該段訓練並回報。',
      red: '新出現臉歪、單側無力、語言改變、劇烈頭痛、昏厥或胸痛：立即求助，不繼續訓練。',
    },
    evidence: '408 人多中心 RCT；一年時整體 52% 提升行走功能等級，兩種啟動時間的減重步行都未優於居家組。減重步行組訓練中暈眩或將昏倒較多，嚴重步行障礙的早期組有較多反覆跌倒。優點是直接比較可行的復健選項；限制包含參與者無法盲化及研究外復健差異。未證明優越不等於所有方案完全等效，更不等於復健無效。',
    audience: '供中風患者、家屬與復健團隊共同選擇訓練方式；圖中路徑為研究組別比較，不能串成自行練習的固定處方。',
    sources: [{ label: 'Duncan PW, Sullivan KJ, Behrman AL, et al. Body-Weight–Supported Treadmill Rehabilitation after Stroke. N Engl J Med. 2011;364(21):2026–2036. DOI: 10.1056/NEJMoa1010790.', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3175688/' }],
  },
  {
    ...REVIEW,
    id: 'avert-early-stroke-mobilisation-rct',
    selectionLabel: '急性中風活動時機',
    searchAliases: ['AVERT', '中風早期復健', '中風下床', '中風24小時', '急性中風活動'],
    supervision: 'medical-team',
    theme: 'orange',
    eyebrow: '2015 AVERT 隨機試驗・重要安全結果',
    title: '急性中風：更早、更多下床活動不一定更好',
    summary: 'AVERT 顯示，發病 24 小時內增加高劑量下床活動，三個月功能結果反而較差。本篇協助家屬理解活動時機與監測，圖解不是急性中風下床教學，也不能用來要求患者臥床或提前起身。',
    images: [trialImage('avert-early-stroke-mobilisation-rct', '急性中風由醫療團隊確認資格、安排安全姿位、決定活動及監測重新評估四格示意')],
    steps: [
      { title: '團隊確認活動資格', instruction: '由中風醫療團隊依神經狀態、生命徵象與治療情況判斷可否活動。家屬先確認當日計畫，不以發病經過幾小時自行決定。', dosage: '依住院團隊指示，沒有通用自行啟動時點。' },
      { title: '安排安全姿位與協助', instruction: '先由照護人員決定合適姿位與移位協助，確認管線與環境。圖示僅表達有專業保護，不代表所有人此時都該坐到床邊。', dosage: '姿位與協助程度由團隊當次評估。' },
      { title: '個別決定是否及如何活動', instruction: '站立、坐起與步行是否安排、每次多久，需依當時狀態決定。不要因擔心錯過復健時機，額外增加下床次數。', dosage: '本篇不提供重複 AVERT 高劑量方案的次數或分鐘數。' },
      { title: '監測後重新評估', instruction: '活動前後由團隊監測反應，必要時暫停或調整。家屬發現神智、說話或肢體表現改變，立即告知護理與醫療人員。', dosage: '每次活動均須配合當下照護計畫。' },
    ],
    suitableFor: '本篇供急性中風患者家屬了解研究與溝通。試驗納入符合生理條件的成年缺血性或出血性中風患者，處於急性中風病房；不能把研究直接套到出院後或慢性期。',
    dosage: 'AVERT 比較通常中風病房照護，與在通常照護外增加頻繁、較高劑量的極早期活動。介入組 92%、通常照護組 59% 在 24 小時內已開始活動，因此不是「早期活動對完全不動」的比較。',
    cue: '與團隊確認今日允許的活動及需要幾人協助，比追求「越早越好」更有用；同樣不能由此試驗推論所有早期活動都有害。',
    regression: '若耐受或神經狀態改變，由醫療團隊重新安排姿位與活動；家屬不要自行把原方案加量，也不要擅自取消全部活動。',
    followUpLabel: '住院期間即時回報變化',
    followUp: '交班或會談時確認當日活動限制、監測方式及誰可以協助。出院前另取得適合當時功能的復健計畫，不能把急性期研究當作長期訓練時程。',
    signals: {
      green: '僅表示團隊確認可執行當次照護計畫；不能由家屬單憑看起來有精神就自行加量。',
      yellow: '活動時不舒服、異常疲憊或較平常難以配合：立刻告知現場醫護，由團隊判斷是否暫停。',
      red: '新的或加重的單側無力、說話改變、意識下降、劇烈頭痛或呼吸異常：立刻呼叫醫護或緊急救援。',
    },
    evidence: '五國 56 病房、2,104 人 RCT，三個月追蹤率 99%。功能良好（mRS 0–2）為高劑量極早期組 46%、通常照護組 50%，調整後 OR 0.73（95% CI 0.59–0.90）。死亡比例差異未達統計顯著，不能宣稱試驗證明增加死亡。規模大且有盲化結局評估；但方案同時改變時機、頻率與總量，不能分離哪項造成不利結果，也不能據此制定人人相同的最佳下床時間。',
    audience: '本篇是醫療團隊限定情境的證據解讀與安全溝通資料；急性中風的姿位、移位與活動均以照護團隊當次指示為準。',
    sources: [{ label: 'AVERT Trial Collaboration group. Efficacy and safety of very early mobilisation within 24 h of stroke onset (AVERT): a randomised controlled trial. Lancet. 2015;386(9988):46–55. DOI: 10.1016/S0140-6736(15)60690-0.', href: 'https://pubmed.ncbi.nlm.nih.gov/25892679/' }],
  },
  {
    ...REVIEW,
    id: 'icare-stroke-arm-training-rct',
    selectionLabel: '中風上肢任務練習',
    searchAliases: ['ICARE', 'ASAP', '中風手部復健', '中風上肢', '任務導向訓練'],
    supervision: 'medical-team',
    theme: 'teal',
    eyebrow: '2016 ICARE 第三期隨機試驗',
    title: '中風上肢：任務導向課程沒有顯示比通常職能治療更好',
    summary: 'ICARE 比較結構化任務練習與通常職能治療，十二個月上肢恢復未見前者較佳。可把目標放在有意義、可分級的生活任務，但不能保證某個課程名稱或增加時數一定帶來額外恢復。',
    images: [trialImage('icare-stroke-arm-training-rct', 'ICARE 的生活任務選擇、患側上肢練習、共同調整難度與日常情境轉移四格示意')],
    steps: [
      { title: '共同選擇生活任務', instruction: '患者與治療師討論想恢復的動作及目前限制，選擇有目的的任務。拿取物品只是圖解例子，並非研究要求每人都練同一物件。', dosage: '先進行上肢能力與個人目標評估。' },
      { title: '分級練習患側動作', instruction: '依能力練習有目的的上肢與手部活動，觀察能否穩定完成。研究對象還有主動手指伸展能力，不能直接套到完全無主動動作的人。', dosage: 'ASAP 方案預定 30 次、每次 1 小時。' },
      { title: '共同調整任務難度', instruction: '治療師與患者共同找出動作障礙，依表現調整物件、環境或協助。不要自行限制健側手，以為那是所有人必需的訓練。', dosage: '預定每週 3 次、約 10 週；研究要求在分組後 16 週內完成。' },
      { title: '連結日常生活', instruction: '討論如何把練習帶到有意義的生活情境，追蹤能否使用患手完成目標，而非只計算重複次數。', dosage: '研究主要結果追蹤至分組後 12 個月。' },
    ],
    suitableFor: '研究納入 361 名中風後主要為中度上肢運動障礙者，在中風後 14–106 天內分組，仍有最低限度的手及手指主動伸展。嚴重認知、感覺或忽略問題者不屬可直接外推的族群。',
    dosage: '三組分別為 ASAP 任務導向訓練、同樣預定 30 小時的通常職能治療、以及未指定治療劑量的通常照護。最後一組仍可接受復健，不能稱作「完全沒治療組」；研究也沒有提供適合所有人的固定手部組次。',
    cue: '讓練習對應本人想做的事情，並在需要時接受協助。課程是否合適應看安全、目標達成與能否持續，不只看名稱。',
    regression: '由治療師改選較容易操作的物件、增加前臂支撐或拆解任務；圖示調整屬臨床討論方向，不宣稱是單獨經試驗驗證的動作。',
    followUpLabel: '定期檢視患手的實際使用',
    followUp: '追蹤同一項生活任務需要多少協助、是否疼痛以及能否在課堂外使用患手；進展停滯時重新評估障礙，不只追加練習時數。',
    signals: {
      green: '在團隊設定的姿勢與協助下能練習，沒有新增肩手痛，生活功能未惡化。',
      yellow: '肩手疼痛增加、腫脹、明顯代償或疲勞影響日常活動：減少負荷並回報治療師。',
      red: '突然新的單側無力、語言障礙、臉歪或意識改變：立即求助；新傷或劇痛停止練習並評估。',
    },
    evidence: '第三期、多中心、評估者盲化 RCT；三組在 12 個月主要 Wolf Motor Function Test 結果未見結構化課程的優越性。納入同劑量對照有助區分課程內容與時數；限制是參與者無法盲化、通常照護內容有差異，而且結論限於試驗涵蓋的障礙程度與時期。結果不能解讀成任務練習無效、職能治療不必做，或所有劑量均等效。',
    audience: '供中風患者與職能治療、復健團隊選擇上肢訓練方式；任務例子需個別化，不是通用的四動作復健套餐。',
    sources: [{ label: 'Winstein CJ, Wolf SL, Dromerick AW, et al. Effect of a Task-Oriented Rehabilitation Program on Upper Extremity Recovery Following Motor Stroke: The ICARE Randomized Clinical Trial. JAMA. 2016;315(6):571–581. DOI: 10.1001/jama.2016.0276.', href: 'https://jamanetwork.com/journals/jama/fullarticle/2488308' }],
  },
  {
    ...REVIEW,
    id: 'sparx-parkinson-treadmill-rct',
    selectionLabel: '早期巴金森氏症跑步機',
    searchAliases: ['SPARX', '巴金森氏症', '帕金森', '高強度有氧', '跑步機訓練'],
    supervision: 'medical-team',
    theme: 'blue',
    eyebrow: '2018 SPARX 第二期隨機試驗',
    title: '早期巴金森氏症：高強度跑步機的初步證據與限制',
    summary: 'SPARX 顯示，經篩選、尚未用藥的早期巴金森氏症患者，可以在研究監測下進行較高強度跑步機活動。結果支持進一步大型試驗，尚不能當作已證明延緩疾病或可以停藥的依據。',
    images: [trialImage('sparx-parkinson-treadmill-rct', 'SPARX 的運動測試、跑步機暖身、心率監測訓練與緩和追蹤四格示意')],
    steps: [
      { title: '先做運動能力測試', instruction: '研究以漸增運動測試量得最大心率，並確認能安全參與。目標不是用年齡公式自行估算後直接衝高強度。', dosage: '開始前由團隊篩選及測試。' },
      { title: '暖身並循序增加', instruction: '先暖身，再由團隊逐步增加頻率與強度。研究初期有現場監督，不是第一天就完成目標心率與總量。', dosage: '每次暖身 5–10 分鐘；前 8 週逐步達到目標。' },
      { title: '用心率監測訓練', instruction: '研究透過跑步機速度或坡度調整負荷，持續記錄心率。是否使用跑步機及如何保護，需依步態與跌倒風險決定。', dosage: '高強度組目標為實測最大心率 80%–85%，主訓練 30 分鐘。' },
      { title: '緩和並回顧耐受', instruction: '課程最後放慢活動，記錄不適並接受團隊追蹤。任何用藥變化都要回報，不能因研究包含未用藥者而自行停藥。', dosage: '緩和 5–10 分鐘；預定每週 4 天，共 26 週。' },
    ],
    suitableFor: '128 名、40–80 歲、早期且尚未接受多巴胺治療的巴金森氏症受試者。晚期疾病、明顯平衡障礙、其他重要疾病或服藥狀況不同者，不能直接採同一負荷。',
    dosage: '研究另比較最大心率 60%–65% 的中強度組及通常照護組。高強度組實際平均每週約 2.8 天，與預定 4 天不同；前兩週均有監督，之後仍至少每月到研究中心追蹤。目標、實際達成量與安全支持需一起解讀。',
    cue: '運動強度由測試、症狀及監測共同決定；不能只為追心率數字而忽略步態，或在沒有人協助時提高速度。',
    regression: '若耐受或行走安全不足，由團隊調低速度、坡度或時間，必要時重選運動方式；換成其他方式不能自動宣稱重現 SPARX 的結果。',
    followUpLabel: '觀察運動與日常狀態',
    followUp: '記錄心率、完成情況、跌倒與症狀變化，由團隊評估是否調整。研究中的短期運動量表結果不能取代長期疾病追蹤。',
    signals: {
      green: '在安排的保護下維持步態，心率落在團隊訂定範圍，沒有新增不適。',
      yellow: '拖步、凍結、心悸、暈眩或異常疲倦：停止該段活動並回報，重新檢討負荷。',
      red: '胸痛、昏厥、呼吸困難或新出現單側無力：立即停止並緊急求助。',
    },
    evidence: '第二期、三組、評估者盲化 RCT，主要目的包括可行性與是否值得做第三期研究。高強度組六個月 UPDRS 運動分數平均改變 0.3 分，通常照護組惡化 3.2 分，達到繼續研究的非無效性判準。這不是確證疾病修飾效果的設計；樣本小、族群經篩選、追蹤僅半年，不能宣稱高強度已證實阻止惡化或優於所有其他運動。',
    audience: '供早期巴金森氏症患者與神經、復健團隊討論有氧運動；研究心率與劑量必須先經個別評估，不能直接自行套用。',
    sources: [{ label: 'Schenkman M, Moore CG, Kohrt WM, et al. Effect of High-Intensity Treadmill Exercise on Motor Symptoms in Patients With De Novo Parkinson Disease: A Phase 2 Randomized Clinical Trial. JAMA Neurol. 2018;75(2):219–226. DOI: 10.1001/jamaneurol.2017.3517.', href: 'https://jamanetwork.com/journals/jamaneurology/fullarticle/2664948' }],
  },
  {
    ...REVIEW,
    id: 'park-in-shape-cycling-rct',
    selectionLabel: '巴金森氏症居家固定車',
    searchAliases: ['Park-in-Shape', '巴金森腳踏車', '帕金森居家運動', '固定腳踏車', '遠距復健'],
    supervision: 'medical-team',
    theme: 'green',
    eyebrow: '2019 Park-in-Shape 隨機試驗',
    title: '輕度巴金森氏症：有遠距支持的居家固定車訓練',
    summary: '六個月的居家固定車有氧訓練，在離藥狀態的動作量表上比伸展組保留較好的表現。研究同時提供遠距支持與動機工具，不能簡化成買一台車就能延緩疾病，也不需要為了運動而自行停藥。',
    images: [trialImage('park-in-shape-cycling-rct', 'Park-in-Shape 的適用性評估、居家固定車、遠距回饋與定期功能追蹤四格示意')],
    steps: [
      { title: '確認居家運動是否合適', instruction: '先由團隊確認病情、治療狀況及居家訓練安全。研究對象是輕度患者，並不代表所有巴金森氏症都能獨自使用固定車。', dosage: '研究對象 30–75 歲、Hoehn–Yahr 分期不高於 2。' },
      { title: '安排固定車有氧課程', instruction: '使用固定於室內的腳踏車，負荷依團隊處方。研究搭配虛擬畫面與遊戲元素；它不是戶外騎車安全性的試驗。', dosage: '每週 3 次、每次 30–45 分鐘，共 6 個月。' },
      { title: '保留遠距支持與回饋', instruction: '將完成情形及不適回報給支持人員，檢討阻礙規律活動的原因。居家是運動地點，不表示整套方案沒有專業監督。', dosage: '兩組都使用動機應用程式並接受遠距支持。' },
      { title: '由團隊追蹤功能', instruction: '比較生活表現、運動耐受與動作量表。研究的離藥測驗由研究團隊安排，不能把它理解為平日訓練前要停藥。', dosage: '主要動作量表結果於 6 個月評估。' },
    ],
    suitableFor: '適合輕度巴金森氏症、日常活動量少，且經團隊確認可用居家固定車者討論。藥物治療須保持醫療團隊安排；有凍結、姿勢性暈眩或移位困難時，先評估上、下車與陪同需要。',
    dosage: '130 人分成固定車有氧與伸展兩組，各 65 人，課程時間與遠距支持相同。上述頻率與時間是研究安排；器材轉速、阻力與心率目標須依個別評估調整，不能把別人的設定直接套用到自己。',
    cue: '先確保上、下車與踩踏過程可控制，再依團隊回饋逐步調整；不要把研究效果套到沒有監測的極限踩踏。',
    regression: '若出現不適或移位困難，由團隊縮短課程、增加協助或重新選擇器材。降階後的目標以個人耐受與功能為準，不保證等同原試驗效果。',
    followUpLabel: '把規律性與不良反應一起回報',
    followUp: '追蹤漏做原因、跌倒、疼痛及日常行動，定期與團隊檢討。研究期間有參與者未完成方案，持續支持與調整本身就是實務的重要部分。',
    signals: {
      green: '能在既定支持下安全上下車，踩踏與休息後狀態穩定，沒有新增不適。',
      yellow: '頭暈、心悸、關節痛或疲勞延續並影響生活：停止當次課程，聯絡團隊調整。',
      red: '昏厥、胸痛、明顯呼吸困難或新的神經症狀：立即停止並求助。',
    },
    evidence: '單中心 RCT；125 人完成主要追蹤，離藥狀態 MDS-UPDRS 動作分數的組間差為 4.2 分（95% CI 1.6–6.9），有利有氧組。兩組都知道自己練什麼，只不知另一組內容；不能把雙盲稱呼理解為完全不知道介入。限制包含樣本小、僅輕度患者及六個月追蹤；結果支持短期動作表現，不足以證明改變神經退化病程或長期效益。',
    audience: '供輕度巴金森氏症患者、家屬與醫療團隊選擇居家有氧方案；須保留專業處方、遠距回饋與原本藥物治療。',
    sources: [{ label: "van der Kolk NM, de Vries NM, Kessels RPC, et al. Effectiveness of home-based and remotely supervised aerobic exercise in Parkinson's disease: a double-blind, randomised controlled trial. Lancet Neurol. 2019;18(11):998–1008. DOI: 10.1016/S1474-4422(19)30285-6.", href: 'https://pubmed.ncbi.nlm.nih.gov/31521532/' }],
  },
]
